export default [
  {
    path: '/litellm-ops',
    name: 'litellmops',
    icon: 'wallet',
    access: 'canAccessRoute',
    routes: [
      {
        path: '/litellm-ops/gateway',
        name: 'gateway',
        icon: 'dashboard',
        component: './LitellmOps/Gateway',
        access: 'canAccessRoute',
        permission: 'litellmops:gateway-read',
      },
      {
        path: '/litellm-ops/users',
        name: 'users',
        icon: 'team',
        component: './LitellmOps/Users',
        access: 'canAccessRoute',
        permission: 'litellmops:user-list',
      },
      {
        path: '/litellm-ops/keys',
        name: 'keys',
        icon: 'idcard',
        component: './LitellmOps/Keys',
        access: 'canAccessRoute',
        permission: 'litellmops:key-list',
      },
      {
        path: '/litellm-ops/bills',
        name: 'bills',
        icon: 'fileText',
        component: './LitellmOps/Bills',
        access: 'canAccessRoute',
        permission: 'litellmops:bills',
      },
      {
        path: '/litellm-ops/orgs',
        name: 'orgs',
        icon: 'apartment',
        component: './LitellmOps/Orgs',
        access: 'canAccessRoute',
        permission: 'litellmops:org-list',
      },
      {
        path: '/litellm-ops/sales',
        name: 'sales',
        icon: 'shoppingCart',
        component: './LitellmOps/Sales',
        access: 'canAccessRoute',
        permission: 'litellmops:order-read',
      },
    ],
  },
];
