// Code generated by mss module template 1.3.0-frontend-v6.2 sync. DO NOT EDIT.

export default [
  {
    path: "/suppliers",
    name: "supplier",
    icon: "shop",
    component: "./generated/Supplier",
    access: 'canAccessRoute',
    permission: "/suppliers",
  },
];
