# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "area/backend"
      - "type/security"
  - package-ecosystem: "gomod"
    directory: "/cmd/tools/pr"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "area/devops"
      - "type/security"
  - package-ecosystem: "gomod"
    directory: "/compose/consul"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "area/devops"
      - "type/security"
  - package-ecosystem: "gomod"
    directory: "/compose/kafka"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "area/devops"
      - "type/security"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "area/devops"
      - "type/security"
