name: (beta)Deploy To Cloudflare

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cicd:
    uses: mss-boot-io/mss-boot-admin-antd/.github/workflows/cf.yml@main
    with:
      env: beta
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
