on:
  workflow_call:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: string
    secrets:
      CF_API_TOKEN:
        description: 'Cloudflare API Token'
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    concurrency:
      group: cloudflare-${{ inputs.env }}
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:${{ inputs.env }}

      - name: Install Dependencies for Workers Site
        working-directory: ./workers-site
        run: pnpm install --frozen-lockfile

      - name: fix route
        run: |
          cp dist/index.html dist/404.html
          cp -r workers-site dist/

      - name: deploy ${{ inputs.env }}
        uses: cloudflare/wrangler-action@v4
        if: ${{ inputs.env == 'alpha' || inputs.env == 'beta' || inputs.env == 'prod' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ inputs.env }}
