FROM golang:1.21-alpine AS builder

WORKDIR /go/src/github.com/mss-boot-io/mss-boot-admin

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 go build -o admin main.go

FROM alpine

LABEL authors="lwnmengjing"

WORKDIR /app

COPY --from=builder /go/src/github.com/mss-boot-io/mss-boot-admin/admin /app/admin

ENTRYPOINT ["/app/admin", "server"]