on:
  workflow_call:
    secrets:
      ssh_private_key:
        required: true
        description: 'SSH private key for git push'

permissions:
  contents: read

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:${{ github.repository }}.git
          ssh_private_key: ${{ secrets.ssh_private_key }}
