// Code generated by mss application template __MSS_GENERATOR_VERSION__. DO NOT EDIT.
package main

import (
	"context"
	"log"

	adminapp "__MSS_DISTRIBUTION_BACKEND_MODULE__/app"
	"__MSS_APP_MODULE__/internal/modules/all"
)

func main() {
	if err := adminapp.ExecuteContext(
		context.Background(),
		adminapp.WithBusinessModules(all.Modules()...),
	); err != nil {
		log.Fatal(err)
	}
}
