// Code generated by mss module template 1.1.0-frontend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

import { hasPermission } from '@/utils/authorization';
import type { AuthorizationIdentity } from '@/utils/authorization';

import type {
  SupplierQuery,
  SupplierTableParams,
  SupplierTableSorter,
} from './types';

export const supplierPermissionPaths = {
  route: '/suppliers',
  list: '/suppliers/permissions/list',
  read: '/suppliers/permissions/read',
  create: '/suppliers/permissions/create',
  update: '/suppliers/permissions/update',
  delete: '/suppliers/permissions/delete',
  export: '/suppliers/permissions/export',
} as const;

export type SupplierCapabilities = {
  canList: boolean;
  canRead: boolean;
  canCreate: boolean;
  canUpdate: boolean;
  canDelete: boolean;
  canExport: boolean;
};

export const getSupplierCapabilities = (
  identity?: AuthorizationIdentity,
): SupplierCapabilities => ({
  canList:
    hasPermission(identity, supplierPermissionPaths.route) &&
    hasPermission(identity, supplierPermissionPaths.list),
  canRead: hasPermission(identity, supplierPermissionPaths.read),
  canCreate: hasPermission(identity, supplierPermissionPaths.create),
  canUpdate: hasPermission(identity, supplierPermissionPaths.update),
  canDelete: hasPermission(identity, supplierPermissionPaths.delete),
  canExport: hasPermission(identity, supplierPermissionPaths.export),
});

export type SupplierPageState = 'forbidden' | 'error' | 'ready';

export const resolveSupplierPageState = (
  capabilities: SupplierCapabilities,
  hasError: boolean,
): SupplierPageState => {
  if (!capabilities.canList) return 'forbidden';
  return hasError ? 'error' : 'ready';
};

export const buildSupplierQuery = (
  params: SupplierTableParams,
  sorter: SupplierTableSorter = {},
): SupplierQuery => {
  const query: SupplierQuery = {};
  if (typeof params.current === 'number') query.current = params.current;
  if (typeof params.pageSize === 'number') query.pageSize = params.pageSize;
  if (typeof params.code === 'string' && params.code.trim() !== '') {
    query.q = params.code.trim();
  }
  if (typeof params.country === 'string') {
    query.country = params.country as string;
  }
  if (typeof params.creditLevel === 'string') {
    query.creditLevel = params.creditLevel as string;
  }
  if (params.enabled === true || params.enabled === 'true') {
    query.enabled = true;
  } else if (params.enabled === false || params.enabled === 'false') {
    query.enabled = false;
  }
  const sorted = Object.entries(sorter).find(([, direction]) => Boolean(direction));
  if (sorted) {
    const [sortBy, direction] = sorted;
    switch (sortBy) {
      case 'code':
        query.sortBy = sortBy;
        query.sortOrder = direction === 'descend' ? 'desc' : 'asc';
        break;
      case 'name':
        query.sortBy = sortBy;
        query.sortOrder = direction === 'descend' ? 'desc' : 'asc';
        break;
      default:
        break;
    }
  }
  return query;
};

type RequestFailure = {
  response?: { status?: number };
  status?: number;
};

export const getSupplierRequestStatus = (error: unknown): number | undefined => {
  const failure = error as RequestFailure | undefined;
  return failure?.response?.status ?? failure?.status;
};
