// Code generated by mss module template 1.1.0-frontend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

import {
  buildSupplierQuery,
  getSupplierCapabilities,
  getSupplierRequestStatus,
  resolveSupplierPageState,
  supplierPermissionPaths,
} from './contracts';

describe('supplier generated frontend contracts', () => {
  test('projects exact route and action permission visibility', () => {
    const identity = {
      permissions: {
        [supplierPermissionPaths.route]: true,
        [supplierPermissionPaths.list]: true,
        [supplierPermissionPaths.read]: true,
        [supplierPermissionPaths.export]: true,
      },
    };

    expect(getSupplierCapabilities(identity)).toEqual({
      canList: true,
      canRead: true,
      canCreate: false,
      canUpdate: false,
      canDelete: false,
      canExport: true,
    });
    expect(resolveSupplierPageState(getSupplierCapabilities(), false)).toBe(
      'forbidden',
    );
    expect(resolveSupplierPageState(getSupplierCapabilities(identity), true)).toBe(
      'error',
    );
  });

  test('maps generated search, filters, and sorting to the backend query', () => {
    expect(
      buildSupplierQuery(
        {
          current: 2,
          pageSize: 20,
          code: '  ACME  ',
          country: 'CN',
          creditLevel: "preferred",
          enabled: 'false',
        },
        {
          code: 'descend',
        },
      ),
    ).toEqual({
      current: 2,
      pageSize: 20,
      q: 'ACME',
      country: 'CN',
      creditLevel: "preferred",
      enabled: false,
      sortBy: 'code',
      sortOrder: 'desc',
    });
  });

  test('recognizes conflict responses without depending on one request library error class', () => {
    expect(getSupplierRequestStatus({ response: { status: 409 } })).toBe(409);
    expect(getSupplierRequestStatus({ status: 503 })).toBe(503);
  });
});
