// Code generated by mss module template 1.1.0-frontend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

import {
  DownloadOutlined,
  PlusOutlined,
} from '@ant-design/icons';
import {
  ModalForm,
  PageContainer,
  ProDescriptions,
  ProFormSelect,
  ProFormSwitch,
  ProFormText,
  ProTable,
} from '@ant-design/pro-components';
import type {
  ActionType,
  ProColumns,
  ProDescriptionsItemProps,
} from '@ant-design/pro-components';
import { useIntl, useModel } from '@umijs/max';
import {
  Alert,
  Button,
  Drawer,
  Empty,
  Grid,
  Popconfirm,
  Result,
  Space,
  Spin,
  Tag,
  message,
} from 'antd';
import React, { useMemo, useRef, useState } from 'react';

import {
  buildSupplierQuery,
  getSupplierCapabilities,
  getSupplierRequestStatus,
  resolveSupplierPageState,
} from './contracts';
import {
  createSupplier,
  deleteSupplier,
  exportSupplier,
  getSupplier,
  listSupplier,
  updateSupplier,
} from './service';
import type {
  CreateSupplierInput,
  Supplier,
  SupplierQuery,
} from './types';

const localePrefix = 'modules.supplier';

const SupplierPage: React.FC = () => {
  const intl = useIntl();
  const { initialState } = useModel('@@initialState');
  const screens = Grid.useBreakpoint();
  const actionRef = useRef<ActionType>();
  const [pageError, setPageError] = useState(false);
  const [editorOpen, setEditorOpen] = useState(false);
  const [editorRecord, setEditorRecord] = useState<Supplier>();
  const [formError, setFormError] = useState<string>();
  const [detailOpen, setDetailOpen] = useState(false);
  const [detailLoading, setDetailLoading] = useState(false);
  const [detailRecord, setDetailRecord] = useState<Supplier>();
  const [detailError, setDetailError] = useState<string>();
  const [currentQuery, setCurrentQuery] = useState<SupplierQuery>({});

  const capabilities = useMemo(
    () => getSupplierCapabilities(initialState?.currentUser),
    [initialState?.currentUser],
  );
  const pageState = resolveSupplierPageState(capabilities, pageError);
  const title = intl.formatMessage({ id: `${localePrefix}.title` });
  const creditLevelOptions = [
    {
      value: "preferred",
      label: intl.formatMessage({ id: `${localePrefix}.enums.creditLevel.preferred` }),
      color: 'green',
    },
    {
      value: "normal",
      label: intl.formatMessage({ id: `${localePrefix}.enums.creditLevel.normal` }),
      color: 'blue',
    },
    {
      value: "restricted",
      label: intl.formatMessage({ id: `${localePrefix}.enums.creditLevel.restricted` }),
      color: 'orange',
    },
    {
      value: "blocked",
      label: intl.formatMessage({ id: `${localePrefix}.enums.creditLevel.blocked` }),
      color: 'red',
    },
  ];

  if (pageState === 'forbidden') {
    return (
      <PageContainer title={title}>
        <Result
          status="403"
          title="403"
          subTitle={intl.formatMessage({ id: `${localePrefix}.states.forbidden` })}
        />
      </PageContainer>
    );
  }

  if (pageState === 'error') {
    return (
      <PageContainer title={title}>
        <Result
          status="error"
          title={intl.formatMessage({ id: `${localePrefix}.states.error` })}
          extra={
            <Button type="primary" onClick={() => setPageError(false)}>
              {intl.formatMessage({ id: `${localePrefix}.actions.retry` })}
            </Button>
          }
        />
      </PageContainer>
    );
  }

  const columns: ProColumns<Supplier>[] = [
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.code` }),
      dataIndex: 'code',
      width: 180,
      sorter: true,
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.name` }),
      dataIndex: 'name',
      width: 240,
      sorter: true,
      search: false,
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.country` }),
      dataIndex: 'country',
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.contactName` }),
      dataIndex: 'contactName',
      search: false,
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.contactEmail` }),
      dataIndex: 'contactEmail',
      search: false,
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.creditLevel` }),
      dataIndex: 'creditLevel',
      valueEnum: Object.fromEntries(
        creditLevelOptions.map((option) => [option.value, { text: option.label }]),
      ),
      render: (_, record) => {
        const option = creditLevelOptions.find((item) => item.value === record.creditLevel);
        return option ? <Tag color={option.color}>{option.label}</Tag> : record.creditLevel;
      },
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.enabled` }),
      dataIndex: 'enabled',
      valueType: 'select',
      valueEnum: {
        true: { text: intl.formatMessage({ id: `${localePrefix}.values.enabled` }) },
        false: { text: intl.formatMessage({ id: `${localePrefix}.values.disabled` }) },
      },
      render: (_, record) => (
        <Tag color={record.enabled ? 'green' : 'default'}>
          {intl.formatMessage({
            id: `${localePrefix}.values.${record.enabled ? 'enabled' : 'disabled'}`,
          })}
        </Tag>
      ),
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.actions.label` }),
      valueType: 'option',
      fixed: screens.md ? 'right' : undefined,
      render: (_, record) => (
        <Space wrap>
          {capabilities.canRead && (
            <Button
              type="link"
              onClick={async () => {
                setDetailOpen(true);
                setDetailLoading(true);
                setDetailError(undefined);
                setDetailRecord(undefined);
                try {
                  setDetailRecord(await getSupplier(record.id, { skipErrorHandler: true }));
                } catch {
                  setDetailError(intl.formatMessage({ id: `${localePrefix}.errors.request` }));
                } finally {
                  setDetailLoading(false);
                }
              }}
            >
              {intl.formatMessage({ id: `${localePrefix}.actions.detail` })}
            </Button>
          )}
          {capabilities.canUpdate && (
            <Button
              type="link"
              onClick={() => {
                setEditorRecord(record);
                setFormError(undefined);
                setEditorOpen(true);
              }}
            >
              {intl.formatMessage({ id: `${localePrefix}.actions.edit` })}
            </Button>
          )}
          {capabilities.canDelete && (
            <Popconfirm
              title={intl.formatMessage({ id: `${localePrefix}.actions.confirmDelete` })}
              onConfirm={async () => {
                try {
                  await deleteSupplier(record.id, { skipErrorHandler: true });
                  message.success(
                    intl.formatMessage({ id: `${localePrefix}.messages.deleteSuccess` }),
                  );
                  actionRef.current?.reload();
                } catch {
                  message.error(intl.formatMessage({ id: `${localePrefix}.errors.request` }));
                }
              }}
            >
              <Button type="link" danger>
                {intl.formatMessage({ id: `${localePrefix}.actions.delete` })}
              </Button>
            </Popconfirm>
          )}
        </Space>
      ),
    },
  ];

  const detailColumns: ProDescriptionsItemProps<Supplier>[] = [
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.id` }),
      dataIndex: 'id',
      copyable: true,
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.code` }),
      dataIndex: 'code',
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.name` }),
      dataIndex: 'name',
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.country` }),
      dataIndex: 'country',
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.contactName` }),
      dataIndex: 'contactName',
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.contactEmail` }),
      dataIndex: 'contactEmail',
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.creditLevel` }),
      dataIndex: 'creditLevel',
      render: (_, record) => {
        const option = creditLevelOptions.find((item) => item.value === record.creditLevel);
        return option ? <Tag color={option.color}>{option.label}</Tag> : record.creditLevel;
      },
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.enabled` }),
      dataIndex: 'enabled',
      render: (_, record) =>
        intl.formatMessage({
          id: `${localePrefix}.values.${record.enabled ? 'enabled' : 'disabled'}`,
        }),
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.createdAt` }),
      dataIndex: 'createdAt',
      valueType: 'dateTime',
    },
    {
      title: intl.formatMessage({ id: `${localePrefix}.fields.updatedAt` }),
      dataIndex: 'updatedAt',
      valueType: 'dateTime',
    },
  ];

  const createDefaults: Partial<CreateSupplierInput> = {
    creditLevel: "normal",
    enabled: true,
  };

  return (
    <PageContainer title={title}>
      <ProTable<Supplier>
        rowKey="id"
        headerTitle={intl.formatMessage({ id: `${localePrefix}.list.title` })}
        actionRef={actionRef}
        columns={columns}
        scroll={ { x: 'max-content' } }
        locale={ { emptyText: intl.formatMessage({ id: `${localePrefix}.states.empty` }) } }
        request={async (params, sorter) => {
          const query = buildSupplierQuery(params, sorter);
          setCurrentQuery(query);
          try {
            const result = await listSupplier(query, { skipErrorHandler: true });
            return { data: result.data, total: result.total, success: true };
          } catch {
            setPageError(true);
            return { data: [], total: 0, success: false };
          }
        }}
        toolBarRender={() => [
          capabilities.canCreate ? (
            <Button
              key="create"
              type="primary"
              icon={<PlusOutlined />}
              onClick={() => {
                setEditorRecord(undefined);
                setFormError(undefined);
                setEditorOpen(true);
              }}
            >
              {intl.formatMessage({ id: `${localePrefix}.actions.create` })}
            </Button>
          ) : null,
          capabilities.canExport ? (
            <Button
              key="export"
              icon={<DownloadOutlined />}
              onClick={async () => {
                try {
                  const blob = await exportSupplier(currentQuery, {
                    skipErrorHandler: true,
                  });
                  const url = URL.createObjectURL(blob);
                  const anchor = document.createElement('a');
                  anchor.href = url;
                  anchor.download = 'supplier.csv';
                  anchor.click();
                  URL.revokeObjectURL(url);
                  message.success(
                    intl.formatMessage({ id: `${localePrefix}.messages.exportSuccess` }),
                  );
                } catch {
                  message.error(intl.formatMessage({ id: `${localePrefix}.errors.request` }));
                }
              }}
            >
              {intl.formatMessage({ id: `${localePrefix}.actions.export` })}
            </Button>
          ) : null,
        ].filter(Boolean) as React.ReactNode[]}
      />

      <ModalForm<CreateSupplierInput>
        key={editorRecord?.id || 'create'}
        title={intl.formatMessage({
          id: `${localePrefix}.actions.${editorRecord ? 'edit' : 'create'}`,
        })}
        open={editorOpen}
        width={screens.md ? 720 : 'calc(100vw - 32px)'}
        initialValues={editorRecord || createDefaults}
        modalProps={ { destroyOnClose: true } }
        onOpenChange={(open) => {
          setEditorOpen(open);
          if (!open) {
            setEditorRecord(undefined);
            setFormError(undefined);
          }
        }}
        onFinish={async (values) => {
          setFormError(undefined);
          try {
            if (editorRecord) {
              await updateSupplier(editorRecord.id, values, { skipErrorHandler: true });
            } else {
              await createSupplier(values, { skipErrorHandler: true });
            }
            message.success(intl.formatMessage({ id: `${localePrefix}.messages.saveSuccess` }));
            setEditorOpen(false);
            setEditorRecord(undefined);
            actionRef.current?.reload();
            return true;
          } catch (error) {
            const key =
              getSupplierRequestStatus(error) === 409 ? 'conflict' : 'request';
            setFormError(intl.formatMessage({ id: `${localePrefix}.errors.${key}` }));
            return false;
          }
        }}
      >
        {formError && <Alert type="error" showIcon message={formError} />}
        <ProFormText
          name="code"
          label={intl.formatMessage({ id: `${localePrefix}.fields.code` })}
          rules={[
            {
              required: true,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.code.required`,
              }),
            },
            {
              min: 2,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.code.minLength`,
              }),
            },
            {
              max: 64,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.code.maxLength`,
              }),
            },
            {
              pattern: new RegExp("^[A-Z0-9_-]+$"),
              message: intl.formatMessage({
                id: `${localePrefix}.validation.code.pattern`,
              }),
            },
          ]}
        />
        <ProFormText
          name="name"
          label={intl.formatMessage({ id: `${localePrefix}.fields.name` })}
          rules={[
            {
              required: true,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.name.required`,
              }),
            },
            {
              min: 2,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.name.minLength`,
              }),
            },
            {
              max: 200,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.name.maxLength`,
              }),
            },
          ]}
        />
        <ProFormText
          name="country"
          label={intl.formatMessage({ id: `${localePrefix}.fields.country` })}
          rules={[
            {
              max: 100,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.country.maxLength`,
              }),
            },
          ]}
        />
        <ProFormText
          name="contactName"
          label={intl.formatMessage({ id: `${localePrefix}.fields.contactName` })}
          rules={[
            {
              required: true,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.contactName.required`,
              }),
            },
            {
              max: 100,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.contactName.maxLength`,
              }),
            },
          ]}
        />
        <ProFormText
          name="contactEmail"
          label={intl.formatMessage({ id: `${localePrefix}.fields.contactEmail` })}
          rules={[
            {
              max: 254,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.contactEmail.maxLength`,
              }),
            },
            {
              type: 'email',
              message: intl.formatMessage({
                id: `${localePrefix}.validation.contactEmail.email`,
              }),
            },
          ]}
        />
        <ProFormSelect
          name="creditLevel"
          label={intl.formatMessage({ id: `${localePrefix}.fields.creditLevel` })}
          options={ creditLevelOptions }
          rules={[
            {
              required: true,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.creditLevel.required`,
              }),
            },
          ]}
        />
        <ProFormSwitch
          name="enabled"
          label={intl.formatMessage({ id: `${localePrefix}.fields.enabled` })}
          rules={[
            {
              required: true,
              message: intl.formatMessage({
                id: `${localePrefix}.validation.enabled.required`,
              }),
            },
          ]}
        />
      </ModalForm>

      <Drawer
        title={intl.formatMessage({ id: `${localePrefix}.actions.detail` })}
        open={detailOpen}
        width={screens.md ? 560 : '100%'}
        onClose={() => setDetailOpen(false)}
      >
        {detailLoading ? (
          <Space direction="vertical" align="center" style={ { width: '100%' } }>
            <Spin />
            <span>{intl.formatMessage({ id: `${localePrefix}.states.detailLoading` })}</span>
          </Space>
        ) : detailError ? (
          <Alert type="error" showIcon message={detailError} />
        ) : detailRecord ? (
          <ProDescriptions<Supplier>
            column={1}
            dataSource={detailRecord}
            columns={detailColumns}
          />
        ) : (
          <Empty description={intl.formatMessage({ id: `${localePrefix}.states.empty` })} />
        )}
      </Drawer>
    </PageContainer>
  );
};

export default SupplierPage;
