// Code generated by mss module template 1.1.0-frontend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

import { request } from '@umijs/max';

import type {
  CreateSupplierInput,
  Supplier,
  SupplierPage,
  SupplierQuery,
  UpdateSupplierInput,
} from './types';

type RequestOptions = Record<string, unknown>;

const resourcePath = '/admin/api/suppliers';
export async function listSupplier(
  params: SupplierQuery,
  options?: RequestOptions,
) {
  return request<SupplierPage>(resourcePath, {
    method: 'GET',
    params,
    ...(options || {}),
  });
}
export async function getSupplier(id: string, options?: RequestOptions) {
  return request<Supplier>(`${resourcePath}/${encodeURIComponent(id)}`, {
    method: 'GET',
    ...(options || {}),
  });
}
export async function createSupplier(
  body: CreateSupplierInput,
  options?: RequestOptions,
) {
  return request<Supplier>(resourcePath, {
    method: 'POST',
    data: body,
    ...(options || {}),
  });
}
export async function updateSupplier(
  id: string,
  body: UpdateSupplierInput,
  options?: RequestOptions,
) {
  return request<Supplier>(`${resourcePath}/${encodeURIComponent(id)}`, {
    method: 'PUT',
    data: body,
    ...(options || {}),
  });
}
export async function deleteSupplier(id: string, options?: RequestOptions) {
  return request<void>(`${resourcePath}/${encodeURIComponent(id)}`, {
    method: 'DELETE',
    ...(options || {}),
  });
}
export async function exportSupplier(
  params: SupplierQuery,
  options?: RequestOptions,
) {
  return request<Blob>(`${resourcePath}/export`, {
    method: 'GET',
    params,
    responseType: 'blob',
    ...(options || {}),
  });
}
