// Code generated by mss module template 1.1.0-frontend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

export type Supplier = {
  id: string;
  code: string;
  name: string;
  country: string;
  contactName: string;
  contactEmail: string;
  creditLevel: string;
  enabled: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type CreateSupplierInput = {
  code: string;
  name: string;
  country?: string;
  contactName: string;
  contactEmail?: string;
  creditLevel: string;
  enabled: boolean;
};

export type UpdateSupplierInput = Partial<CreateSupplierInput>;

export type SupplierQuery = {
  current?: number;
  pageSize?: number;
  q?: string;
  country?: string;
  creditLevel?: string;
  enabled?: boolean;
  sortBy?: 'code' | 'name';
  sortOrder?: 'asc' | 'desc';
};

export type SupplierPage = {
  data: Supplier[];
  total: number;
  current: number;
  pageSize: number;
};

export type SupplierTableParams = Record<string, unknown> & {
  current?: number;
  pageSize?: number;
};

export type SupplierTableSorter = Record<
  string,
  'ascend' | 'descend' | null | undefined
>;
