package generator

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/mss-boot-io/mss-boot-admin/internal/mss/buildinfo"
	"github.com/mss-boot-io/mss-boot-admin/internal/mss/project"
	"github.com/mss-boot-io/mss-boot-admin/internal/mss/spec"
	foundationtemplates "github.com/mss-boot-io/mss-boot-admin/templates"
)

const (
	generatedMarker              = "Code generated by mss"
	moduleTemplateRevision       = "1.3.0-fullstack.1"
	backendTemplateRevision      = "1.3.0-backend.1"
	instructionsTemplateRevision = "1.3.0-module-instructions.1"
	frontendV6TemplateRevision   = "1.3.0-frontend-v6.1"
	docsTemplateRevision         = "1.3.0-docs.1"
	e2eV6TemplateRevision        = "1.3.0-e2e-v6.2"
)

// Action describes how one output differs from the workspace.
type Action string

const (
	ActionCreate    Action = "create"
	ActionDelete    Action = "delete"
	ActionUpdate    Action = "update"
	ActionUnchanged Action = "unchanged"
)

// Options control generation. Dry-run is the default when Write is false.
type Options struct {
	Root           string
	Write          bool
	Check          bool
	FrontendTarget string
	Project        *project.ProjectDocument
}

// Change is one deterministic output decision.
type Change struct {
	Path     string `json:"path"`
	Action   Action `json:"action"`
	Managed  bool   `json:"managed"`
	Bytes    int    `json:"bytes"`
	SHA256   string `json:"sha256"`
	Source   string `json:"source,omitempty"`
	content  []byte
	fileMode os.FileMode
}

// Plan is safe to render for humans or agents before applying writes.
type Plan struct {
	Module           string       `json:"module"`
	GeneratedAt      time.Time    `json:"generatedAt"`
	DryRun           bool         `json:"dryRun"`
	Check            bool         `json:"check"`
	Phase            string       `json:"phase"`
	GeneratorVersion string       `json:"generatorVersion"`
	GeneratorCommit  string       `json:"generatorCommit,omitempty"`
	TemplateRevision string       `json:"templateRevision"`
	FrontendTarget   string       `json:"frontendTarget,omitempty"`
	LayoutKind       string       `json:"layoutKind"`
	Complete         bool         `json:"complete"`
	Projections      []Projection `json:"projections"`
	Changes          []Change     `json:"changes"`
}

// DriftError is returned by --check when generated output is missing or stale.
type DriftError struct {
	Paths []string
}

func (e *DriftError) Error() string {
	return "generated module output is stale: " + strings.Join(e.Paths, ", ")
}

// JSON returns stable indented JSON.
func (p Plan) JSON() ([]byte, error) {
	return json.MarshalIndent(p, "", "  ")
}

// Text returns a compact generation summary.
func (p Plan) Text() string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "mss module generate: %s\n", p.Module)
	fmt.Fprintf(&builder, "dry-run: %t\n", p.DryRun)
	fmt.Fprintf(&builder, "check: %t\n\n", p.Check)
	fmt.Fprintf(&builder, "phase: %s\n", p.Phase)
	fmt.Fprintf(&builder, "generator version: %s\n", p.GeneratorVersion)
	if p.GeneratorCommit != "" {
		fmt.Fprintf(&builder, "generator commit: %s\n", p.GeneratorCommit)
	}
	fmt.Fprintf(&builder, "template revision: %s\n", p.TemplateRevision)
	if p.FrontendTarget != "" {
		fmt.Fprintf(&builder, "frontend target: %s\n", p.FrontendTarget)
	}
	fmt.Fprintf(&builder, "project layout: %s\n", p.LayoutKind)
	fmt.Fprintf(&builder, "complete: %t\n", p.Complete)
	deferred := 0
	for _, projection := range p.Projections {
		if projection.Status == ProjectionDeferred {
			deferred++
		}
	}
	fmt.Fprintf(&builder, "deferred projections: %d\n\n", deferred)
	for _, change := range p.Changes {
		fmt.Fprintf(&builder, "%-9s %s (%d bytes, %s)\n", change.Action, change.Path, change.Bytes, change.SHA256[:12])
	}
	return builder.String()
}

// Generate renders one validated module and optionally writes the plan atomically.
func Generate(module *spec.Module, options Options) (Plan, error) {
	if module == nil {
		return Plan{}, errors.New("module specification is nil")
	}
	if options.Root == "" {
		return Plan{}, errors.New("repository root is required")
	}
	layout, err := resolveTargetLayout(options.Project)
	if err != nil {
		return Plan{}, fmt.Errorf("resolve target project layout: %w", err)
	}
	frontendTarget := strings.TrimSpace(options.FrontendTarget)
	if frontendTarget == "" {
		frontendTarget = spec.FrontendTargetAntDV6
	}
	if frontendTarget != spec.FrontendTargetAntDV6 {
		return Plan{}, fmt.Errorf("unsupported frontend target %q: use %s", frontendTarget, spec.FrontendTargetAntDV6)
	}
	repository, err := os.OpenRoot(options.Root)
	if err != nil {
		return Plan{}, fmt.Errorf("open repository root: %w", err)
	}
	defer repository.Close()
	if issues := module.Validate(); len(issues) > 0 {
		return Plan{}, &spec.ValidationError{Issues: issues}
	}
	plan := Plan{
		Module:           module.Metadata.Name,
		GeneratedAt:      time.Now().UTC(),
		DryRun:           !options.Write,
		Check:            options.Check,
		Phase:            "generated-module-checkpoint",
		GeneratorVersion: buildinfo.VersionString(),
		GeneratorCommit:  buildinfo.CommitString(),
		TemplateRevision: moduleTemplateRevision,
		FrontendTarget:   frontendTarget,
		LayoutKind:       layout.Kind,
		Changes:          make([]Change, 0),
	}
	projections, projectionErr := buildProjectionReport(module)
	plan.Projections = projections
	plan.Complete = true
	for _, projection := range projections {
		if projection.Status == ProjectionDeferred || projection.Status == ProjectionUnsupported {
			plan.Complete = false
		}
	}
	if projectionErr != nil {
		return plan, projectionErr
	}
	if module.Spec.Generation.Frontend != nil && *module.Spec.Generation.Frontend && !module.SupportsFrontendTarget(frontendTarget) {
		return plan, fmt.Errorf("module %s does not declare frontend target %s", module.Metadata.Name, frontendTarget)
	}
	canonicalSource, err := canonicalModuleSourcePath(repository, options.Root, module.SourcePath)
	if err != nil {
		return plan, err
	}
	canonicalModule := *module
	canonicalModule.SourcePath = canonicalSource
	module = &canonicalModule
	if err := validateMigrationIDUniqueness(repository, module, layout); err != nil {
		return plan, err
	}

	data, err := buildTemplateData(module)
	if err != nil {
		return plan, err
	}
	data.TargetModule = layout.TargetModule
	data.AdminModule = layout.AdminModule
	data.FrameworkModule = layout.FrameworkModule
	data.AdminWebPackage = layout.AdminWebPackage
	data.ModuleDirectory = filepath.ToSlash(filepath.Join(layout.ModulesDir, module.Metadata.Name))
	data.BackendDirectory = layout.BackendDir
	backendRelativeModule, relativeErr := filepath.Rel(filepath.FromSlash(layout.BackendDir), filepath.FromSlash(data.ModuleDirectory))
	if relativeErr != nil {
		return plan, fmt.Errorf("resolve backend-relative module directory: %w", relativeErr)
	}
	data.BackendRelativeModuleDirectory = filepath.ToSlash(backendRelativeModule)
	data.FrontendDirectory = layout.FrontendDir
	data.GeneratedDirectory = layout.GeneratedDir
	data.BusinessRoutesFile = layout.BusinessRoutesFile
	data.DocumentationModulesDirectory = layout.DocumentationModulesDir
	if layout.Kind == layoutThinHost {
		data.MSSCommand = "mss --root ."
	} else {
		data.MSSCommand = "go run ./cmd/mss"
	}
	outputs, err := renderModuleOutputs(repository, module, data, frontendTarget, layout)
	if err != nil {
		return plan, err
	}
	registryOutputs, err := renderRegistryOutputs(repository, module, frontendTarget, layout)
	if err != nil {
		return plan, err
	}
	outputs = append(outputs, registryOutputs...)

	plan.Changes = make([]Change, 0, len(outputs))

	for _, output := range outputs {
		change, err := compareOutput(repository, output)
		if err != nil {
			return plan, err
		}
		plan.Changes = append(plan.Changes, change)
	}
	for _, obsoletePath := range obsoleteModuleOutputPaths(module, frontendTarget, layout) {
		change, exists, err := compareObsoleteOutput(repository, obsoletePath)
		if err != nil {
			return plan, err
		}
		if exists {
			plan.Changes = append(plan.Changes, change)
		}
	}
	sort.SliceStable(plan.Changes, func(i, j int) bool {
		return plan.Changes[i].Path < plan.Changes[j].Path
	})

	if options.Check {
		var stale []string
		for _, change := range plan.Changes {
			if change.Action != ActionUnchanged {
				stale = append(stale, change.Path)
			}
		}
		if len(stale) > 0 {
			return plan, &DriftError{Paths: stale}
		}
		return plan, nil
	}

	if options.Write {
		for _, change := range plan.Changes {
			if change.Action == ActionUnchanged {
				continue
			}
			if err := writeAtomic(repository, change); err != nil {
				return plan, err
			}
		}
	}
	return plan, nil
}

type output struct {
	path     string
	content  []byte
	managed  bool
	source   string
	fileMode os.FileMode
}

type templateData struct {
	SourceSpec                     string
	TemplateRevision               string
	FrontendTemplateRevision       string
	DocsTemplateRevision           string
	E2ETemplateRevision            string
	InstructionsTemplateRevision   string
	TargetModule                   string
	AdminModule                    string
	FrameworkModule                string
	AdminWebPackage                string
	ModuleDirectory                string
	BackendDirectory               string
	BackendRelativeModuleDirectory string
	FrontendDirectory              string
	GeneratedDirectory             string
	BusinessRoutesFile             string
	DocumentationModulesDirectory  string
	MSSCommand                     string
	ModuleName                     string
	EnvPrefix                      string
	Package                        string
	ModelName                      string
	DisplayName                    string
	Description                    string
	Table                          string
	MigrationID                    string
	AuthorizationMigrationID       string
	APIVersion                     string
	APIBasePath                    string
	FullAPIPath                    string
	APIResource                    string
	NeedsTime                      bool
	HasTextFields                  bool
	NeedsRegexp                    bool
	NeedsEmail                     bool
	Fields                         []fieldData
	SearchFields                   []fieldData
	FilterFields                   []fieldData
	SortFields                     []fieldData
	ListFields                     []fieldData
	Indexes                        []indexData
	UniqueGroups                   []uniqueGroupData
	Checks                         []checkData
	MigrationColumns               []migrationColumnData
	CreateTableSQLite              string
	CreateTablePostgres            string
	CreateTableMySQL               string
	Operations                     []operationData
	HasList                        bool
	HasGet                         bool
	HasCreate                      bool
	HasUpdate                      bool
	HasDelete                      bool
	HasExport                      bool
	HasUniqueFields                bool
	UniqueField                    fieldData
	HasMutableUnique               bool
	MutableUniqueField             fieldData
	HasUpdateField                 bool
	UpdateField                    fieldData
	HasE2EUpdateField              bool
	E2EUpdateField                 fieldData
	HasV6E2EUpdateField            bool
	V6E2EUpdateField               fieldData
	HasE2EMarkerField              bool
	E2EMarkerField                 fieldData
	HasSearchField                 bool
	SearchField                    fieldData
	PrimarySortName                string
	Events                         []eventData
	CreatedEventName               string
	UpdatedEventName               string
	HasCreatedEvent                bool
	HasUpdatedEvent                bool
	Permissions                    []permissionData
	DefaultRoles                   []string
	MenuPermissionCode             string
	MenuDefaultRoles               []string
	AuthorizationMatrix            []authorizationMatrixData
	AdminBypass                    bool
	Menu                           menuData
	UIList                         bool
	UIForm                         bool
	UIDetail                       bool
	UIMobile                       bool
	UIExport                       bool
	HasFormText                    bool
	HasFormSelect                  bool
	HasFormSwitch                  bool
	HasFrontendV6                  bool
	PermissionListPath             string
	PermissionReadPath             string
	PermissionCreatePath           string
	PermissionUpdatePath           string
	PermissionDeletePath           string
	PermissionExportPath           string
}

// ConflictError prevents the generator from replacing a user-owned file at a
// managed output path. All conflicts are detected before the first write.
type ConflictError struct {
	Path string
}

func (e *ConflictError) Error() string {
	return "generated output conflicts with user-owned file: " + e.Path
}

// MigrationIDCollisionError prevents a module migration from sharing a
// persisted identity with another module or a file-based Admin migration.
// The check runs before output comparison or the first write.
type MigrationIDCollisionError struct {
	ID       string
	Existing string
	Current  string
}

func (e *MigrationIDCollisionError) Error() string {
	return fmt.Sprintf("migration ID %s collides between %s and %s", e.ID, e.Existing, e.Current)
}

type fieldData struct {
	JSONName           string
	Column             string
	GoName             string
	GoType             string
	SearchType         string
	GormTag            string
	SearchTag          string
	DisplayName        string
	DisplayNameEn      string
	SpecType           string
	Required           bool
	Immutable          bool
	Unique             bool
	Searchable         bool
	Sortable           bool
	Filterable         bool
	List               bool
	IsString           bool
	IsEnum             bool
	IsBool             bool
	HasDefault         bool
	DefaultGo          string
	HasMinLength       bool
	MinLength          int
	HasMaxLength       bool
	MaxLength          int
	PatternGo          string
	HasPattern         bool
	EmailFormat        bool
	EnumValues         []enumData
	FixtureGo          string
	AlternateFixtureGo string
	TSType             string
	TSOptional         bool
	Form               bool
	Detail             bool
	PrimarySearch      bool
	UIComponent        string
	UIWidth            string
	UIPlaceholder      string
	UIHelp             string
	DefaultTS          string
	PatternTS          string
}

type permissionData struct {
	Action        string
	Identifier    string
	Code          string
	DisplayName   string
	Description   string
	DefaultRoles  []string
	ComponentPath string
}

type enumData struct {
	Value   string
	GoValue string
	TSValue string
	Label   string
	LabelEn string
	Color   string
}

type indexData struct {
	Name        string
	Unique      bool
	Columns     []string
	SQLiteDDL   string
	PostgresDDL string
	MySQLDDL    string
}

type uniqueGroupData struct {
	Name   string
	Fields []fieldData
}

type checkData struct {
	Name           string
	Column         string
	Values         []string
	SQLiteClause   string
	PostgresClause string
	MySQLClause    string
}

type migrationColumnData struct {
	Name          string
	SQLiteTypes   string
	PostgresTypes string
	MySQLTypes    string
	Nullable      bool
	PrimaryKey    bool
	Length        int
	HasDefault    bool
	DefaultValue  string
}

type operationData struct {
	Name                    string
	HandlerName             string
	Method                  string
	RoutePath               string
	OpenAPIPath             string
	PolicyPath              string
	PermissionIdentifier    string
	PermissionCode          string
	PermissionDisplayName   string
	PermissionComponentPath string
	DefaultRoles            []string
}

type authorizationMatrixData struct {
	Role                 string
	Operation            string
	Method               string
	PolicyPath           string
	PermissionIdentifier string
	Allowed              bool
}

type eventData struct {
	Name     string
	NameGo   string
	When     string
	TypeName string
}

type menuData struct {
	Name                       string
	Path                       string
	DisplayName                string
	DisplayNameEn              string
	Icon                       string
	Parent                     string
	ParentName                 string
	ParentDisplayNameEnLiteral string
	Order                      int
	Hidden                     bool
}

func buildTemplateData(module *spec.Module) (templateData, error) {
	data := templateData{
		SourceSpec:                   filepath.ToSlash(module.SourcePath),
		TemplateRevision:             backendTemplateRevision,
		FrontendTemplateRevision:     frontendV6TemplateRevision,
		DocsTemplateRevision:         docsTemplateRevision,
		E2ETemplateRevision:          e2eV6TemplateRevision,
		InstructionsTemplateRevision: instructionsTemplateRevision,
		ModuleName:                   module.Metadata.Name,
		EnvPrefix:                    strings.ToUpper(spec.SnakeCase(module.Metadata.Name)),
		Package:                      strings.ReplaceAll(spec.SnakeCase(module.Metadata.Name), "-", "_"),
		ModelName:                    module.Spec.Entity.GoName,
		DisplayName:                  escapeGoContent(module.Metadata.DisplayName),
		Description:                  escapeGoContent(module.Metadata.Description),
		Table:                        module.Spec.Entity.Table,
		MigrationID:                  module.Spec.Generation.MigrationID,
		AuthorizationMigrationID:     module.Spec.Generation.AuthorizationMigrationID,
		APIVersion:                   module.Spec.API.Version,
		APIBasePath:                  module.Spec.API.BasePath,
		FullAPIPath:                  "/admin/api" + module.Spec.API.BasePath,
		APIResource:                  strings.TrimPrefix(module.Spec.API.BasePath, "/"),
		AdminBypass:                  module.Spec.Ownership.AdminBypass != nil && *module.Spec.Ownership.AdminBypass,
		UIList:                       module.Spec.UI.List,
		UIForm:                       module.Spec.UI.Form,
		UIDetail:                     module.Spec.UI.Detail,
		UIMobile:                     module.Spec.UI.Mobile != nil && *module.Spec.UI.Mobile,
		UIExport:                     module.Spec.UI.Export,
		HasFrontendV6:                module.SupportsFrontendTarget(spec.FrontendTargetAntDV6),
		Menu: menuData{
			Name:                       escapeGoContent(module.Metadata.Name),
			Path:                       escapeGoContent(module.Spec.Menu.Path),
			DisplayName:                escapeGoContent(module.Spec.Menu.DisplayName),
			DisplayNameEn:              escapeGoContent(module.Spec.Menu.DisplayNameEn),
			Icon:                       escapeGoContent(module.Spec.Menu.Icon),
			Parent:                     escapeGoContent(module.Spec.Menu.Parent),
			ParentName:                 escapeGoContent(menuNameFromPath(module.Spec.Menu.Parent)),
			ParentDisplayNameEnLiteral: jsLiteral(module.Spec.Menu.ParentDisplayNameEn),
			Order:                      module.Spec.Menu.Order,
			Hidden:                     module.Spec.Menu.Hidden,
		},
	}
	if data.SourceSpec == "" {
		data.SourceSpec = "module.yaml"
	}

	primarySearchAssigned := false
	for _, field := range module.Spec.Entity.Fields {
		mapped, err := mapField(module, field)
		if err != nil {
			return templateData{}, err
		}
		if field.Searchable && !field.UI.Hidden && !primarySearchAssigned {
			mapped.PrimarySearch = true
			primarySearchAssigned = true
		}
		data.Fields = append(data.Fields, mapped)
		if field.Type == "string" || field.Type == "enum" {
			data.HasTextFields = true
		}
		if field.Validation.Pattern != "" {
			data.NeedsRegexp = true
		}
		if field.Validation.Format == "email" {
			data.NeedsEmail = true
		}
		if field.Searchable {
			data.SearchFields = append(data.SearchFields, mapped)
		}
		if mapped.Form {
			switch field.UI.Component {
			case "select":
				data.HasFormSelect = true
			case "switch":
				data.HasFormSwitch = true
			default:
				data.HasFormText = true
			}
		}
		if field.Filterable {
			data.FilterFields = append(data.FilterFields, mapped)
		}
		if field.Sortable {
			data.SortFields = append(data.SortFields, mapped)
			if data.PrimarySortName == "" {
				data.PrimarySortName = field.Name
			}
		}
		if mapped.List {
			data.ListFields = append(data.ListFields, mapped)
		}
		if field.Unique {
			if !data.HasUniqueFields {
				data.UniqueField = mapped
			}
			if !field.Immutable && !data.HasMutableUnique {
				data.HasMutableUnique = true
				data.MutableUniqueField = mapped
			}
			data.HasUniqueFields = true
		}
		if !data.HasUpdateField && !field.Immutable && (field.Type == "string") && !field.Unique && field.Validation.Pattern == "" && field.Validation.Format == "" {
			data.HasUpdateField = true
			data.UpdateField = mapped
			data.HasE2EUpdateField = true
			data.E2EUpdateField = mapped
		} else if !data.HasE2EUpdateField && !field.Immutable && mapped.Form {
			data.HasE2EUpdateField = true
			data.E2EUpdateField = mapped
		}
		if !data.HasV6E2EUpdateField && !field.Immutable && mapped.Form && mapped.List && contains([]string{"string", "text"}, field.Type) {
			data.HasV6E2EUpdateField = true
			data.V6E2EUpdateField = mapped
		}
		if !data.HasE2EMarkerField && field.Unique && field.Searchable && mapped.Form && mapped.List && contains([]string{"string", "text"}, field.Type) {
			data.HasE2EMarkerField = true
			data.E2EMarkerField = mapped
		}
		if !data.HasSearchField && field.Searchable {
			data.HasSearchField = true
			data.SearchField = mapped
		}
	}
	defaultRoleSet := make(map[string]struct{})
	for _, permission := range module.Spec.Permissions {
		defaultRoles := append([]string(nil), permission.DefaultRoles...)
		data.Permissions = append(data.Permissions, permissionData{
			Action:        permission.Action,
			Identifier:    spec.PascalCase(permission.Action),
			Code:          escapeGoContent(module.PermissionCode(permission.Action)),
			DisplayName:   escapeGoContent(permission.DisplayName),
			Description:   escapeGoContent(permission.Description),
			DefaultRoles:  defaultRoles,
			ComponentPath: strings.TrimSuffix(module.Spec.Menu.Path, "/") + "/permissions/" + permission.Action,
		})
		componentPath := strings.TrimSuffix(module.Spec.Menu.Path, "/") + "/permissions/" + permission.Action
		switch permission.Action {
		case "list":
			data.PermissionListPath = componentPath
		case "read":
			data.PermissionReadPath = componentPath
		case "create":
			data.PermissionCreatePath = componentPath
		case "update":
			data.PermissionUpdatePath = componentPath
		case "delete":
			data.PermissionDeletePath = componentPath
		case "export":
			data.PermissionExportPath = componentPath
		}
		for _, role := range defaultRoles {
			defaultRoleSet[role] = struct{}{}
		}
	}
	for role := range defaultRoleSet {
		data.DefaultRoles = append(data.DefaultRoles, role)
	}
	sort.Strings(data.DefaultRoles)
	if permission, ok := module.Permission("list"); ok {
		data.MenuPermissionCode = module.PermissionCode(permission.Action)
		data.MenuDefaultRoles = append([]string(nil), permission.DefaultRoles...)
	} else if permission, ok := module.Permission("read"); ok {
		data.MenuPermissionCode = module.PermissionCode(permission.Action)
		data.MenuDefaultRoles = append([]string(nil), permission.DefaultRoles...)
	} else if len(module.Spec.Permissions) > 0 {
		data.MenuPermissionCode = module.PermissionCode(module.Spec.Permissions[0].Action)
		data.MenuDefaultRoles = append([]string(nil), module.Spec.Permissions[0].DefaultRoles...)
	}
	data.Operations = buildOperations(module)
	for _, role := range data.DefaultRoles {
		for _, operation := range data.Operations {
			data.AuthorizationMatrix = append(data.AuthorizationMatrix, authorizationMatrixData{
				Role:                 role,
				Operation:            operation.Name,
				Method:               operation.Method,
				PolicyPath:           operation.PolicyPath,
				PermissionIdentifier: operation.PermissionIdentifier,
				Allowed:              contains(operation.DefaultRoles, role),
			})
		}
	}
	for _, operation := range data.Operations {
		switch operation.Name {
		case "list":
			data.HasList = true
		case "get":
			data.HasGet = true
		case "create":
			data.HasCreate = true
		case "update":
			data.HasUpdate = true
		case "delete":
			data.HasDelete = true
		case "export":
			data.HasExport = true
		}
	}
	for _, event := range module.Spec.Events {
		data.Events = append(data.Events, eventData{
			Name:     event.Name,
			NameGo:   strconv.Quote(event.Name),
			When:     event.When,
			TypeName: module.Spec.Entity.GoName + spec.PascalCase(event.When) + "Event",
		})
		if event.When == "created" {
			data.CreatedEventName = event.Name
			data.HasCreatedEvent = true
		}
		if event.When == "updated" {
			data.UpdatedEventName = event.Name
			data.HasUpdatedEvent = true
		}
	}
	data.Indexes = buildIndexData(module)
	data.UniqueGroups = buildUniqueGroupData(module, data.Fields)
	if len(data.UniqueGroups) > 0 {
		data.HasUniqueFields = true
	}
	for _, field := range module.Spec.Entity.Fields {
		if field.Type == "enum" {
			values := make([]string, 0, len(field.EnumValues))
			sqliteValues := make([]string, 0, len(field.EnumValues))
			postgresValues := make([]string, 0, len(field.EnumValues))
			mysqlValues := make([]string, 0, len(field.EnumValues))
			for _, value := range field.EnumValues {
				values = append(values, value.Value)
				sqliteValues = append(sqliteValues, sqlLiteral(value.Value, "sqlite"))
				postgresValues = append(postgresValues, sqlLiteral(value.Value, "postgres")+"::character varying")
				mysqlValues = append(mysqlValues, sqlLiteral(value.Value, "mysql"))
			}
			data.Checks = append(data.Checks, checkData{
				Name:           "ck_" + module.Spec.Entity.Table + "_" + field.Column,
				Column:         field.Column,
				Values:         values,
				SQLiteClause:   "CHECK (" + quoteSQLIdentifier(field.Column, "sqlite") + " IN (" + strings.Join(sqliteValues, ", ") + "))",
				PostgresClause: "CHECK (((" + quoteSQLIdentifier(field.Column, "postgres") + ")::text = ANY ((ARRAY[" + strings.Join(postgresValues, ", ") + "])::text[])))",
				MySQLClause:    "(" + quoteSQLIdentifier(field.Column, "mysql") + " IN (" + strings.Join(mysqlValues, ", ") + "))",
			})
		}
	}
	data.MigrationColumns = buildMigrationColumnData(module)
	data.CreateTableSQLite = buildCreateTableDDL(module, "sqlite")
	data.CreateTablePostgres = buildCreateTableDDL(module, "postgres")
	data.CreateTableMySQL = buildCreateTableDDL(module, "mysql")
	return data, nil
}

func buildMigrationColumnData(module *spec.Module) []migrationColumnData {
	columns := []migrationColumnData{
		{Name: "id", SQLiteTypes: "varchar", PostgresTypes: "varchar", MySQLTypes: "varchar", Nullable: false, PrimaryKey: true, Length: 64},
		{Name: "created_at", SQLiteTypes: "datetime", PostgresTypes: "timestamptz", MySQLTypes: "datetime", Nullable: false},
		{Name: "updated_at", SQLiteTypes: "datetime", PostgresTypes: "timestamptz", MySQLTypes: "datetime", Nullable: false},
		{Name: "deleted_at", SQLiteTypes: "datetime", PostgresTypes: "timestamptz", MySQLTypes: "datetime", Nullable: true},
	}
	for _, field := range module.Spec.Entity.Fields {
		column := migrationColumnData{
			Name:         field.Column,
			Nullable:     !field.Required || field.Nullable,
			HasDefault:   field.Default != nil,
			DefaultValue: fmt.Sprint(field.Default),
		}
		switch field.Type {
		case "bool":
			column.SQLiteTypes = "boolean|bool"
			column.PostgresTypes = "bool|boolean"
			column.MySQLTypes = "tinyint|boolean|bool"
		default:
			column.SQLiteTypes = "varchar"
			column.PostgresTypes = "varchar"
			column.MySQLTypes = "varchar"
			column.Length = 255
			if field.Validation.MaxLength != nil {
				column.Length = *field.Validation.MaxLength
			}
		}
		columns = append(columns, column)
	}
	return columns
}

func mapField(module *spec.Module, field spec.FieldSpec) (fieldData, error) {
	goType, searchType, tsType, err := fieldTypes(field)
	if err != nil {
		return fieldData{}, err
	}
	gormTag := buildGORMTag(module, field)
	searchKind := "exact"
	if field.Searchable && contains([]string{"string", "text"}, field.Type) {
		searchKind = "contains"
	}
	searchTag := "type:" + searchKind + ";column:" + field.Column
	return fieldData{
		JSONName:           field.Name,
		Column:             field.Column,
		GoName:             field.GoName,
		GoType:             goType,
		SearchType:         searchType,
		GormTag:            gormTag,
		SearchTag:          searchTag,
		DisplayName:        field.DisplayName,
		DisplayNameEn:      titleWords(field.Name),
		SpecType:           field.Type,
		Required:           field.Required,
		Immutable:          field.Immutable,
		Unique:             field.Unique,
		Searchable:         field.Searchable,
		Sortable:           field.Sortable,
		Filterable:         field.Filterable,
		List:               (field.List == nil || *field.List) && !field.UI.Hidden,
		IsString:           field.Type == "string",
		IsEnum:             field.Type == "enum",
		IsBool:             field.Type == "bool",
		HasDefault:         field.Default != nil,
		DefaultGo:          goLiteral(field.Default),
		HasMinLength:       field.Validation.MinLength != nil,
		MinLength:          intValue(field.Validation.MinLength),
		HasMaxLength:       field.Validation.MaxLength != nil,
		MaxLength:          intValue(field.Validation.MaxLength),
		PatternGo:          strconv.Quote(field.Validation.Pattern),
		HasPattern:         field.Validation.Pattern != "",
		EmailFormat:        field.Validation.Format == "email",
		EnumValues:         mapEnumValues(field.EnumValues),
		FixtureGo:          fixtureGo(field, false),
		AlternateFixtureGo: fixtureGo(field, true),
		TSType:             tsType,
		TSOptional:         !field.Required,
		Form:               (field.Form == nil || *field.Form) && !field.UI.Hidden,
		Detail:             (field.Detail == nil || *field.Detail) && !field.UI.Hidden,
		UIComponent:        field.UI.Component,
		UIWidth:            jsLiteral(field.UI.Width),
		UIPlaceholder:      quotedStringOrEmpty(field.UI.Placeholder),
		UIHelp:             quotedStringOrEmpty(field.UI.Help),
		DefaultTS:          jsLiteral(field.Default),
		PatternTS:          strconv.Quote(field.Validation.Pattern),
	}, nil
}

func fieldTypes(field spec.FieldSpec) (goType, searchType, tsType string, err error) {
	switch field.Type {
	case "string", "text", "enum", "uuid", "file", "files", "json", "relation":
		goType, searchType, tsType = "string", "string", "string"
	case "int":
		goType, searchType, tsType = "int", "int", "number"
	case "int64":
		goType, searchType, tsType = "int64", "int64", "number"
	case "uint":
		goType, searchType, tsType = "uint", "uint", "number"
	case "float64", "decimal":
		goType, searchType, tsType = "float64", "float64", "number"
	case "bool":
		goType, searchType, tsType = "bool", "bool", "boolean"
	case "date", "datetime":
		goType, searchType, tsType = "time.Time", "string", "string"
	default:
		return "", "", "", fmt.Errorf("unsupported field type %q", field.Type)
	}
	if field.Nullable {
		goType = "*" + goType
	}
	return goType, searchType, tsType, nil
}

func buildGORMTag(module *spec.Module, field spec.FieldSpec) string {
	parts := []string{"column:" + field.Column, "type:" + databaseType(field)}
	if field.Required && !field.Nullable {
		parts = append(parts, "not null")
	}
	if field.Unique {
		parts = append(parts, "uniqueIndex:ux_"+module.Spec.Entity.Table+"_"+field.Column)
	} else if field.Index {
		parts = append(parts, "index:idx_"+module.Spec.Entity.Table+"_"+field.Column)
	}
	for _, databaseIndex := range module.Spec.Entity.Indexes {
		for priority, fieldName := range databaseIndex.Fields {
			if fieldName != field.Name {
				continue
			}
			kind := "index:"
			if databaseIndex.Unique {
				kind = "uniqueIndex:"
			}
			parts = append(parts, kind+databaseIndex.Name+",priority:"+strconv.Itoa(priority+1))
		}
	}
	if field.Default != nil {
		parts = append(parts, "default:"+sanitizeTagValue(fmt.Sprint(field.Default)))
	}
	if field.DisplayName != "" {
		parts = append(parts, "comment:"+sanitizeTagValue(field.DisplayName))
	}
	return strings.Join(parts, ";")
}

func buildOperations(module *spec.Module) []operationData {
	operations := make([]operationData, 0, len(module.Spec.API.Operations))
	for _, operation := range module.Spec.API.Operations {
		permission := operation
		method := ""
		routePath := ""
		openAPIPath := "/admin/api" + module.Spec.API.BasePath
		switch operation {
		case "list":
			method = "GET"
			permission = "list"
		case "get":
			method = "GET"
			permission = "read"
			routePath = "/:id"
			openAPIPath += "/{id}"
		case "create":
			method = "POST"
		case "update":
			method = "PUT"
			routePath = "/:id"
			openAPIPath += "/{id}"
		case "delete":
			method = "DELETE"
			routePath = "/:id"
			openAPIPath += "/{id}"
		case "export":
			method = "GET"
			routePath = "/export"
			openAPIPath += "/export"
		}
		permissionSpec, _ := module.Permission(permission)
		operations = append(operations, operationData{
			Name:                    operation,
			HandlerName:             spec.PascalCase(operation),
			Method:                  method,
			RoutePath:               routePath,
			OpenAPIPath:             openAPIPath,
			PolicyPath:              "/admin/api" + module.Spec.API.BasePath + routePath,
			PermissionIdentifier:    spec.PascalCase(permission),
			PermissionCode:          module.PermissionCode(permission),
			PermissionDisplayName:   permissionSpec.DisplayName,
			PermissionComponentPath: strings.TrimSuffix(module.Spec.Menu.Path, "/") + "/permissions/" + permission,
			DefaultRoles:            append([]string(nil), permissionSpec.DefaultRoles...),
		})
	}
	return operations
}

func buildIndexData(module *spec.Module) []indexData {
	type indexDefinition struct {
		name    string
		columns []string
		unique  bool
	}
	definitions := make([]indexDefinition, 0, len(module.Spec.Entity.Indexes)+len(module.Spec.Entity.Fields)+1)
	definitions = append(definitions, indexDefinition{
		name:    "idx_" + module.Spec.Entity.Table + "_deleted_at",
		columns: []string{"deleted_at"},
	})
	for _, field := range module.Spec.Entity.Fields {
		if field.Unique {
			definitions = append(definitions, indexDefinition{
				name:    "ux_" + module.Spec.Entity.Table + "_" + field.Column,
				columns: []string{field.Column},
				unique:  true,
			})
		} else if field.Index {
			definitions = append(definitions, indexDefinition{
				name:    "idx_" + module.Spec.Entity.Table + "_" + field.Column,
				columns: []string{field.Column},
			})
		}
	}
	for _, databaseIndex := range module.Spec.Entity.Indexes {
		columns := make([]string, 0, len(databaseIndex.Fields))
		for _, fieldName := range databaseIndex.Fields {
			field, _ := module.Field(fieldName)
			columns = append(columns, field.Column)
		}
		definitions = append(definitions, indexDefinition{
			name:    databaseIndex.Name,
			columns: columns,
			unique:  databaseIndex.Unique,
		})
	}
	sort.SliceStable(definitions, func(i, j int) bool { return definitions[i].name < definitions[j].name })
	indexes := make([]indexData, 0, len(definitions))
	for _, definition := range definitions {
		indexes = append(indexes, indexData{
			Name:        definition.name,
			Unique:      definition.unique,
			Columns:     append([]string(nil), definition.columns...),
			SQLiteDDL:   buildIndexDDL(module.Spec.Entity.Table, definition.name, definition.columns, definition.unique, "sqlite"),
			PostgresDDL: buildIndexDDL(module.Spec.Entity.Table, definition.name, definition.columns, definition.unique, "postgres"),
			MySQLDDL:    buildIndexDDL(module.Spec.Entity.Table, definition.name, definition.columns, definition.unique, "mysql"),
		})
	}
	return indexes
}

func buildUniqueGroupData(module *spec.Module, fields []fieldData) []uniqueGroupData {
	byName := make(map[string]fieldData, len(fields))
	for index, field := range module.Spec.Entity.Fields {
		byName[field.Name] = fields[index]
	}
	groups := make([]uniqueGroupData, 0)
	for _, field := range module.Spec.Entity.Fields {
		if field.Unique {
			groups = append(groups, uniqueGroupData{
				Name:   "ux_" + module.Spec.Entity.Table + "_" + field.Column,
				Fields: []fieldData{byName[field.Name]},
			})
		}
	}
	for _, databaseIndex := range module.Spec.Entity.Indexes {
		if !databaseIndex.Unique {
			continue
		}
		group := uniqueGroupData{Name: databaseIndex.Name}
		for _, fieldName := range databaseIndex.Fields {
			group.Fields = append(group.Fields, byName[fieldName])
		}
		groups = append(groups, group)
	}
	sort.SliceStable(groups, func(i, j int) bool { return groups[i].Name < groups[j].Name })
	return groups
}

func buildIndexDDL(table, name string, columns []string, unique bool, dialect string) string {
	quotedColumns := make([]string, 0, len(columns))
	for _, column := range columns {
		quotedColumns = append(quotedColumns, quoteSQLIdentifier(column, dialect))
	}
	uniqueText := ""
	if unique {
		uniqueText = "UNIQUE "
	}
	ifNotExists := " IF NOT EXISTS"
	if dialect == "mysql" {
		ifNotExists = ""
	}
	return "CREATE " + uniqueText + "INDEX" + ifNotExists + " " + quoteSQLIdentifier(name, dialect) +
		" ON " + quoteSQLIdentifier(table, dialect) + " (" + strings.Join(quotedColumns, ", ") + ")"
}

func buildCreateTableDDL(module *spec.Module, dialect string) string {
	columns := []string{
		quoteSQLIdentifier("id", dialect) + " " + ddlStringType(64, dialect) + " NOT NULL PRIMARY KEY",
		quoteSQLIdentifier("created_at", dialect) + " " + ddlTimestampType(dialect) + " NOT NULL",
		quoteSQLIdentifier("updated_at", dialect) + " " + ddlTimestampType(dialect) + " NOT NULL",
		quoteSQLIdentifier("deleted_at", dialect) + " " + ddlTimestampType(dialect) + " NULL",
	}
	constraints := make([]string, 0)
	for _, field := range module.Spec.Entity.Fields {
		definition := quoteSQLIdentifier(field.Column, dialect) + " "
		switch field.Type {
		case "bool":
			definition += "BOOLEAN"
		default:
			length := 255
			if field.Validation.MaxLength != nil {
				length = *field.Validation.MaxLength
			}
			definition += ddlStringType(length, dialect)
		}
		if field.Required && !field.Nullable {
			definition += " NOT NULL"
		}
		if field.Default != nil {
			definition += " DEFAULT " + sqlLiteral(field.Default, dialect)
		}
		columns = append(columns, definition)
		if field.Type == "enum" {
			values := make([]string, 0, len(field.EnumValues))
			for _, enumValue := range field.EnumValues {
				values = append(values, sqlLiteral(enumValue.Value, dialect))
			}
			constraints = append(constraints, "CONSTRAINT "+quoteSQLIdentifier("ck_"+module.Spec.Entity.Table+"_"+field.Column, dialect)+
				" CHECK ("+quoteSQLIdentifier(field.Column, dialect)+" IN ("+strings.Join(values, ", ")+"))")
		}
	}
	columns = append(columns, constraints...)
	statement := "CREATE TABLE IF NOT EXISTS " + quoteSQLIdentifier(module.Spec.Entity.Table, dialect) + " (\n  " +
		strings.Join(columns, ",\n  ") + "\n)"
	if dialect == "mysql" {
		statement += " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"
	}
	return statement
}

func quoteSQLIdentifier(value, dialect string) string {
	if dialect == "mysql" {
		return "`" + strings.ReplaceAll(value, "`", "``") + "`"
	}
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

func ddlStringType(length int, dialect string) string {
	value := fmt.Sprintf("VARCHAR(%d)", length)
	if dialect == "mysql" {
		value += " COLLATE utf8mb4_bin"
	}
	return value
}

func ddlTimestampType(dialect string) string {
	switch dialect {
	case "postgres":
		return "TIMESTAMPTZ"
	case "mysql":
		return "DATETIME(3)"
	default:
		return "DATETIME"
	}
}

func sqlLiteral(value any, dialect string) string {
	switch typed := value.(type) {
	case bool:
		if typed {
			if dialect == "sqlite" {
				return "1"
			}
			return "TRUE"
		}
		if dialect == "sqlite" {
			return "0"
		}
		return "FALSE"
	case string:
		return "'" + strings.ReplaceAll(typed, "'", "''") + "'"
	default:
		return fmt.Sprint(value)
	}
}

func goLiteral(value any) string {
	switch typed := value.(type) {
	case string:
		return strconv.Quote(typed)
	case bool:
		return strconv.FormatBool(typed)
	case nil:
		return ""
	default:
		return fmt.Sprint(value)
	}
}

func intValue(value *int) int {
	if value == nil {
		return 0
	}
	return *value
}

func mapEnumValues(values []spec.EnumValue) []enumData {
	result := make([]enumData, 0, len(values))
	for _, value := range values {
		result = append(result, enumData{
			Value:   value.Value,
			GoValue: strconv.Quote(value.Value),
			TSValue: strconv.Quote(value.Value),
			Label:   value.Label,
			LabelEn: value.LabelEn,
			Color:   value.Color,
		})
	}
	return result
}

func jsLiteral(value any) string {
	if value == nil {
		return ""
	}
	encoded, err := json.Marshal(value)
	if err != nil {
		return ""
	}
	return string(encoded)
}

func quotedStringOrEmpty(value string) string {
	if value == "" {
		return ""
	}
	return strconv.Quote(value)
}

func fixtureGo(field spec.FieldSpec, alternate bool) string {
	if field.Type == "bool" {
		if alternate {
			return "false"
		}
		return "true"
	}
	if field.Type == "enum" && len(field.EnumValues) > 0 {
		index := 0
		if alternate && len(field.EnumValues) > 1 {
			index = 1
		}
		return strconv.Quote(field.EnumValues[index].Value)
	}
	if field.Validation.Format == "email" {
		if alternate {
			return strconv.Quote("alternate@example.test")
		}
		return strconv.Quote("supplier@example.test")
	}
	candidates := []string{"VALUE_01", "value", "sample", "AA"}
	if alternate {
		candidates = []string{"VALUE_02", "value two", "alternate", "BB"}
	}
	minimum := 0
	if field.Validation.MinLength != nil {
		minimum = *field.Validation.MinLength
	}
	maximum := 0
	if field.Validation.MaxLength != nil {
		maximum = *field.Validation.MaxLength
	}
	var pattern *regexp.Regexp
	if field.Validation.Pattern != "" {
		pattern = regexp.MustCompile(field.Validation.Pattern)
	}
	for _, candidate := range candidates {
		for len([]rune(candidate)) < minimum {
			candidate += "A"
		}
		if maximum > 0 && len([]rune(candidate)) > maximum {
			candidate = string([]rune(candidate)[:maximum])
		}
		if pattern == nil || pattern.MatchString(candidate) {
			return strconv.Quote(candidate)
		}
	}
	return strconv.Quote(strings.Repeat("A", max(1, minimum)))
}

func databaseType(field spec.FieldSpec) string {
	maxLength := 255
	if field.Validation.MaxLength != nil {
		maxLength = *field.Validation.MaxLength
	}
	switch field.Type {
	case "string", "enum", "uuid", "file", "relation":
		return fmt.Sprintf("varchar(%d)", maxLength)
	case "text", "files":
		return "text"
	case "json":
		return "json"
	case "int":
		return "int"
	case "int64":
		return "bigint"
	case "uint":
		return "bigint unsigned"
	case "float64":
		return "double"
	case "decimal":
		precision, scale := 18, 2
		if field.Validation.Precision != nil {
			precision = *field.Validation.Precision
		}
		if field.Validation.Scale != nil {
			scale = *field.Validation.Scale
		}
		return fmt.Sprintf("decimal(%d,%d)", precision, scale)
	case "bool":
		return "boolean"
	case "date":
		return "date"
	case "datetime":
		return "datetime"
	default:
		return "text"
	}
}

func buildBindingTag(field spec.FieldSpec) string {
	var rules []string
	if field.Required {
		rules = append(rules, "required")
	}
	if field.Validation.Format == "email" {
		rules = append(rules, "email")
	}
	if field.Validation.MinLength != nil {
		rules = append(rules, "min="+strconv.Itoa(*field.Validation.MinLength))
	}
	if field.Validation.MaxLength != nil {
		rules = append(rules, "max="+strconv.Itoa(*field.Validation.MaxLength))
	}
	if field.Validation.Minimum != nil {
		rules = append(rules, "gte="+numberString(*field.Validation.Minimum))
	}
	if field.Validation.Maximum != nil {
		rules = append(rules, "lte="+numberString(*field.Validation.Maximum))
	}
	return strings.Join(rules, ",")
}

func renderModuleOutputs(repository *os.Root, module *spec.Module, data templateData, frontendTarget string, layout targetLayout) ([]output, error) {
	moduleDir := filepath.FromSlash(filepath.Join(layout.ModulesDir, module.Metadata.Name))
	mappings := []struct {
		template string
		path     string
	}{
		{"templates/module/backend/model.go.tmpl", filepath.Join(moduleDir, "model_generated.go")},
		{"templates/module/backend/dto.go.tmpl", filepath.Join(moduleDir, "dto_generated.go")},
		{"templates/module/backend/events.go.tmpl", filepath.Join(moduleDir, "events_generated.go")},
		{"templates/module/backend/service.go.tmpl", filepath.Join(moduleDir, "service_generated.go")},
		{"templates/module/backend/api.go.tmpl", filepath.Join(moduleDir, "api_generated.go")},
		{"templates/module/backend/authorization.go.tmpl", filepath.Join(moduleDir, "authorization_generated.go")},
		{"templates/module/backend/authorization_migration.go.tmpl", filepath.Join(moduleDir, "authorization_migration_generated.go")},
		{"templates/module/backend/migration.go.tmpl", filepath.Join(moduleDir, "migration_generated.go")},
		{"templates/module/backend/descriptor.go.tmpl", filepath.Join(moduleDir, "descriptor_generated.go")},
		{"templates/module/backend/module.go.tmpl", filepath.Join(moduleDir, "module_generated.go")},
		{"templates/module/backend/module_test.go.tmpl", filepath.Join(moduleDir, "module_generated_test.go")},
		{"templates/module/backend/service_test.go.tmpl", filepath.Join(moduleDir, "service_generated_test.go")},
		{"templates/module/backend/api_test.go.tmpl", filepath.Join(moduleDir, "api_generated_test.go")},
		{"templates/module/backend/authorization_test.go.tmpl", filepath.Join(moduleDir, "authorization_generated_test.go")},
		{"templates/module/backend/migration_test.go.tmpl", filepath.Join(moduleDir, "migration_generated_test.go")},
		{"templates/module/backend/authorization_migration_test.go.tmpl", filepath.Join(moduleDir, "authorization_migration_generated_test.go")},
		{"templates/module/backend/migration_provider_test.go.tmpl", filepath.Join(moduleDir, "migration_provider_generated_test.go")},
		{"templates/module/backend/AGENTS.md.tmpl", filepath.Join(moduleDir, "AGENTS.md")},
	}
	if module.Spec.Generation.Frontend != nil && *module.Spec.Generation.Frontend {
		data.FrontendTemplateRevision = frontendV6TemplateRevision
		data.E2ETemplateRevision = e2eV6TemplateRevision
		frontendDir := filepath.Join(filepath.FromSlash(layout.GeneratedDir), "modules", module.Metadata.Name)
		mappings = append(mappings,
			struct{ template, path string }{"templates/module/frontend-v6/types.ts.tmpl", filepath.Join(frontendDir, "types.ts")},
			struct{ template, path string }{"templates/module/frontend-v6/contract.ts.tmpl", filepath.Join(frontendDir, "contract.ts")},
			struct{ template, path string }{"templates/module/frontend-v6/api.ts.tmpl", filepath.Join(frontendDir, "api.ts")},
			struct{ template, path string }{"templates/module/frontend-v6/query.ts.tmpl", filepath.Join(frontendDir, "query.ts")},
			struct{ template, path string }{"templates/module/frontend-v6/page.tsx.tmpl", filepath.Join(frontendDir, module.Spec.Entity.GoName+"Page.tsx")},
			struct{ template, path string }{"templates/module/frontend-v6/contract.test.ts.tmpl", filepath.Join(frontendDir, "contract.test.ts")},
			struct{ template, path string }{"templates/module/frontend-v6/page-entry.tsx.tmpl", filepath.Join(filepath.FromSlash(layout.FrontendPagesDir), module.Spec.Entity.GoName, "index.tsx")},
		)
	}
	if module.Spec.Generation.Docs != nil && *module.Spec.Generation.Docs {
		if layout.DocumentationModulesDir == "" {
			return nil, errors.New("project layout does not define a documentation directory for generated module docs")
		}
		mappings = append(mappings, struct {
			template string
			path     string
		}{
			template: "templates/module/docs/module.md.tmpl",
			path:     filepath.Join(filepath.FromSlash(layout.DocumentationModulesDir), module.Metadata.Name+".md"),
		})
	}
	if module.Spec.Tests.E2E {
		mappings = append(mappings, struct {
			template string
			path     string
		}{
			template: "templates/module/frontend-v6/e2e.spec.ts.tmpl",
			path:     filepath.Join(filepath.FromSlash(layout.FrontendE2EDir), module.Metadata.Name+".spec.ts"),
		})
	}

	outputs := make([]output, 0, len(mappings)+4)
	for _, mapping := range mappings {
		content, err := renderTemplate(mapping.template, data)
		if err != nil {
			return nil, err
		}
		if strings.HasSuffix(mapping.path, ".go") {
			content, err = format.Source(content)
			if err != nil {
				return nil, fmt.Errorf("format generated Go file %s: %w", mapping.path, err)
			}
		}
		outputs = append(outputs, output{
			path:     filepath.ToSlash(mapping.path),
			content:  normalizeNewline(content),
			managed:  true,
			source:   filepath.ToSlash(mapping.template),
			fileMode: 0o644,
		})
	}

	normalizedSpec, err := module.YAML()
	if err != nil {
		return nil, fmt.Errorf("marshal normalized module spec: %w", err)
	}
	normalizedSpec = append([]byte("# Code generated by mss module template "+moduleTemplateRevision+" from "+filepath.ToSlash(module.SourcePath)+". DO NOT EDIT.\n"), normalizedSpec...)
	outputs = append(outputs, output{
		path:     filepath.ToSlash(filepath.Join(moduleDir, "module.yaml")),
		content:  normalizeNewline(normalizedSpec),
		managed:  true,
		source:   filepath.ToSlash(module.SourcePath),
		fileMode: 0o644,
	})

	customPath := filepath.ToSlash(filepath.Join(moduleDir, "custom.go"))
	if _, err := repository.Stat(filepath.FromSlash(customPath)); errors.Is(err, os.ErrNotExist) {
		custom := fmt.Sprintf("package %s\n\n// Add non-generated business rules and extension hooks in this file.\n", data.Package)
		formatted, formatErr := format.Source([]byte(custom))
		if formatErr != nil {
			return nil, formatErr
		}
		outputs = append(outputs, output{
			path:     customPath,
			content:  formatted,
			managed:  false,
			source:   "generator extension point",
			fileMode: 0o644,
		})
	}
	return outputs, nil
}

func obsoleteModuleOutputPaths(module *spec.Module, frontendTarget string, layout targetLayout) []string {
	moduleDir := filepath.Join(filepath.FromSlash(layout.ModulesDir), module.Metadata.Name)
	paths := []string{
		filepath.ToSlash(filepath.Join(moduleDir, "controller_generated.go")),
		filepath.ToSlash(filepath.Join(moduleDir, "search_generated.go")),
	}
	if module.Spec.Generation.Docs == nil || !*module.Spec.Generation.Docs {
		if layout.DocumentationModulesDir != "" {
			paths = append(paths, filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.DocumentationModulesDir), module.Metadata.Name+".md")))
		}
	}
	if !module.Spec.Tests.E2E {
		paths = append(paths, filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.FrontendE2EDir), module.Metadata.Name+".spec.ts")))
	}
	return paths
}

func renderRegistryOutputs(repository *os.Root, current *spec.Module, frontendTarget string, layout targetLayout) ([]output, error) {
	modules, err := discoverModules(repository, current, layout)
	if err != nil {
		return nil, err
	}

	var goRegistry strings.Builder
	goRegistry.WriteString("// Code generated by mss module template " + backendTemplateRevision + " sync. DO NOT EDIT.\n\n")
	goRegistry.WriteString("// Package all returns every enabled vertical module in stable generation order.\n")
	goRegistry.WriteString("package all\n")
	goRegistry.WriteString("\nimport (\n")
	fmt.Fprintf(&goRegistry, "\t%q\n", layout.AdminModule+"/business")
	for index, module := range modules {
		moduleImport, importErr := layout.moduleImportPath(module.Metadata.Name)
		if importErr != nil {
			return nil, importErr
		}
		fmt.Fprintf(
			&goRegistry,
			"\tmodule%d %q\n",
			index,
			moduleImport,
		)
	}
	goRegistry.WriteString(")\n\n")
	goRegistry.WriteString("// Modules returns a new slice so callers cannot mutate the generated registry.\n")
	goRegistry.WriteString("func Modules() []business.Module {\n")
	goRegistry.WriteString("\treturn []business.Module{\n")
	for index := range modules {
		fmt.Fprintf(&goRegistry, "\t\tmodule%d.Module(),\n", index)
	}
	goRegistry.WriteString("\t}\n")
	goRegistry.WriteString("}\n")
	formattedRegistry, err := format.Source([]byte(goRegistry.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated module registry: %w", err)
	}

	frontendRevision := frontendV6TemplateRevision
	var routes strings.Builder
	routes.WriteString("// Code generated by mss module template " + frontendRevision + " sync. DO NOT EDIT.\n\n")
	routes.WriteString("export default [\n")
	frontendModules := make([]*spec.Module, 0, len(modules))
	for _, module := range modules {
		if !module.SupportsFrontendTarget(frontendTarget) {
			continue
		}
		frontendModules = append(frontendModules, module)
	}
	sort.SliceStable(frontendModules, func(i, j int) bool {
		if frontendModules[i].Spec.Menu.Order == frontendModules[j].Spec.Menu.Order {
			return frontendModules[i].Spec.Menu.Path < frontendModules[j].Spec.Menu.Path
		}
		return frontendModules[i].Spec.Menu.Order < frontendModules[j].Spec.Menu.Order
	})
	for _, module := range frontendModules {
		routes.WriteString("  {\n")
		fmt.Fprintf(&routes, "    path: %s,\n", strconv.Quote(module.Spec.Menu.Path))
		fmt.Fprintf(&routes, "    name: %s,\n", strconv.Quote(module.Metadata.Name))
		if module.Spec.Menu.Icon != "" {
			fmt.Fprintf(&routes, "    icon: %s,\n", strconv.Quote(module.Spec.Menu.Icon))
		}
		fmt.Fprintf(&routes, "    component: %s,\n", strconv.Quote("./generated/"+module.Spec.Entity.GoName))
		routes.WriteString("    access: 'canAccessRoute',\n")
		fmt.Fprintf(&routes, "    permission: %s,\n", strconv.Quote(module.Spec.Menu.Path))
		if module.Spec.Menu.Hidden {
			routes.WriteString("    hideInMenu: true,\n")
		}
		routes.WriteString("  },\n")
	}
	routes.WriteString("];\n")

	zhCN := renderLocaleRegistry(frontendModules, "zh-CN", frontendRevision)
	enUS := renderLocaleRegistry(frontendModules, "en-US", frontendRevision)

	outputs := []output{
		{
			path:     filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), "all", "generated.go")),
			content:  normalizeNewline(formattedRegistry),
			managed:  true,
			source:   filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), "*", "module.yaml")),
			fileMode: 0o644,
		},
	}
	outputs = append(outputs,
		output{
			path:     layout.BusinessRoutesFile,
			content:  normalizeNewline([]byte(routes.String())),
			managed:  true,
			source:   filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), "*", "module.yaml")),
			fileMode: 0o644,
		},
		output{
			path:     filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.GeneratedDir), "locales", "zh-CN.ts")),
			content:  normalizeNewline(zhCN),
			managed:  true,
			source:   filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), "*", "module.yaml")),
			fileMode: 0o644,
		},
		output{
			path:     filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.GeneratedDir), "locales", "en-US.ts")),
			content:  normalizeNewline(enUS),
			managed:  true,
			source:   filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), "*", "module.yaml")),
			fileMode: 0o644,
		},
		output{
			path:     filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.GeneratedDir), "routes.ts")),
			content:  normalizeNewline(renderV6RouteRegistry(frontendModules)),
			managed:  true,
			source:   filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), "*", "module.yaml")),
			fileMode: 0o644,
		},
	)
	return outputs, nil
}

func renderV6RouteRegistry(modules []*spec.Module) []byte {
	var output strings.Builder
	output.WriteString("// Code generated by mss module template " + frontendV6TemplateRevision + " sync. DO NOT EDIT.\n\n")
	output.WriteString("export default [\n")
	for _, module := range modules {
		output.WriteString("  {\n")
		fmt.Fprintf(&output, "    path: %s,\n", strconv.Quote(module.Spec.Menu.Path))
		fmt.Fprintf(&output, "    serverPaths: [%s],\n", strconv.Quote(module.Spec.Menu.Path))
		fmt.Fprintf(&output, "    menuName: %s,\n", strconv.Quote(module.Metadata.Name))
		fmt.Fprintf(&output, "    permission: %s,\n", strconv.Quote(module.Spec.Menu.Path))
		output.WriteString("  },\n")
	}
	output.WriteString("] as const;\n")
	return []byte(output.String())
}

type localeEntry struct {
	key   string
	value string
}

func renderLocaleRegistry(modules []*spec.Module, locale, frontendRevision string) []byte {
	entries := make([]localeEntry, 0, len(modules)*32)
	for _, module := range modules {
		entries = append(entries, moduleLocaleEntries(module, locale)...)
	}
	sort.SliceStable(entries, func(i, j int) bool { return entries[i].key < entries[j].key })
	var output strings.Builder
	output.WriteString("// Code generated by mss module template " + frontendRevision + " sync. DO NOT EDIT.\n\n")
	output.WriteString("export default {\n")
	for _, entry := range entries {
		fmt.Fprintf(&output, "  %s: %s,\n", strconv.Quote(entry.key), strconv.Quote(entry.value))
	}
	output.WriteString("};\n")
	return []byte(output.String())
}

func moduleLocaleEntries(module *spec.Module, locale string) []localeEntry {
	prefix := "modules." + module.Metadata.Name + "."
	moduleName := module.Metadata.DisplayName
	if locale == "en-US" {
		moduleName = module.Spec.Menu.DisplayNameEn
		if moduleName == "" {
			moduleName = titleWords(module.Metadata.Name)
		}
	}
	localized := func(zh, en string) string {
		if locale == "en-US" {
			return en
		}
		return zh
	}
	entries := []localeEntry{
		{key: "menu." + module.Metadata.Name, value: moduleName},
		{key: prefix + "title", value: moduleName},
		{key: prefix + "description", value: localized(module.Metadata.Description, "Review and manage "+strings.ToLower(moduleName)+" records through an authorized server contract.")},
		{key: prefix + "list.title", value: localized(moduleName+"列表", moduleName+" list")},
		{key: prefix + "actions.label", value: localized("操作", "Actions")},
		{key: prefix + "actions.create", value: localized("新建", "Create")},
		{key: prefix + "actions.edit", value: localized("编辑", "Edit")},
		{key: prefix + "actions.detail", value: localized("详情", "Details")},
		{key: prefix + "actions.delete", value: localized("删除", "Delete")},
		{key: prefix + "actions.export", value: localized("导出", "Export")},
		{key: prefix + "actions.retry", value: localized("重试", "Retry")},
		{key: prefix + "actions.search", value: localized("查询", "Search")},
		{key: prefix + "actions.reset", value: localized("重置", "Reset")},
		{key: prefix + "actions.close", value: localized("关闭", "Close")},
		{key: prefix + "actions.confirmDelete", value: localized("确认删除这条记录？", "Delete this record?")},
		{key: prefix + "messages.saveSuccess", value: localized("保存成功", "Saved successfully")},
		{key: prefix + "messages.deleteSuccess", value: localized("删除成功", "Deleted successfully")},
		{key: prefix + "messages.exportSuccess", value: localized("导出已开始下载", "Export download started")},
		{key: prefix + "states.empty", value: localized("暂无"+moduleName+"数据", "No "+strings.ToLower(moduleName)+" data")},
		{key: prefix + "states.forbidden", value: localized("无权访问此页面", "You do not have permission to view this page")},
		{key: prefix + "states.error", value: localized("加载失败，请重试", "Loading failed. Please retry.")},
		{key: prefix + "states.refreshFailed", value: localized("刷新失败，仍显示最近一次成功加载的数据", "Refresh failed. The last successfully loaded data remains visible.")},
		{key: prefix + "states.notFound", value: localized("记录不存在或已删除", "The record does not exist or was deleted.")},
		{key: prefix + "states.detailLoading", value: localized("正在加载详情", "Loading details")},
		{key: prefix + "errors.conflict", value: localized("记录冲突，请刷新后重试", "The record conflicts with current data. Refresh and try again.")},
		{key: prefix + "errors.request", value: localized("操作失败，请重试", "The operation failed. Please retry.")},
		{key: prefix + "fields.id", value: "ID"},
		{key: prefix + "fields.createdAt", value: localized("创建时间", "Created at")},
		{key: prefix + "fields.updatedAt", value: localized("更新时间", "Updated at")},
		{key: prefix + "values.enabled", value: localized("启用", "Enabled")},
		{key: prefix + "values.disabled", value: localized("停用", "Disabled")},
		{key: prefix + "values.all", value: localized("全部", "All")},
	}
	if parentName := menuNameFromPath(module.Spec.Menu.Parent); parentName != "" {
		parentDisplayName := module.Spec.Menu.ParentDisplayName
		if locale == "en-US" {
			parentDisplayName = module.Spec.Menu.ParentDisplayNameEn
		}
		if parentDisplayName == "" {
			parentDisplayName = titleWords(strings.ReplaceAll(parentName, ".", " "))
		}
		entries = append(entries,
			localeEntry{key: "menu." + parentName, value: parentDisplayName},
			localeEntry{key: "menu." + parentName + "." + module.Metadata.Name, value: moduleName},
		)
	}
	for _, field := range module.Spec.Entity.Fields {
		label := field.DisplayName
		if locale == "en-US" {
			label = titleWords(field.Name)
		}
		entries = append(entries, localeEntry{key: prefix + "fields." + field.Name, value: label})
		if field.Required {
			entries = append(entries, localeEntry{key: prefix + "validation." + field.Name + ".required", value: localized(field.DisplayName+"为必填项", label+" is required")})
		}
		if field.Validation.MinLength != nil {
			entries = append(entries, localeEntry{key: prefix + "validation." + field.Name + ".minLength", value: localized(field.DisplayName+"长度不能少于"+strconv.Itoa(*field.Validation.MinLength)+"个字符", label+" must contain at least "+strconv.Itoa(*field.Validation.MinLength)+" characters")})
		}
		if field.Validation.MaxLength != nil {
			entries = append(entries, localeEntry{key: prefix + "validation." + field.Name + ".maxLength", value: localized(field.DisplayName+"长度不能超过"+strconv.Itoa(*field.Validation.MaxLength)+"个字符", label+" must contain no more than "+strconv.Itoa(*field.Validation.MaxLength)+" characters")})
		}
		if field.Validation.Pattern != "" {
			entries = append(entries, localeEntry{key: prefix + "validation." + field.Name + ".pattern", value: localized(field.DisplayName+"格式不正确", label+" has an invalid format")})
		}
		if field.Validation.Format == "email" {
			entries = append(entries, localeEntry{key: prefix + "validation." + field.Name + ".email", value: localized("请输入有效的邮箱地址", "Enter a valid email address")})
		}
		for _, enumValue := range field.EnumValues {
			enumLabel := enumValue.Label
			if locale == "en-US" {
				enumLabel = enumValue.LabelEn
				if enumLabel == "" {
					enumLabel = titleWords(enumValue.Value)
				}
			}
			entries = append(entries, localeEntry{key: prefix + "enums." + field.Name + "." + enumValue.Value, value: enumLabel})
		}
	}
	for _, permission := range module.Spec.Permissions {
		label := permission.DisplayName
		description := permission.Description
		if description == "" {
			description = label + "权限"
		}
		if locale == "en-US" {
			label = titleWords(permission.Action)
			description = label + " permission"
		}
		entries = append(entries, localeEntry{key: prefix + "permissions." + permission.Action + ".label", value: label})
		entries = append(entries, localeEntry{key: prefix + "permissions." + permission.Action + ".description", value: description})
	}
	return entries
}

func titleWords(value string) string {
	words := strings.Fields(strings.ReplaceAll(spec.SnakeCase(value), "_", " "))
	for index := range words {
		words[index] = strings.ToUpper(words[index][:1]) + words[index][1:]
	}
	return strings.Join(words, " ")
}

func menuNameFromPath(path string) string {
	return strings.ReplaceAll(strings.Trim(path, "/"), "/", ".")
}

func discoverModules(repository *os.Root, current *spec.Module, layout targetLayout) ([]*spec.Module, error) {
	byName := map[string]*spec.Module{current.Metadata.Name: current}
	generatedPattern := filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), "*", "module.yaml"))
	matches, err := fs.Glob(repository.FS(), generatedPattern)
	if err != nil {
		return nil, fmt.Errorf("discover module specs: %w", err)
	}
	currentGeneratedSpec := filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), current.Metadata.Name, "module.yaml"))
	for _, match := range matches {
		if filepath.ToSlash(match) == currentGeneratedSpec {
			continue
		}
		content, readErr := repository.ReadFile(filepath.FromSlash(match))
		if readErr != nil {
			return nil, fmt.Errorf("read generated module spec %s: %w", match, readErr)
		}
		module, loadErr := spec.ParseModule(content, match)
		if loadErr != nil {
			return nil, loadErr
		}
		byName[module.Metadata.Name] = module
	}
	modules := make([]*spec.Module, 0, len(byName))
	for _, module := range byName {
		modules = append(modules, module)
	}
	sort.SliceStable(modules, func(i, j int) bool {
		return modules[i].Metadata.Name < modules[j].Metadata.Name
	})
	return modules, nil
}

var (
	migrationFilenamePattern  = regexp.MustCompile(`^(?:0|[1-9][0-9]*)(?:_.*)?\.go$`)
	migrationLiteralIDPattern = regexp.MustCompile(`"((?:0|[1-9][0-9]*))"`)
)

func validateMigrationIDUniqueness(repository *os.Root, current *spec.Module, layout targetLayout) error {
	type owner struct {
		key  string
		path string
	}
	owners := make(map[string]owner)
	targetIDs := map[string]struct{}{
		current.Spec.Generation.MigrationID:              {},
		current.Spec.Generation.AuthorizationMigrationID: {},
	}
	register := func(id string, candidate owner) error {
		if id == "" {
			return nil
		}
		if _, targeted := targetIDs[id]; !targeted {
			return nil
		}
		if existing, ok := owners[id]; ok {
			if existing.key == candidate.key {
				return nil
			}
			return &MigrationIDCollisionError{ID: id, Existing: existing.path, Current: candidate.path}
		}
		owners[id] = candidate
		return nil
	}
	currentOwner := owner{key: "module:" + current.Metadata.Name, path: filepath.ToSlash(current.SourcePath)}
	if currentOwner.path == "" {
		currentOwner.path = "module:" + current.Metadata.Name
	}
	if err := register(current.Spec.Generation.MigrationID, currentOwner); err != nil {
		return err
	}
	if err := register(current.Spec.Generation.AuthorizationMigrationID, currentOwner); err != nil {
		return err
	}

	seenPaths := make(map[string]struct{})
	currentGeneratedSpec := filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), current.Metadata.Name, "module.yaml"))
	sourcePattern := filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.SpecificationsDir), "modules", "*.yaml"))
	generatedPattern := filepath.ToSlash(filepath.Join(filepath.FromSlash(layout.ModulesDir), "*", "module.yaml"))
	for _, pattern := range []string{sourcePattern, generatedPattern} {
		matches, err := fs.Glob(repository.FS(), pattern)
		if err != nil {
			return fmt.Errorf("discover migration IDs from %s: %w", pattern, err)
		}
		for _, match := range matches {
			// The generated module spec is replaced by this run. Skip its stale
			// pre-projection shape while still registering the validated source
			// module above as the owner of both migration identities.
			if filepath.ToSlash(match) == currentGeneratedSpec {
				continue
			}
			if _, seen := seenPaths[match]; seen {
				continue
			}
			seenPaths[match] = struct{}{}
			content, err := repository.ReadFile(filepath.FromSlash(match))
			if err != nil {
				return fmt.Errorf("read module migration identity %s: %w", match, err)
			}
			module, err := spec.ParseModule(content, match)
			if err != nil {
				return err
			}
			if err := register(module.Spec.Generation.MigrationID, owner{
				key:  "module:" + module.Metadata.Name,
				path: match,
			}); err != nil {
				return err
			}
			if err := register(module.Spec.Generation.AuthorizationMigrationID, owner{
				key:  "module:" + module.Metadata.Name,
				path: match,
			}); err != nil {
				return err
			}
		}
	}

	migrationRoot := layout.LegacyMigrationDir
	if migrationRoot == "" {
		return nil
	}
	if _, err := repository.Stat(filepath.FromSlash(migrationRoot)); errors.Is(err, os.ErrNotExist) {
		return nil
	} else if err != nil {
		return fmt.Errorf("inspect Admin migration root: %w", err)
	}
	return fs.WalkDir(repository.FS(), migrationRoot, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || strings.HasSuffix(entry.Name(), "_test.go") || filepath.Ext(entry.Name()) != ".go" {
			return nil
		}
		candidateOwner := owner{key: "migration:" + path, path: path}
		if migrationFilenamePattern.MatchString(entry.Name()) {
			id, _, _ := strings.Cut(strings.TrimSuffix(entry.Name(), filepath.Ext(entry.Name())), "_")
			if err := register(id, candidateOwner); err != nil {
				return err
			}
		}
		content, err := repository.ReadFile(filepath.FromSlash(path))
		if err != nil {
			return fmt.Errorf("read Admin migration identity %s: %w", path, err)
		}
		// Compatibility migrations may need to query the ledger identity owned by
		// one generated module without claiming that identity. The explicit,
		// module-scoped marker keeps that reference auditable and only suppresses
		// collision ownership while regenerating the named module.
		referenceMarker := []byte("mss:migration-reference " + current.Metadata.Name)
		for _, line := range bytes.Split(content, []byte("\n")) {
			if bytes.Contains(line, referenceMarker) {
				continue
			}
			for _, match := range migrationLiteralIDPattern.FindAllSubmatch(line, -1) {
				if err := register(string(match[1]), candidateOwner); err != nil {
					return err
				}
			}
		}
		return nil
	})
}

func renderLocales(modules []*spec.Module) (string, string) {
	var zhCN strings.Builder
	var enUS strings.Builder
	zhCN.WriteString("// Code generated by mss module sync. DO NOT EDIT.\n\nexport default {\n")
	enUS.WriteString("// Code generated by mss module sync. DO NOT EDIT.\n\nexport default {\n")
	for _, module := range modules {
		key := "menu." + module.Metadata.Name
		fmt.Fprintf(&zhCN, "  %s: %s,\n", tsQuote(key), tsQuote(module.Spec.Menu.DisplayName))
		englishName := module.Spec.Menu.DisplayNameEn
		if englishName == "" {
			englishName = module.Metadata.DisplayName
		}
		fmt.Fprintf(&enUS, "  %s: %s,\n", tsQuote(key), tsQuote(englishName))
		for _, field := range module.Spec.Entity.Fields {
			fieldKey := "module." + module.Metadata.Name + ".field." + field.Name
			fmt.Fprintf(&zhCN, "  %s: %s,\n", tsQuote(fieldKey), tsQuote(field.DisplayName))
			fmt.Fprintf(&enUS, "  %s: %s,\n", tsQuote(fieldKey), tsQuote(field.DisplayName))
		}
	}
	zhCN.WriteString("};\n")
	enUS.WriteString("};\n")
	return zhCN.String(), enUS.String()
}

func compareOutput(repository *os.Root, candidate output) (Change, error) {
	relative, err := rootedName(candidate.path)
	if err != nil {
		return Change{}, err
	}
	action := ActionCreate
	existing, readErr := repository.ReadFile(relative)
	if readErr == nil {
		if candidate.managed && !bytes.Contains(existing, []byte(generatedMarker)) {
			return Change{}, &ConflictError{Path: filepath.ToSlash(candidate.path)}
		}
		action = ActionUpdate
		if bytes.Equal(normalizeNewline(existing), normalizeNewline(candidate.content)) {
			action = ActionUnchanged
		}
	} else if !errors.Is(readErr, os.ErrNotExist) {
		return Change{}, fmt.Errorf("read existing output %s: %w", candidate.path, readErr)
	}
	digest := sha256.Sum256(candidate.content)
	return Change{
		Path:     filepath.ToSlash(candidate.path),
		Action:   action,
		Managed:  candidate.managed,
		Bytes:    len(candidate.content),
		SHA256:   hex.EncodeToString(digest[:]),
		Source:   candidate.source,
		content:  candidate.content,
		fileMode: candidate.fileMode,
	}, nil
}

func compareObsoleteOutput(repository *os.Root, path string) (Change, bool, error) {
	relative, err := rootedName(path)
	if err != nil {
		return Change{}, false, err
	}
	existing, err := repository.ReadFile(relative)
	if errors.Is(err, os.ErrNotExist) {
		return Change{}, false, nil
	}
	if err != nil {
		return Change{}, false, fmt.Errorf("read obsolete generated output %s: %w", path, err)
	}
	if !bytes.Contains(existing, []byte(generatedMarker)) {
		return Change{}, false, &ConflictError{Path: filepath.ToSlash(path)}
	}
	digest := sha256.Sum256(existing)
	return Change{
		Path:    filepath.ToSlash(path),
		Action:  ActionDelete,
		Managed: true,
		Bytes:   len(existing),
		SHA256:  hex.EncodeToString(digest[:]),
		Source:  "obsolete generated output",
	}, true, nil
}

func writeAtomic(repository *os.Root, change Change) error {
	relative, err := rootedName(change.Path)
	if err != nil {
		return err
	}
	if change.Action == ActionDelete {
		existing, readErr := repository.ReadFile(relative)
		if errors.Is(readErr, os.ErrNotExist) {
			return nil
		}
		if readErr != nil {
			return fmt.Errorf("read obsolete generated output %s before delete: %w", change.Path, readErr)
		}
		if !bytes.Contains(existing, []byte(generatedMarker)) {
			return &ConflictError{Path: change.Path}
		}
		if err := repository.Remove(relative); err != nil {
			return fmt.Errorf("delete obsolete generated output %s: %w", change.Path, err)
		}
		return nil
	}
	directory := filepath.Dir(relative)
	if directory != "." {
		if err := repository.MkdirAll(directory, 0o755); err != nil {
			return fmt.Errorf("create output directory for %s: %w", change.Path, err)
		}
	}
	mode := change.fileMode
	if mode == 0 {
		mode = 0o644
	}
	temporary, temporaryName, err := createRootTemp(repository, directory, mode)
	if err != nil {
		return fmt.Errorf("create temporary output for %s: %w", change.Path, err)
	}
	cleanup := func() {
		_ = temporary.Close()
		_ = repository.Remove(temporaryName)
	}
	if _, err := temporary.Write(change.content); err != nil {
		cleanup()
		return fmt.Errorf("write temporary output for %s: %w", change.Path, err)
	}
	if err := temporary.Chmod(mode); err != nil {
		cleanup()
		return fmt.Errorf("chmod temporary output for %s: %w", change.Path, err)
	}
	if err := temporary.Sync(); err != nil {
		cleanup()
		return fmt.Errorf("sync temporary output for %s: %w", change.Path, err)
	}
	if err := temporary.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close temporary output for %s: %w", change.Path, err)
	}
	if err := repository.Rename(temporaryName, relative); err != nil {
		cleanup()
		return fmt.Errorf("replace output %s: %w", change.Path, err)
	}
	return nil
}

func createRootTemp(repository *os.Root, directory string, mode os.FileMode) (*os.File, string, error) {
	for attempt := 0; attempt < 100; attempt++ {
		var entropy [12]byte
		if _, err := rand.Read(entropy[:]); err != nil {
			return nil, "", err
		}
		name := ".mss-generate-" + hex.EncodeToString(entropy[:])
		if directory != "." {
			name = filepath.Join(directory, name)
		}
		file, err := repository.OpenFile(name, os.O_RDWR|os.O_CREATE|os.O_EXCL, mode)
		if err == nil {
			return file, name, nil
		}
		if !errors.Is(err, os.ErrExist) {
			return nil, "", err
		}
	}
	return nil, "", errors.New("temporary output name collision limit exceeded")
}

func renderTemplate(path string, data templateData) ([]byte, error) {
	relative, err := rootedName(path)
	if err != nil {
		return nil, err
	}
	embeddedPath := filepath.ToSlash(relative)
	embeddedPath = strings.TrimPrefix(embeddedPath, "templates/")
	content, err := foundationtemplates.Module.ReadFile(embeddedPath)
	if err != nil {
		return nil, fmt.Errorf("read generator template %s: %w", path, err)
	}
	parsed, err := template.New(filepath.Base(path)).Option("missingkey=error").Parse(string(content))
	if err != nil {
		return nil, fmt.Errorf("parse generator template %s: %w", path, err)
	}
	var buffer bytes.Buffer
	if err := parsed.Execute(&buffer, data); err != nil {
		return nil, fmt.Errorf("execute generator template %s: %w", path, err)
	}
	return buffer.Bytes(), nil
}

func rootedName(relative string) (string, error) {
	if filepath.IsAbs(relative) {
		return "", fmt.Errorf("output path %q must be repository-relative", relative)
	}
	cleaned := filepath.Clean(filepath.FromSlash(relative))
	if cleaned == "." || cleaned == ".." || strings.HasPrefix(cleaned, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("output path %q escapes repository root", relative)
	}
	return cleaned, nil
}

func canonicalModuleSourcePath(repository *os.Root, repositoryPath, sourcePath string) (string, error) {
	if strings.TrimSpace(sourcePath) == "" {
		return "module.yaml", nil
	}
	rootAbsolute, err := filepath.Abs(repositoryPath)
	if err != nil {
		return "", fmt.Errorf("resolve repository root for module source: %w", err)
	}
	rootResolved, err := filepath.EvalSymlinks(rootAbsolute)
	if err != nil {
		return "", fmt.Errorf("resolve repository root for module source: %w", err)
	}

	var relative string
	if filepath.IsAbs(sourcePath) {
		sourceAbsolute := filepath.Clean(sourcePath)
		if sourceResolved, resolveErr := filepath.EvalSymlinks(sourceAbsolute); resolveErr == nil {
			relative, err = filepath.Rel(rootResolved, sourceResolved)
		} else {
			relative, err = filepath.Rel(rootAbsolute, sourceAbsolute)
		}
		if err != nil {
			return "", fmt.Errorf("resolve module source %q: %w", sourcePath, err)
		}
	} else {
		relative, err = rootedName(sourcePath)
		if err != nil {
			return "", fmt.Errorf("confine module source: %w", err)
		}
	}
	if relative == "." || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return "", fmt.Errorf("module source %q is outside the repository root", sourcePath)
	}
	relative, err = rootedName(relative)
	if err != nil {
		return "", fmt.Errorf("confine module source: %w", err)
	}
	info, statErr := repository.Stat(relative)
	if statErr == nil {
		if !info.Mode().IsRegular() {
			return "", fmt.Errorf("module source %q is not a regular repository file", sourcePath)
		}
	} else if !errors.Is(statErr, os.ErrNotExist) {
		return "", fmt.Errorf("module source %q escapes or cannot be inspected within the repository: %w", sourcePath, statErr)
	}
	return filepath.ToSlash(relative), nil
}

func renderColumns(module *spec.Module) string {
	var builder strings.Builder
	for _, field := range module.Spec.Entity.Fields {
		if field.List != nil && !*field.List {
			continue
		}
		fmt.Fprintf(&builder, "    {\n")
		fmt.Fprintf(&builder, "      title: intl.formatMessage({ id: %s, defaultMessage: %s }),\n",
			tsQuote("module."+module.Metadata.Name+".field."+field.Name), tsQuote(field.DisplayName))
		fmt.Fprintf(&builder, "      dataIndex: %s,\n", tsQuote(field.Name))
		if !field.Searchable && !field.Filterable {
			builder.WriteString("      hideInSearch: true,\n")
		}
		switch field.Type {
		case "bool":
			builder.WriteString("      valueType: 'switch',\n")
		case "date":
			builder.WriteString("      valueType: 'date',\n")
		case "datetime":
			builder.WriteString("      valueType: 'dateTime',\n")
		case "decimal":
			builder.WriteString("      valueType: 'money',\n")
		case "enum":
			builder.WriteString("      valueEnum: {\n")
			for _, value := range field.EnumValues {
				fmt.Fprintf(&builder, "        %s: { text: %s%s },\n", tsQuote(value.Value), tsQuote(value.Label), enumColor(value.Color))
			}
			builder.WriteString("      },\n")
		}
		if width, ok := numericWidth(field.UI.Width); ok {
			fmt.Fprintf(&builder, "      width: %d,\n", width)
		}
		builder.WriteString("    },\n")
	}
	return builder.String()
}

func renderFormFields(module *spec.Module) string {
	var builder strings.Builder
	for _, field := range module.Spec.Entity.Fields {
		if field.Form != nil && !*field.Form {
			continue
		}
		component := formComponent(field)
		fmt.Fprintf(&builder, "        <%s\n", component)
		fmt.Fprintf(&builder, "          name=%s\n", tsQuote(field.Name))
		fmt.Fprintf(&builder, "          label={intl.formatMessage({ id: %s, defaultMessage: %s })}\n",
			tsQuote("module."+module.Metadata.Name+".field."+field.Name), tsQuote(field.DisplayName))
		if field.Required {
			builder.WriteString("          rules={[{ required: true }]}\n")
		}
		if field.Immutable {
			builder.WriteString("          disabled={Boolean(current?.id)}\n")
		}
		if field.Type == "enum" {
			builder.WriteString("          options={[\n")
			for _, value := range field.EnumValues {
				fmt.Fprintf(&builder, "            { label: %s, value: %s },\n", tsQuote(value.Label), tsQuote(value.Value))
			}
			builder.WriteString("          ]}\n")
		}
		builder.WriteString("        />\n")
	}
	return builder.String()
}

func formComponent(field spec.FieldSpec) string {
	if field.UI.Component != "" {
		switch field.UI.Component {
		case "textarea", "json-editor":
			return "ProFormTextArea"
		case "number", "money":
			return "ProFormDigit"
		case "select", "radio", "checkbox", "relation-select":
			return "ProFormSelect"
		case "switch":
			return "ProFormSwitch"
		case "date":
			return "ProFormDatePicker"
		case "datetime":
			return "ProFormDateTimePicker"
		default:
			return "ProFormText"
		}
	}
	switch field.Type {
	case "text", "json", "files":
		return "ProFormTextArea"
	case "int", "int64", "uint", "float64", "decimal":
		return "ProFormDigit"
	case "enum", "relation":
		return "ProFormSelect"
	case "bool":
		return "ProFormSwitch"
	case "date":
		return "ProFormDatePicker"
	case "datetime":
		return "ProFormDateTimePicker"
	default:
		return "ProFormText"
	}
}

func enumColor(color string) string {
	if color == "" {
		return ""
	}
	return ", status: " + tsQuote(color)
}

func numericWidth(value any) (int, bool) {
	switch typed := value.(type) {
	case int:
		return typed, true
	case int64:
		return int(typed), true
	case float64:
		return int(typed), true
	case string:
		width, err := strconv.Atoi(typed)
		return width, err == nil
	default:
		return 0, false
	}
}

func normalizeNewline(content []byte) []byte {
	normalized := bytes.ReplaceAll(content, []byte("\r\n"), []byte("\n"))
	normalized = bytes.TrimRight(normalized, "\n")
	return append(normalized, '\n')
}

func sanitizeTagValue(value string) string {
	value = strings.ReplaceAll(value, ";", ",")
	value = strings.ReplaceAll(value, "`", "'")
	value = strings.ReplaceAll(value, "\n", " ")
	return strings.TrimSpace(value)
}

func escapeGoContent(value string) string {
	quoted := strconv.Quote(value)
	if len(quoted) >= 2 {
		return quoted[1 : len(quoted)-1]
	}
	return value
}

func tsQuote(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "'", "\\'")
	value = strings.ReplaceAll(value, "\r", "")
	value = strings.ReplaceAll(value, "\n", "\\n")
	return "'" + value + "'"
}

func numberString(value float64) string {
	return strconv.FormatFloat(value, 'f', -1, 64)
}

func yesNo(value bool) string {
	if value {
		return "是"
	}
	return "否"
}

func contains(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}
