package generator

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/mss-boot-io/mss-boot-admin/internal/mss/spec"
)

const generatedMarker = "Code generated by mss"

// Action describes how one output differs from the workspace.
type Action string

const (
	ActionCreate    Action = "create"
	ActionUpdate    Action = "update"
	ActionUnchanged Action = "unchanged"
)

// Options control generation. Dry-run is the default when Write is false.
type Options struct {
	Root  string
	Write bool
	Check bool
}

// Change is one deterministic output decision.
type Change struct {
	Path     string `json:"path"`
	Action   Action `json:"action"`
	Managed  bool   `json:"managed"`
	Bytes    int    `json:"bytes"`
	SHA256   string `json:"sha256"`
	Source   string `json:"source,omitempty"`
	content  []byte
	fileMode os.FileMode
}

// Plan is safe to render for humans or agents before applying writes.
type Plan struct {
	Module      string    `json:"module"`
	GeneratedAt time.Time `json:"generatedAt"`
	DryRun      bool      `json:"dryRun"`
	Check       bool      `json:"check"`
	Changes     []Change  `json:"changes"`
}

// DriftError is returned by --check when generated output is missing or stale.
type DriftError struct {
	Paths []string
}

func (e *DriftError) Error() string {
	return "generated module output is stale: " + strings.Join(e.Paths, ", ")
}

// JSON returns stable indented JSON.
func (p Plan) JSON() ([]byte, error) {
	return json.MarshalIndent(p, "", "  ")
}

// Text returns a compact generation summary.
func (p Plan) Text() string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "mss module generate: %s\n", p.Module)
	fmt.Fprintf(&builder, "dry-run: %t\n", p.DryRun)
	fmt.Fprintf(&builder, "check: %t\n\n", p.Check)
	for _, change := range p.Changes {
		fmt.Fprintf(&builder, "%-9s %s (%d bytes, %s)\n", change.Action, change.Path, change.Bytes, change.SHA256[:12])
	}
	return builder.String()
}

// Generate renders one validated module and optionally writes the plan atomically.
func Generate(module *spec.Module, options Options) (Plan, error) {
	if module == nil {
		return Plan{}, errors.New("module specification is nil")
	}
	if options.Root == "" {
		return Plan{}, errors.New("repository root is required")
	}
	if issues := module.Validate(); len(issues) > 0 {
		return Plan{}, &spec.ValidationError{Issues: issues}
	}

	data, err := buildTemplateData(module)
	if err != nil {
		return Plan{}, err
	}
	outputs, err := renderModuleOutputs(options.Root, module, data)
	if err != nil {
		return Plan{}, err
	}
	registryOutputs, err := renderRegistryOutputs(options.Root, module)
	if err != nil {
		return Plan{}, err
	}
	outputs = append(outputs, registryOutputs...)

	plan := Plan{
		Module:      module.Metadata.Name,
		GeneratedAt: time.Now().UTC(),
		DryRun:      !options.Write,
		Check:       options.Check,
		Changes:     make([]Change, 0, len(outputs)),
	}

	for _, output := range outputs {
		change, err := compareOutput(options.Root, output)
		if err != nil {
			return Plan{}, err
		}
		plan.Changes = append(plan.Changes, change)
	}
	sort.SliceStable(plan.Changes, func(i, j int) bool {
		return plan.Changes[i].Path < plan.Changes[j].Path
	})

	if options.Check {
		var stale []string
		for _, change := range plan.Changes {
			if change.Action != ActionUnchanged {
				stale = append(stale, change.Path)
			}
		}
		if len(stale) > 0 {
			return plan, &DriftError{Paths: stale}
		}
		return plan, nil
	}

	if options.Write {
		for _, change := range plan.Changes {
			if change.Action == ActionUnchanged {
				continue
			}
			if err := writeAtomic(options.Root, change); err != nil {
				return plan, err
			}
		}
	}
	return plan, nil
}

type output struct {
	path     string
	content  []byte
	managed  bool
	source   string
	fileMode os.FileMode
}

type templateData struct {
	SourceSpec     string
	ModuleName     string
	Package        string
	ModelName      string
	DisplayName    string
	Description    string
	Table          string
	APIResource    string
	NeedsTime      bool
	Fields         []fieldData
	SearchFields   []fieldData
	Permissions    []permissionData
	Menu           menuData
	ColumnsCode    string
	FormFieldsCode string
}

type fieldData struct {
	JSONName       string
	GoName         string
	GoType         string
	SearchType     string
	TSType         string
	TSOptional     bool
	GormTag        string
	BindingTag     string
	SearchTag      string
	DisplayName    string
	SpecType       string
	RequiredText   string
	SearchableText string
	FilterableText string
}

type permissionData struct {
	Code        string
	DisplayName string
	Description string
}

type menuData struct {
	Path          string
	DisplayName   string
	DisplayNameEn string
	Icon          string
	Parent        string
	Order         int
	Hidden        bool
}

func buildTemplateData(module *spec.Module) (templateData, error) {
	data := templateData{
		SourceSpec:  filepath.ToSlash(module.SourcePath),
		ModuleName:  module.Metadata.Name,
		Package:     strings.ReplaceAll(spec.SnakeCase(module.Metadata.Name), "-", "_"),
		ModelName:   module.Spec.Entity.GoName,
		DisplayName: escapeGoContent(module.Metadata.DisplayName),
		Description: escapeGoContent(module.Metadata.Description),
		Table:       module.Spec.Entity.Table,
		APIResource: strings.TrimPrefix(module.Spec.API.BasePath, "/"),
		Menu: menuData{
			Path:          escapeGoContent(module.Spec.Menu.Path),
			DisplayName:   escapeGoContent(module.Spec.Menu.DisplayName),
			DisplayNameEn: escapeGoContent(module.Spec.Menu.DisplayNameEn),
			Icon:          escapeGoContent(module.Spec.Menu.Icon),
			Parent:        escapeGoContent(module.Spec.Menu.Parent),
			Order:         module.Spec.Menu.Order,
			Hidden:        module.Spec.Menu.Hidden,
		},
	}
	if data.SourceSpec == "" {
		data.SourceSpec = "module.yaml"
	}

	for _, field := range module.Spec.Entity.Fields {
		mapped, err := mapField(field)
		if err != nil {
			return templateData{}, err
		}
		data.Fields = append(data.Fields, mapped)
		if field.Type == "date" || field.Type == "datetime" {
			data.NeedsTime = true
		}
		if field.Searchable || field.Filterable {
			data.SearchFields = append(data.SearchFields, mapped)
		}
	}
	for _, permission := range module.Spec.Permissions {
		data.Permissions = append(data.Permissions, permissionData{
			Code:        escapeGoContent(module.PermissionCode(permission.Action)),
			DisplayName: escapeGoContent(permission.DisplayName),
			Description: escapeGoContent(permission.Description),
		})
	}

	data.ColumnsCode = renderColumns(module)
	data.FormFieldsCode = renderFormFields(module)
	return data, nil
}

func mapField(field spec.FieldSpec) (fieldData, error) {
	goType, searchType, tsType, err := fieldTypes(field)
	if err != nil {
		return fieldData{}, err
	}
	gormTag := buildGORMTag(field)
	bindingTag := buildBindingTag(field)
	searchKind := "exact"
	if field.Searchable && contains([]string{"string", "text"}, field.Type) {
		searchKind = "contains"
	}
	searchTag := "type:" + searchKind + ";column:" + field.Column
	return fieldData{
		JSONName:       field.Name,
		GoName:         field.GoName,
		GoType:         goType,
		SearchType:     searchType,
		TSType:         tsType,
		TSOptional:     !field.Required || field.Nullable,
		GormTag:        gormTag,
		BindingTag:     bindingTag,
		SearchTag:      searchTag,
		DisplayName:    field.DisplayName,
		SpecType:       field.Type,
		RequiredText:   yesNo(field.Required),
		SearchableText: yesNo(field.Searchable),
		FilterableText: yesNo(field.Filterable),
	}, nil
}

func fieldTypes(field spec.FieldSpec) (goType, searchType, tsType string, err error) {
	switch field.Type {
	case "string", "text", "enum", "uuid", "file", "files", "json", "relation":
		goType, searchType, tsType = "string", "string", "string"
	case "int":
		goType, searchType, tsType = "int", "int", "number"
	case "int64":
		goType, searchType, tsType = "int64", "int64", "number"
	case "uint":
		goType, searchType, tsType = "uint", "uint", "number"
	case "float64", "decimal":
		goType, searchType, tsType = "float64", "float64", "number"
	case "bool":
		goType, searchType, tsType = "bool", "bool", "boolean"
	case "date", "datetime":
		goType, searchType, tsType = "time.Time", "string", "string"
	default:
		return "", "", "", fmt.Errorf("unsupported field type %q", field.Type)
	}
	if field.Nullable {
		goType = "*" + goType
	}
	return goType, searchType, tsType, nil
}

func buildGORMTag(field spec.FieldSpec) string {
	parts := []string{"column:" + field.Column, "type:" + databaseType(field)}
	if field.Required && !field.Nullable {
		parts = append(parts, "not null")
	}
	if field.Unique {
		parts = append(parts, "uniqueIndex")
	} else if field.Index {
		parts = append(parts, "index")
	}
	if field.Default != nil {
		parts = append(parts, "default:"+sanitizeTagValue(fmt.Sprint(field.Default)))
	}
	if field.DisplayName != "" {
		parts = append(parts, "comment:"+sanitizeTagValue(field.DisplayName))
	}
	return strings.Join(parts, ";")
}

func databaseType(field spec.FieldSpec) string {
	maxLength := 255
	if field.Validation.MaxLength != nil {
		maxLength = *field.Validation.MaxLength
	}
	switch field.Type {
	case "string", "enum", "uuid", "file", "relation":
		return fmt.Sprintf("varchar(%d)", maxLength)
	case "text", "files":
		return "text"
	case "json":
		return "json"
	case "int":
		return "int"
	case "int64":
		return "bigint"
	case "uint":
		return "bigint unsigned"
	case "float64":
		return "double"
	case "decimal":
		precision, scale := 18, 2
		if field.Validation.Precision != nil {
			precision = *field.Validation.Precision
		}
		if field.Validation.Scale != nil {
			scale = *field.Validation.Scale
		}
		return fmt.Sprintf("decimal(%d,%d)", precision, scale)
	case "bool":
		return "boolean"
	case "date":
		return "date"
	case "datetime":
		return "datetime"
	default:
		return "text"
	}
}

func buildBindingTag(field spec.FieldSpec) string {
	var rules []string
	if field.Required {
		rules = append(rules, "required")
	}
	if field.Validation.Format == "email" {
		rules = append(rules, "email")
	}
	if field.Validation.MinLength != nil {
		rules = append(rules, "min="+strconv.Itoa(*field.Validation.MinLength))
	}
	if field.Validation.MaxLength != nil {
		rules = append(rules, "max="+strconv.Itoa(*field.Validation.MaxLength))
	}
	if field.Validation.Minimum != nil {
		rules = append(rules, "gte="+numberString(*field.Validation.Minimum))
	}
	if field.Validation.Maximum != nil {
		rules = append(rules, "lte="+numberString(*field.Validation.Maximum))
	}
	return strings.Join(rules, ",")
}

func renderModuleOutputs(root string, module *spec.Module, data templateData) ([]output, error) {
	moduleDir := filepath.Join("admin", "modules", module.Metadata.Name)
	frontendDir := filepath.Join("web", "antd", "src", "modules", module.Metadata.Name)
	pageDir := filepath.Join("web", "antd", "src", "pages", "generated", module.Spec.Entity.GoName)
	mappings := []struct {
		template string
		path     string
	}{
		{"templates/module/backend/model.go.tmpl", filepath.Join(moduleDir, "model_generated.go")},
		{"templates/module/backend/search.go.tmpl", filepath.Join(moduleDir, "search_generated.go")},
		{"templates/module/backend/controller.go.tmpl", filepath.Join(moduleDir, "controller_generated.go")},
		{"templates/module/backend/descriptor.go.tmpl", filepath.Join(moduleDir, "descriptor_generated.go")},
		{"templates/module/backend/module_test.go.tmpl", filepath.Join(moduleDir, "module_generated_test.go")},
		{"templates/module/backend/AGENTS.md.tmpl", filepath.Join(moduleDir, "AGENTS.md")},
		{"templates/module/frontend/types.ts.tmpl", filepath.Join(frontendDir, "types.ts")},
		{"templates/module/frontend/service.ts.tmpl", filepath.Join(frontendDir, "service.ts")},
		{"templates/module/frontend/index.tsx.tmpl", filepath.Join(frontendDir, "index.tsx")},
		{"templates/module/frontend/page.tsx.tmpl", filepath.Join(pageDir, "index.tsx")},
		{"templates/module/docs/module.md.tmpl", filepath.Join("docs", "docs", "modules", module.Metadata.Name+".md")},
	}

	outputs := make([]output, 0, len(mappings)+2)
	for _, mapping := range mappings {
		content, err := renderTemplate(filepath.Join(root, filepath.FromSlash(mapping.template)), data)
		if err != nil {
			return nil, err
		}
		if strings.HasSuffix(mapping.path, ".go") {
			content, err = format.Source(content)
			if err != nil {
				return nil, fmt.Errorf("format generated Go file %s: %w", mapping.path, err)
			}
		}
		outputs = append(outputs, output{
			path:     filepath.ToSlash(mapping.path),
			content:  normalizeNewline(content),
			managed:  true,
			source:   filepath.ToSlash(mapping.template),
			fileMode: 0o644,
		})
	}

	normalizedSpec, err := module.YAML()
	if err != nil {
		return nil, fmt.Errorf("marshal normalized module spec: %w", err)
	}
	outputs = append(outputs, output{
		path:     filepath.ToSlash(filepath.Join(moduleDir, "module.yaml")),
		content:  normalizeNewline(normalizedSpec),
		managed:  true,
		source:   filepath.ToSlash(module.SourcePath),
		fileMode: 0o644,
	})

	customPath := filepath.ToSlash(filepath.Join(moduleDir, "custom.go"))
	if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(customPath))); errors.Is(err, os.ErrNotExist) {
		custom := fmt.Sprintf("package %s\n\n// Add non-generated business rules and extension hooks in this file.\n", data.Package)
		formatted, formatErr := format.Source([]byte(custom))
		if formatErr != nil {
			return nil, formatErr
		}
		outputs = append(outputs, output{
			path:     customPath,
			content:  formatted,
			managed:  false,
			source:   "generator extension point",
			fileMode: 0o644,
		})
	}
	return outputs, nil
}

func renderRegistryOutputs(root string, current *spec.Module) ([]output, error) {
	modules, err := discoverModules(root, current)
	if err != nil {
		return nil, err
	}

	var goRegistry strings.Builder
	goRegistry.WriteString("// Code generated by mss module sync. DO NOT EDIT.\n\n")
	goRegistry.WriteString("// Package all imports every enabled vertical module for registration side effects.\n")
	goRegistry.WriteString("package all\n")
	if len(modules) > 0 {
		goRegistry.WriteString("\nimport (\n")
		for _, module := range modules {
			fmt.Fprintf(&goRegistry, "\t_ \"github.com/mss-boot-io/mss-boot-admin/admin/modules/%s\"\n", module.Metadata.Name)
		}
		goRegistry.WriteString(")\n")
	}
	formattedRegistry, err := format.Source([]byte(goRegistry.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated module registry: %w", err)
	}

	var routes strings.Builder
	routes.WriteString("// Code generated by mss module sync. DO NOT EDIT.\n\n")
	routes.WriteString("export default [\n")
	for _, module := range modules {
		fmt.Fprintf(&routes, "  { path: %s, name: %s, icon: %s, component: %s },\n",
			tsQuote(module.Spec.Menu.Path),
			tsQuote(module.Metadata.Name),
			tsQuote(module.Spec.Menu.Icon),
			tsQuote("./generated/"+module.Spec.Entity.GoName),
		)
	}
	routes.WriteString("];\n")

	zhCN, enUS := renderLocales(modules)
	return []output{
		{
			path:     "admin/modules/all/generated.go",
			content:  normalizeNewline(formattedRegistry),
			managed:  true,
			source:   "admin/modules/*/module.yaml",
			fileMode: 0o644,
		},
		{
			path:     "web/antd/config/routes.generated.ts",
			content:  normalizeNewline([]byte(routes.String())),
			managed:  true,
			source:   "admin/modules/*/module.yaml",
			fileMode: 0o644,
		},
		{
			path:     "web/antd/src/locales/generated.zh-CN.ts",
			content:  normalizeNewline([]byte(zhCN)),
			managed:  true,
			source:   "admin/modules/*/module.yaml",
			fileMode: 0o644,
		},
		{
			path:     "web/antd/src/locales/generated.en-US.ts",
			content:  normalizeNewline([]byte(enUS)),
			managed:  true,
			source:   "admin/modules/*/module.yaml",
			fileMode: 0o644,
		},
	}, nil
}

func discoverModules(root string, current *spec.Module) ([]*spec.Module, error) {
	byName := map[string]*spec.Module{current.Metadata.Name: current}
	matches, err := filepath.Glob(filepath.Join(root, "admin", "modules", "*", "module.yaml"))
	if err != nil {
		return nil, fmt.Errorf("discover module specs: %w", err)
	}
	for _, match := range matches {
		module, loadErr := spec.LoadModule(match)
		if loadErr != nil {
			return nil, loadErr
		}
		if module.Metadata.Name == current.Metadata.Name {
			continue
		}
		byName[module.Metadata.Name] = module
	}
	modules := make([]*spec.Module, 0, len(byName))
	for _, module := range byName {
		modules = append(modules, module)
	}
	sort.SliceStable(modules, func(i, j int) bool {
		return modules[i].Metadata.Name < modules[j].Metadata.Name
	})
	return modules, nil
}

func renderLocales(modules []*spec.Module) (string, string) {
	var zhCN strings.Builder
	var enUS strings.Builder
	zhCN.WriteString("// Code generated by mss module sync. DO NOT EDIT.\n\nexport default {\n")
	enUS.WriteString("// Code generated by mss module sync. DO NOT EDIT.\n\nexport default {\n")
	for _, module := range modules {
		key := "menu." + module.Metadata.Name
		fmt.Fprintf(&zhCN, "  %s: %s,\n", tsQuote(key), tsQuote(module.Spec.Menu.DisplayName))
		englishName := module.Spec.Menu.DisplayNameEn
		if englishName == "" {
			englishName = module.Metadata.DisplayName
		}
		fmt.Fprintf(&enUS, "  %s: %s,\n", tsQuote(key), tsQuote(englishName))
		for _, field := range module.Spec.Entity.Fields {
			fieldKey := "module." + module.Metadata.Name + ".field." + field.Name
			fmt.Fprintf(&zhCN, "  %s: %s,\n", tsQuote(fieldKey), tsQuote(field.DisplayName))
			fmt.Fprintf(&enUS, "  %s: %s,\n", tsQuote(fieldKey), tsQuote(field.DisplayName))
		}
	}
	zhCN.WriteString("};\n")
	enUS.WriteString("};\n")
	return zhCN.String(), enUS.String()
}

func compareOutput(root string, candidate output) (Change, error) {
	absolute, err := safePath(root, candidate.path)
	if err != nil {
		return Change{}, err
	}
	action := ActionCreate
	existing, readErr := os.ReadFile(absolute)
	if readErr == nil {
		action = ActionUpdate
		if bytes.Equal(normalizeNewline(existing), normalizeNewline(candidate.content)) {
			action = ActionUnchanged
		}
	} else if !errors.Is(readErr, os.ErrNotExist) {
		return Change{}, fmt.Errorf("read existing output %s: %w", candidate.path, readErr)
	}
	digest := sha256.Sum256(candidate.content)
	return Change{
		Path:     filepath.ToSlash(candidate.path),
		Action:   action,
		Managed:  candidate.managed,
		Bytes:    len(candidate.content),
		SHA256:   hex.EncodeToString(digest[:]),
		Source:   candidate.source,
		content:  candidate.content,
		fileMode: candidate.fileMode,
	}, nil
}

func writeAtomic(root string, change Change) error {
	absolute, err := safePath(root, change.Path)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(absolute), 0o755); err != nil {
		return fmt.Errorf("create output directory for %s: %w", change.Path, err)
	}
	mode := change.fileMode
	if mode == 0 {
		mode = 0o644
	}
	temporary, err := os.CreateTemp(filepath.Dir(absolute), ".mss-generate-*")
	if err != nil {
		return fmt.Errorf("create temporary output for %s: %w", change.Path, err)
	}
	temporaryName := temporary.Name()
	cleanup := func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryName)
	}
	if _, err := temporary.Write(change.content); err != nil {
		cleanup()
		return fmt.Errorf("write temporary output for %s: %w", change.Path, err)
	}
	if err := temporary.Chmod(mode); err != nil {
		cleanup()
		return fmt.Errorf("chmod temporary output for %s: %w", change.Path, err)
	}
	if err := temporary.Sync(); err != nil {
		cleanup()
		return fmt.Errorf("sync temporary output for %s: %w", change.Path, err)
	}
	if err := temporary.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close temporary output for %s: %w", change.Path, err)
	}
	if err := os.Rename(temporaryName, absolute); err != nil {
		cleanup()
		return fmt.Errorf("replace output %s: %w", change.Path, err)
	}
	return nil
}

func renderTemplate(path string, data templateData) ([]byte, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read generator template %s: %w", path, err)
	}
	parsed, err := template.New(filepath.Base(path)).Option("missingkey=error").Parse(string(content))
	if err != nil {
		return nil, fmt.Errorf("parse generator template %s: %w", path, err)
	}
	var buffer bytes.Buffer
	if err := parsed.Execute(&buffer, data); err != nil {
		return nil, fmt.Errorf("execute generator template %s: %w", path, err)
	}
	return buffer.Bytes(), nil
}

func safePath(root, relative string) (string, error) {
	if filepath.IsAbs(relative) {
		return "", fmt.Errorf("output path %q must be repository-relative", relative)
	}
	cleaned := filepath.Clean(filepath.FromSlash(relative))
	if cleaned == "." || cleaned == ".." || strings.HasPrefix(cleaned, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("output path %q escapes repository root", relative)
	}
	absolute := filepath.Join(root, cleaned)
	rel, err := filepath.Rel(root, absolute)
	if err != nil {
		return "", fmt.Errorf("resolve output path %q: %w", relative, err)
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("output path %q escapes repository root", relative)
	}
	return absolute, nil
}

func renderColumns(module *spec.Module) string {
	var builder strings.Builder
	for _, field := range module.Spec.Entity.Fields {
		if field.List != nil && !*field.List {
			continue
		}
		fmt.Fprintf(&builder, "    {\n")
		fmt.Fprintf(&builder, "      title: intl.formatMessage({ id: %s, defaultMessage: %s }),\n",
			tsQuote("module."+module.Metadata.Name+".field."+field.Name), tsQuote(field.DisplayName))
		fmt.Fprintf(&builder, "      dataIndex: %s,\n", tsQuote(field.Name))
		if !field.Searchable && !field.Filterable {
			builder.WriteString("      hideInSearch: true,\n")
		}
		switch field.Type {
		case "bool":
			builder.WriteString("      valueType: 'switch',\n")
		case "date":
			builder.WriteString("      valueType: 'date',\n")
		case "datetime":
			builder.WriteString("      valueType: 'dateTime',\n")
		case "decimal":
			builder.WriteString("      valueType: 'money',\n")
		case "enum":
			builder.WriteString("      valueEnum: {\n")
			for _, value := range field.EnumValues {
				fmt.Fprintf(&builder, "        %s: { text: %s%s },\n", tsQuote(value.Value), tsQuote(value.Label), enumColor(value.Color))
			}
			builder.WriteString("      },\n")
		}
		if width, ok := numericWidth(field.UI.Width); ok {
			fmt.Fprintf(&builder, "      width: %d,\n", width)
		}
		builder.WriteString("    },\n")
	}
	return builder.String()
}

func renderFormFields(module *spec.Module) string {
	var builder strings.Builder
	for _, field := range module.Spec.Entity.Fields {
		if field.Form != nil && !*field.Form {
			continue
		}
		component := formComponent(field)
		fmt.Fprintf(&builder, "        <%s\n", component)
		fmt.Fprintf(&builder, "          name=%s\n", tsQuote(field.Name))
		fmt.Fprintf(&builder, "          label={intl.formatMessage({ id: %s, defaultMessage: %s })}\n",
			tsQuote("module."+module.Metadata.Name+".field."+field.Name), tsQuote(field.DisplayName))
		if field.Required {
			builder.WriteString("          rules={[{ required: true }]}\n")
		}
		if field.Immutable {
			builder.WriteString("          disabled={Boolean(current?.id)}\n")
		}
		if field.Type == "enum" {
			builder.WriteString("          options={[\n")
			for _, value := range field.EnumValues {
				fmt.Fprintf(&builder, "            { label: %s, value: %s },\n", tsQuote(value.Label), tsQuote(value.Value))
			}
			builder.WriteString("          ]}\n")
		}
		builder.WriteString("        />\n")
	}
	return builder.String()
}

func formComponent(field spec.FieldSpec) string {
	if field.UI.Component != "" {
		switch field.UI.Component {
		case "textarea", "json-editor":
			return "ProFormTextArea"
		case "number", "money":
			return "ProFormDigit"
		case "select", "radio", "checkbox", "relation-select":
			return "ProFormSelect"
		case "switch":
			return "ProFormSwitch"
		case "date":
			return "ProFormDatePicker"
		case "datetime":
			return "ProFormDateTimePicker"
		default:
			return "ProFormText"
		}
	}
	switch field.Type {
	case "text", "json", "files":
		return "ProFormTextArea"
	case "int", "int64", "uint", "float64", "decimal":
		return "ProFormDigit"
	case "enum", "relation":
		return "ProFormSelect"
	case "bool":
		return "ProFormSwitch"
	case "date":
		return "ProFormDatePicker"
	case "datetime":
		return "ProFormDateTimePicker"
	default:
		return "ProFormText"
	}
}

func enumColor(color string) string {
	if color == "" {
		return ""
	}
	return ", status: " + tsQuote(color)
}

func numericWidth(value any) (int, bool) {
	switch typed := value.(type) {
	case int:
		return typed, true
	case int64:
		return int(typed), true
	case float64:
		return int(typed), true
	case string:
		width, err := strconv.Atoi(typed)
		return width, err == nil
	default:
		return 0, false
	}
}

func normalizeNewline(content []byte) []byte {
	normalized := bytes.ReplaceAll(content, []byte("\r\n"), []byte("\n"))
	normalized = bytes.TrimRight(normalized, "\n")
	return append(normalized, '\n')
}

func sanitizeTagValue(value string) string {
	value = strings.ReplaceAll(value, ";", ",")
	value = strings.ReplaceAll(value, "`", "'")
	value = strings.ReplaceAll(value, "\n", " ")
	return strings.TrimSpace(value)
}

func escapeGoContent(value string) string {
	quoted := strconv.Quote(value)
	if len(quoted) >= 2 {
		return quoted[1 : len(quoted)-1]
	}
	return value
}

func tsQuote(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "'", "\\'")
	value = strings.ReplaceAll(value, "\r", "")
	value = strings.ReplaceAll(value, "\n", "\\n")
	return "'" + value + "'"
}

func numberString(value float64) string {
	return strconv.FormatFloat(value, 'f', -1, 64)
}

func yesNo(value bool) string {
	if value {
		return "是"
	}
	return "否"
}

func contains(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}
