version: '3'
services:
  consul-server:
    image: hashicorp/consul:latest
    command: "agent -server -bootstrap-expect=1 -ui -node=consul-server -bind=0.0.0.0 -client=0.0.0.0"
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8400:8400"
      - "8600:8600"
    volumes:
      - consul-data:/consul/data
  consul-client:
    image: hashicorp/consul:latest
    command: "agent -join=consul-server -node=consul-client -bind=0.0.0.0 -client=0.0.0.0"
    links:
      - consul-server
    depends_on:
      - consul-server
volumes:
  consul-data: