import { hasPermission } from '@mss-admin-core/shared/auth/access';
import type { CurrentUser } from '@mss-admin-core/shared/auth/types';

export const opsPermissions = {
  userList: 'litellmops:user-list',
  userRead: 'litellmops:user-read',
  userWrite: 'litellmops:user-write',
  keyList: 'litellmops:key-list',
  keyRead: 'litellmops:key-read',
  keyIssue: 'litellmops:key-issue',
  keyWrite: 'litellmops:key-write',
  keyRevoke: 'litellmops:key-revoke',
  sync: 'litellmops:sync',
  bills: 'litellmops:bills',
  recharge: 'litellmops:recharge',
  orgList: 'litellmops:org-list',
  orgRead: 'litellmops:org-read',
  productRead: 'litellmops:product-read',
  productWrite: 'litellmops:product-write',
  orderRead: 'litellmops:order-read',
  orderImport: 'litellmops:order-import',
  orderVerify: 'litellmops:order-verify',
  orderApprove: 'litellmops:order-approve',
  orderExecute: 'litellmops:order-execute',
  orderReconcile: 'litellmops:order-reconcile',
  orderRefundReview: 'litellmops:order-refund-review',
  gatewayRead: 'litellmops:gateway-read',
  managementResolve: 'litellmops:management-resolve',
} as const;

export function buildOpsAccess(user?: CurrentUser) {
  return {
    canReadGateway: hasPermission(user, opsPermissions.gatewayRead),
    canReadUsers: hasPermission(user, opsPermissions.userList),
    canReadUserDetails: hasPermission(user, opsPermissions.userRead),
    canWriteUsers: hasPermission(user, opsPermissions.userWrite),
    canInviteUsers: hasPermission(user, opsPermissions.userWrite),
    canSync: hasPermission(user, opsPermissions.sync),
    canRecharge: hasPermission(user, opsPermissions.recharge),
    canReadKeys: hasPermission(user, opsPermissions.keyList),
    canReadKeyDetails: hasPermission(user, opsPermissions.keyRead),
    canIssueKeys: hasPermission(user, opsPermissions.keyIssue),
    canWriteKeys: hasPermission(user, opsPermissions.keyWrite),
    canRevokeKeys: hasPermission(user, opsPermissions.keyRevoke),
    canReadOrganizations: hasPermission(user, opsPermissions.orgList),
    canReadOrganizationDetails: hasPermission(user, opsPermissions.orgRead),
    canReadProducts: hasPermission(user, opsPermissions.productRead),
    canWriteProducts: hasPermission(user, opsPermissions.productWrite),
    canReadSales: hasPermission(user, opsPermissions.orderRead),
    canWriteSales: hasPermission(user, opsPermissions.orderImport),
    canVerifySales: hasPermission(user, opsPermissions.orderVerify),
    canApproveSales: hasPermission(user, opsPermissions.orderApprove),
    canExecuteSales: hasPermission(user, opsPermissions.orderExecute),
    canReconcileSales: hasPermission(user, opsPermissions.orderReconcile),
    canReviewRefund: hasPermission(user, opsPermissions.orderRefundReview),
    canResolveManagement: hasPermission(user, opsPermissions.managementResolve),
  };
}
