// Code generated by mss application template __MSS_GENERATOR_VERSION__. DO NOT EDIT.

// Package all returns every enabled business module in stable generation order.
package all

import "__MSS_DISTRIBUTION_BACKEND_MODULE__/business"

// Modules returns a new slice so callers cannot mutate the generated registry.
func Modules() []business.Module {
	return []business.Module{}
}
