// Code generated by mss module template 1.3.0-backend.1 sync. DO NOT EDIT.

// Package all returns every enabled vertical module in stable generation order.
package all

import (
	"github.com/mss-boot-io/mss-boot-admin/admin/business"
	module0 "github.com/mss-boot-io/mss-boot-admin/admin/modules/supplier"
)

// Modules returns a new slice so callers cannot mutate the generated registry.
func Modules() []business.Module {
	return []business.Module{
		module0.Module(),
	}
}
