// Code generated by mss module template 1.1.0-backend.3 sync. DO NOT EDIT.

// Package all imports every enabled vertical module for registration side effects.
package all

import (
	_ "github.com/mss-boot-io/mss-boot-admin/admin/modules/supplier"
)
