// Code generated by mss module presentation template 1.3.7-presentation-v2.2 sync. DO NOT EDIT.

// Package all exposes explicit generated business-module inventories.
package all

import (
	presentationModule0 "github.com/mss-boot-io/mss-boot-admin/admin/modules/supplier"
	"github.com/mss-boot-io/mss-boot-admin/admin/presentation"
)

// Presentations returns a new ordered slice of generated v2 definitions.
// It is inventory only; P2B application composition owns validation and freezing.
func Presentations() []presentation.CapabilityDefinition {
	return []presentation.CapabilityDefinition{
		presentationModule0.PresentationDefinition(), // supplier.list sha256:20979dbd25719ae69c07e383627849910d8a7fb8beb95b023362d56a4c4d72c7
	}
}
