version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "area/frontend"
      - "type/security"
  - package-ecosystem: "npm"
    directory: "/workers-site"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      workers-site-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "area/devops"
      - "type/security"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "area/devops"
      - "type/security"
