// Code generated by mss module template 1.1.0-backend.3 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"reflect"
	"strings"

	"github.com/gin-gonic/gin"
)

const (
	PermissionCreate = "supplier:create"
	PermissionDelete = "supplier:delete"
	PermissionExport = "supplier:export"
	PermissionList   = "supplier:list"
	PermissionRead   = "supplier:read"
	PermissionUpdate = "supplier:update"
)

// Authorizer is required at route composition and enforces backend policy.
type Authorizer interface {
	Authorize(*gin.Context, string) error
}

// OperationContract is the generated HTTP/OpenAPI/permission projection.
type OperationContract struct {
	Operation  string `json:"operation"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Permission string `json:"permission"`
	APIVersion string `json:"apiVersion"`
}

var operationContracts = []OperationContract{
	{Operation: "create", Method: "POST", Path: "/admin/api/suppliers", Permission: PermissionCreate, APIVersion: "v1"},
	{Operation: "delete", Method: "DELETE", Path: "/admin/api/suppliers/{id}", Permission: PermissionDelete, APIVersion: "v1"},
	{Operation: "export", Method: "GET", Path: "/admin/api/suppliers/export", Permission: PermissionExport, APIVersion: "v1"},
	{Operation: "get", Method: "GET", Path: "/admin/api/suppliers/{id}", Permission: PermissionRead, APIVersion: "v1"},
	{Operation: "list", Method: "GET", Path: "/admin/api/suppliers", Permission: PermissionList, APIVersion: "v1"},
	{Operation: "update", Method: "PUT", Path: "/admin/api/suppliers/{id}", Permission: PermissionUpdate, APIVersion: "v1"},
}

// OperationContracts returns a defensive copy of the generated contract.
func OperationContracts() []OperationContract {
	return append([]OperationContract(nil), operationContracts...)
}

// RegisterRoutes mounts only declared operations and refuses to mount without
// an injected authorizer. No init function calls this method.
func RegisterRoutes(group *gin.RouterGroup, application Application, authorizer Authorizer) error {
	if group == nil {
		return errors.New("supplier route group is required")
	}
	if nilInterface(application) {
		return errors.New("supplier application is required")
	}
	if nilInterface(authorizer) {
		return errors.New("supplier authorizer is required")
	}
	controller := &HTTPController{application: application, authorizer: authorizer}
	resource := group.Group("/suppliers")
	resource.Handle("POST", "", controller.authorize(PermissionCreate, controller.Create))
	resource.Handle("DELETE", "/:id", controller.authorize(PermissionDelete, controller.Delete))
	resource.Handle("GET", "/export", controller.authorize(PermissionExport, controller.Export))
	resource.Handle("GET", "/:id", controller.authorize(PermissionRead, controller.Get))
	resource.Handle("GET", "", controller.authorize(PermissionList, controller.List))
	resource.Handle("PUT", "/:id", controller.authorize(PermissionUpdate, controller.Update))
	return nil
}

func nilInterface(value any) bool {
	if value == nil {
		return true
	}
	reflected := reflect.ValueOf(value)
	switch reflected.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return reflected.IsNil()
	default:
		return false
	}
}

// HTTPController implements the generated supplier HTTP boundary.
type HTTPController struct {
	application Application
	authorizer  Authorizer
}

func (controller *HTTPController) authorize(permission string, next gin.HandlerFunc) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		if err := controller.authorizer.Authorize(ctx, permission); err != nil {
			status := http.StatusForbidden
			message := "forbidden"
			switch {
			case errors.Is(err, ErrSupplierAuthenticationRequired):
				status = http.StatusUnauthorized
				message = "unauthorized"
			case errors.Is(err, ErrSupplierAuthorizationUnavailable):
				status = http.StatusServiceUnavailable
				message = "authorization unavailable"
			}
			ctx.AbortWithStatusJSON(status, gin.H{"error": message})
			return
		}
		next(ctx)
	}
}

// List godoc
// @Summary List 供应商管理
// @Tags Supplier
// @Security Bearer
// @Param q query string false "search"
// @Param current query int false "page"
// @Param pageSize query int false "page size (max 100)"
// @Param sortBy query string false "sortable field"
// @Param sortOrder query string false "asc or desc"
// @Success 200 {object} SupplierPage
// @Failure 403 {object} map[string]string
// @Router /admin/api/suppliers [get]
func (controller *HTTPController) List(ctx *gin.Context) {
	var query ListSupplierQuery
	if err := ctx.ShouldBindQuery(&query); err != nil {
		writeSupplierError(ctx, &ValidationError{Field: "query", Rule: "invalid"})
		return
	}
	page, err := controller.application.List(ctx.Request.Context(), query)
	if err != nil {
		writeSupplierError(ctx, err)
		return
	}
	ctx.JSON(http.StatusOK, page)
}

// Get godoc
// @Summary Get 供应商管理
// @Tags Supplier
// @Security Bearer
// @Param id path string true "resource ID"
// @Success 200 {object} Supplier
// @Failure 404 {object} map[string]string
// @Router /admin/api/suppliers/{id} [get]
func (controller *HTTPController) Get(ctx *gin.Context) {
	record, err := controller.application.Get(ctx.Request.Context(), ctx.Param("id"))
	if err != nil {
		writeSupplierError(ctx, err)
		return
	}
	ctx.JSON(http.StatusOK, record)
}

// Create godoc
// @Summary Create 供应商管理
// @Tags Supplier
// @Security Bearer
// @Accept json
// @Produce json
// @Param body body CreateSupplierInput true "create input"
// @Success 201 {object} Supplier
// @Failure 409 {object} map[string]string
// @Failure 422 {object} ValidationError
// @Router /admin/api/suppliers [post]
func (controller *HTTPController) Create(ctx *gin.Context) {
	var input CreateSupplierInput
	if err := decodeSupplierJSON(ctx, &input); err != nil {
		writeSupplierError(ctx, &ValidationError{Field: "body", Rule: "invalid"})
		return
	}
	record, err := controller.application.Create(ctx.Request.Context(), &input)
	if err != nil {
		writeSupplierError(ctx, err)
		return
	}
	ctx.JSON(http.StatusCreated, record)
}

// Update godoc
// @Summary Update 供应商管理
// @Tags Supplier
// @Security Bearer
// @Accept json
// @Produce json
// @Param id path string true "resource ID"
// @Param body body UpdateSupplierInput true "update input"
// @Success 200 {object} Supplier
// @Failure 404 {object} map[string]string
// @Failure 409 {object} map[string]string
// @Failure 422 {object} ValidationError
// @Router /admin/api/suppliers/{id} [put]
func (controller *HTTPController) Update(ctx *gin.Context) {
	var input UpdateSupplierInput
	if err := decodeSupplierJSON(ctx, &input); err != nil {
		writeSupplierError(ctx, &ValidationError{Field: "body", Rule: "invalid"})
		return
	}
	record, err := controller.application.Update(ctx.Request.Context(), ctx.Param("id"), &input)
	if err != nil {
		writeSupplierError(ctx, err)
		return
	}
	ctx.JSON(http.StatusOK, record)
}

// Delete godoc
// @Summary Delete 供应商管理
// @Tags Supplier
// @Security Bearer
// @Param id path string true "resource ID"
// @Success 204
// @Failure 404 {object} map[string]string
// @Router /admin/api/suppliers/{id} [delete]
func (controller *HTTPController) Delete(ctx *gin.Context) {
	if err := controller.application.Delete(ctx.Request.Context(), ctx.Param("id")); err != nil {
		writeSupplierError(ctx, err)
		return
	}
	ctx.Status(http.StatusNoContent)
}

// Export godoc
// @Summary Export 供应商管理
// @Tags Supplier
// @Security Bearer
// @Produce text/csv
// @Success 200 {file} file
// @Failure 403 {object} map[string]string
// @Router /admin/api/suppliers/export [get]
func (controller *HTTPController) Export(ctx *gin.Context) {
	var query ListSupplierQuery
	if err := ctx.ShouldBindQuery(&query); err != nil {
		writeSupplierError(ctx, &ValidationError{Field: "query", Rule: "invalid"})
		return
	}
	var output strings.Builder
	if err := controller.application.Export(ctx.Request.Context(), query, &output); err != nil {
		writeSupplierError(ctx, err)
		return
	}
	ctx.Header("Content-Disposition", "attachment; filename=supplier.csv")
	ctx.Data(http.StatusOK, "text/csv; charset=utf-8", []byte(output.String()))
}

func decodeSupplierJSON(ctx *gin.Context, destination any) error {
	ctx.Request.Body = http.MaxBytesReader(ctx.Writer, ctx.Request.Body, 1<<20)
	decoder := json.NewDecoder(ctx.Request.Body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil {
		return err
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil {
			return fmt.Errorf("multiple JSON values")
		}
		return err
	}
	return nil
}

func writeSupplierError(ctx *gin.Context, err error) {
	var validation *ValidationError
	switch {
	case errors.As(err, &validation):
		ctx.JSON(http.StatusUnprocessableEntity, validation)
	case errors.Is(err, ErrSupplierNotFound):
		ctx.JSON(http.StatusNotFound, gin.H{"error": "not found"})
	case errors.Is(err, ErrSupplierConflict):
		ctx.JSON(http.StatusConflict, gin.H{"error": "conflict"})
	case errors.Is(err, ErrSupplierExportLimit):
		ctx.JSON(http.StatusUnprocessableEntity, gin.H{"error": "export limit exceeded"})
	default:
		ctx.JSON(http.StatusInternalServerError, gin.H{"error": "internal error"})
	}
}
