// Code generated by mss module template 1.1.0-backend.2 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"

	"github.com/gin-gonic/gin"
)

type recordingSupplierAuthorizer struct {
	mu          sync.Mutex
	denied      bool
	permissions []string
}

func (authorizer *recordingSupplierAuthorizer) Authorize(_ *http.Request, permission string) error {
	authorizer.mu.Lock()
	defer authorizer.mu.Unlock()
	authorizer.permissions = append(authorizer.permissions, permission)
	if authorizer.denied {
		return errors.New("denied")
	}
	return nil
}

func TestSupplierRegisterRoutesFailsClosedWithoutAuthorizer(t *testing.T) {
	gin.SetMode(gin.TestMode)
	router := gin.New()
	service, err := NewService(openSupplierTestDatabase(t), discardEventCollector{})
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}
	if err := RegisterRoutes(router.Group("/admin/api"), service, nil); err == nil {
		t.Fatal("RegisterRoutes(nil authorizer) unexpectedly succeeded")
	}
	var typedNilAuthorizer *recordingSupplierAuthorizer
	if err := RegisterRoutes(router.Group("/admin/api"), service, typedNilAuthorizer); err == nil {
		t.Fatal("RegisterRoutes(typed nil authorizer) unexpectedly succeeded")
	}
	if routes := router.Routes(); len(routes) != 0 {
		t.Fatalf("routes mounted before authorization was available: %#v", routes)
	}
}

func TestSupplierHTTPAuthorizationValidationAndDeclaredOperations(t *testing.T) {
	gin.SetMode(gin.TestMode)
	db := openSupplierTestDatabase(t)
	service, err := NewService(db, discardEventCollector{})
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}
	authorizer := &recordingSupplierAuthorizer{denied: true}
	router := gin.New()
	if err := RegisterRoutes(router.Group("/admin/api"), service, authorizer); err != nil {
		t.Fatalf("RegisterRoutes() error = %v", err)
	}
	if got, want := len(router.Routes()), 6; got != want {
		t.Fatalf("registered routes = %d, want %d", got, want)
	}

	body, err := json.Marshal(validSupplierInput())
	if err != nil {
		t.Fatalf("marshal input: %v", err)
	}
	denied := performSupplierRequest(router, http.MethodPost, "/admin/api/suppliers", body)
	if denied.Code != http.StatusForbidden || !strings.Contains(denied.Body.String(), "forbidden") {
		t.Fatalf("denied response = %d %q", denied.Code, denied.Body.String())
	}
	var count int64
	if err := db.Model(new(Supplier)).Count(&count).Error; err != nil || count != 0 {
		t.Fatalf("denied request mutated database: count=%d err=%v", count, err)
	}

	authorizer.mu.Lock()
	authorizer.denied = false
	authorizer.mu.Unlock()
	createdResponse := performSupplierRequest(router, http.MethodPost, "/admin/api/suppliers", body)
	if createdResponse.Code != http.StatusCreated {
		t.Fatalf("create response = %d %q", createdResponse.Code, createdResponse.Body.String())
	}
	var created Supplier
	if err := json.Unmarshal(createdResponse.Body.Bytes(), &created); err != nil || created.ID == "" {
		t.Fatalf("decode created response: record=%#v err=%v", created, err)
	}

	unknown := append(bytes.TrimSuffix(body, []byte("}")), []byte(",\"unknown\":true}")...)
	unknownResponse := performSupplierRequest(router, http.MethodPost, "/admin/api/suppliers", unknown)
	if unknownResponse.Code != http.StatusUnprocessableEntity || strings.Contains(unknownResponse.Body.String(), "unknown") {
		t.Fatalf("unknown-field response = %d %q", unknownResponse.Code, unknownResponse.Body.String())
	}

	listResponse := performSupplierRequest(router, http.MethodGet, "/admin/api/suppliers?current=1&pageSize=20", nil)
	if listResponse.Code != http.StatusOK || !strings.Contains(listResponse.Body.String(), created.ID) {
		t.Fatalf("list response = %d %q", listResponse.Code, listResponse.Body.String())
	}
	exportResponse := performSupplierRequest(router, http.MethodGet, "/admin/api/suppliers/export", nil)
	if exportResponse.Code != http.StatusOK || !strings.Contains(exportResponse.Header().Get("Content-Type"), "text/csv") {
		t.Fatalf("export response = %d %q", exportResponse.Code, exportResponse.Body.String())
	}
}

func performSupplierRequest(handler http.Handler, method, path string, body []byte) *httptest.ResponseRecorder {
	request := httptest.NewRequest(method, path, bytes.NewReader(body))
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	return response
}
