// Code generated by mss module template 1.1.0-backend.3 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"errors"
	"path/filepath"
	"slices"
	"testing"

	"github.com/glebarez/sqlite"
	"github.com/mss-boot-io/mss-boot-admin/admin/models"
	adminpkg "github.com/mss-boot-io/mss-boot-admin/admin/pkg"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func TestSupplierAuthorizationMigrationProjectsExactPolicy(t *testing.T) {
	db := openSupplierAuthorizationTestDatabase(t)
	for attempt := 1; attempt <= 2; attempt++ {
		if err := applySupplierAuthorizationMigration(
			db,
			SupplierAuthorizationMigrationID.String(),
			nil,
		); err != nil {
			t.Fatalf("authorization migration attempt %d: %v", attempt, err)
		}
	}

	var versionCount int64
	if err := db.Model(&migrationmodels.Migration{}).
		Where("version = ?", SupplierAuthorizationMigrationID.String()).
		Count(&versionCount).Error; err != nil || versionCount != 1 {
		t.Fatalf("authorization migration version count = %d, err=%v", versionCount, err)
	}

	var roles []models.Role
	if err := db.Where("name IN ?", []string{"admin", "finance", "procurement"}).
		Order("name").
		Find(&roles).Error; err != nil {
		t.Fatalf("load generated roles: %v", err)
	}
	if got, want := len(roles), 3; got != want {
		t.Fatalf("generated roles = %d, want %d", got, want)
	}
	roleIDs := make(map[string]string, len(roles))
	for _, role := range roles {
		roleIDs[role.Name] = role.ID
	}

	var menu models.Menu
	if err := db.Where("type = ? AND path = ?", adminpkg.MenuAccessType, "/suppliers").Take(&menu).Error; err != nil {
		t.Fatalf("load module menu: %v", err)
	}
	if menu.Name != "supplier" ||
		menu.Permission != "supplier:list" ||
		menu.Icon != "shop" ||
		menu.Sort != 20 ||
		menu.HideInMenu != false {
		t.Fatalf("module menu metadata = %#v", menu)
	}
	var parent models.Menu
	if err := db.Where("id = ?", menu.ParentID).Take(&parent).Error; err != nil {
		t.Fatalf("load menu parent: %v", err)
	}
	if parent.Name != "procurement" || parent.Path != "/procurement" {
		t.Fatalf("menu parent metadata = %#v", parent)
	}
	var componentCreate models.Menu
	if err := db.Where(
		"type = ? AND path = ?",
		adminpkg.ComponentAccessType,
		"/suppliers/permissions/create",
	).Take(&componentCreate).Error; err != nil {
		t.Fatalf("load permission component supplier:create: %v", err)
	}
	if componentCreate.Permission != PermissionCreate ||
		componentCreate.Name != "创建供应商" ||
		componentCreate.ParentID != menu.ID {
		t.Fatalf("permission component supplier:create = %#v", componentCreate)
	}
	var componentDelete models.Menu
	if err := db.Where(
		"type = ? AND path = ?",
		adminpkg.ComponentAccessType,
		"/suppliers/permissions/delete",
	).Take(&componentDelete).Error; err != nil {
		t.Fatalf("load permission component supplier:delete: %v", err)
	}
	if componentDelete.Permission != PermissionDelete ||
		componentDelete.Name != "删除供应商" ||
		componentDelete.ParentID != menu.ID {
		t.Fatalf("permission component supplier:delete = %#v", componentDelete)
	}
	var componentExport models.Menu
	if err := db.Where(
		"type = ? AND path = ?",
		adminpkg.ComponentAccessType,
		"/suppliers/permissions/export",
	).Take(&componentExport).Error; err != nil {
		t.Fatalf("load permission component supplier:export: %v", err)
	}
	if componentExport.Permission != PermissionExport ||
		componentExport.Name != "导出供应商" ||
		componentExport.ParentID != menu.ID {
		t.Fatalf("permission component supplier:export = %#v", componentExport)
	}
	var componentList models.Menu
	if err := db.Where(
		"type = ? AND path = ?",
		adminpkg.ComponentAccessType,
		"/suppliers/permissions/list",
	).Take(&componentList).Error; err != nil {
		t.Fatalf("load permission component supplier:list: %v", err)
	}
	if componentList.Permission != PermissionList ||
		componentList.Name != "查看供应商列表" ||
		componentList.ParentID != menu.ID {
		t.Fatalf("permission component supplier:list = %#v", componentList)
	}
	var componentRead models.Menu
	if err := db.Where(
		"type = ? AND path = ?",
		adminpkg.ComponentAccessType,
		"/suppliers/permissions/read",
	).Take(&componentRead).Error; err != nil {
		t.Fatalf("load permission component supplier:read: %v", err)
	}
	if componentRead.Permission != PermissionRead ||
		componentRead.Name != "查看供应商详情" ||
		componentRead.ParentID != menu.ID {
		t.Fatalf("permission component supplier:read = %#v", componentRead)
	}
	var componentUpdate models.Menu
	if err := db.Where(
		"type = ? AND path = ?",
		adminpkg.ComponentAccessType,
		"/suppliers/permissions/update",
	).Take(&componentUpdate).Error; err != nil {
		t.Fatalf("load permission component supplier:update: %v", err)
	}
	if componentUpdate.Permission != PermissionUpdate ||
		componentUpdate.Name != "编辑供应商" ||
		componentUpdate.ParentID != menu.ID {
		t.Fatalf("permission component supplier:update = %#v", componentUpdate)
	}

	menuDefaultRoles := []string{"admin", "finance", "procurement"}
	menuTargets := []struct {
		accessType adminpkg.AccessType
		path       string
	}{
		{accessType: menu.Type, path: menu.Path},
		{accessType: parent.Type, path: parent.Path},
	}
	for roleName, roleID := range roleIDs {
		for _, target := range menuTargets {
			var count int64
			if err := db.Model(&models.CasbinRule{}).Where(
				"ptype = ? AND v0 = ? AND v1 = ? AND v2 = ? AND v3 = ?",
				"p",
				roleID,
				target.accessType.String(),
				target.path,
				"GET",
			).Count(&count).Error; err != nil {
				t.Fatalf("count menu policy %s for %s: %v", target.path, roleName, err)
			}
			want := int64(0)
			if slices.Contains(menuDefaultRoles, roleName) {
				want = 1
			}
			if count != want {
				t.Fatalf("menu policy %s for %s = %d, want %d", target.path, roleName, count, want)
			}
		}
	}
	for _, seed := range supplierPermissionSeeds {
		for roleName, roleID := range roleIDs {
			var count int64
			if err := db.Model(&models.CasbinRule{}).Where(
				"ptype = ? AND v0 = ? AND v1 = ? AND v2 = ? AND v3 = ?",
				"p",
				roleID,
				adminpkg.ComponentAccessType.String(),
				seed.componentPath,
				"GET",
			).Count(&count).Error; err != nil {
				t.Fatalf("count component policy %s for %s: %v", seed.code, roleName, err)
			}
			want := int64(0)
			if slices.Contains(seed.defaultRoles, roleName) {
				want = 1
			}
			if count != want {
				t.Fatalf("component policy %s for %s = %d, want %d", seed.code, roleName, count, want)
			}
		}
	}

	matrix := []struct {
		role    string
		method  string
		path    string
		allowed bool
	}{
		{role: "admin", method: "POST", path: "/admin/api/suppliers", allowed: true},
		{role: "admin", method: "DELETE", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "admin", method: "GET", path: "/admin/api/suppliers/export", allowed: true},
		{role: "admin", method: "GET", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "admin", method: "GET", path: "/admin/api/suppliers", allowed: true},
		{role: "admin", method: "PUT", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "finance", method: "POST", path: "/admin/api/suppliers", allowed: false},
		{role: "finance", method: "DELETE", path: "/admin/api/suppliers/:id", allowed: false},
		{role: "finance", method: "GET", path: "/admin/api/suppliers/export", allowed: true},
		{role: "finance", method: "GET", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "finance", method: "GET", path: "/admin/api/suppliers", allowed: true},
		{role: "finance", method: "PUT", path: "/admin/api/suppliers/:id", allowed: false},
		{role: "procurement", method: "POST", path: "/admin/api/suppliers", allowed: true},
		{role: "procurement", method: "DELETE", path: "/admin/api/suppliers/:id", allowed: false},
		{role: "procurement", method: "GET", path: "/admin/api/suppliers/export", allowed: true},
		{role: "procurement", method: "GET", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "procurement", method: "GET", path: "/admin/api/suppliers", allowed: true},
		{role: "procurement", method: "PUT", path: "/admin/api/suppliers/:id", allowed: true},
	}
	for _, expected := range matrix {
		var count int64
		if err := db.Model(&models.CasbinRule{}).Where(
			"ptype = ? AND v0 = ? AND v1 = ? AND v2 = ? AND v3 = ?",
			"p",
			roleIDs[expected.role],
			adminpkg.APIAccessType.String(),
			expected.path,
			expected.method,
		).Count(&count).Error; err != nil {
			t.Fatalf("count API policy %s %s for %s: %v", expected.method, expected.path, expected.role, err)
		}
		want := int64(0)
		if expected.allowed {
			want = 1
		}
		if count != want {
			t.Fatalf("API policy %s %s for %s = %d, want %d", expected.method, expected.path, expected.role, count, want)
		}
	}

	var revisions []models.ConfigRevision
	if err := db.Where("resource = ?", supplierAuthorizationResource).
		Order("scope, owner_id").
		Find(&revisions).Error; err != nil {
		t.Fatalf("load authorization revisions: %v", err)
	}
	if got, want := len(revisions), 3+1; got != want {
		t.Fatalf("authorization revisions = %d, want %d", got, want)
	}
	for _, revision := range revisions {
		if revision.Revision != 1 {
			t.Fatalf("authorization revision %#v, want revision 1", revision)
		}
	}
}

func TestSupplierAuthorizationMigrationFailureRollsBackAllProjectedTruth(t *testing.T) {
	db := openSupplierAuthorizationTestDatabase(t)
	injected := errors.New("injected authorization seed failure")
	err := applySupplierAuthorizationMigration(
		db,
		SupplierAuthorizationMigrationID.String(),
		func() error { return injected },
	)
	if !errors.Is(err, injected) {
		t.Fatalf("authorization migration error = %v, want injected failure", err)
	}

	for name, model := range map[string]any{
		"roles":     &models.Role{},
		"menus":     &models.Menu{},
		"policies":  &models.CasbinRule{},
		"revisions": &models.ConfigRevision{},
		"versions":  &migrationmodels.Migration{},
	} {
		var count int64
		if err := db.Model(model).Count(&count).Error; err != nil {
			t.Fatalf("count %s after rollback: %v", name, err)
		}
		if count != 0 {
			t.Fatalf("%s after rollback = %d, want zero", name, count)
		}
	}
}

func openSupplierAuthorizationTestDatabase(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(filepath.Join(t.TempDir(), "authorization.db")), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open authorization database: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("authorization database handle: %v", err)
	}
	t.Cleanup(func() { _ = sqlDB.Close() })
	prepareSupplierAuthorizationTestSchema(t, db)
	if err := db.AutoMigrate(
		&migrationmodels.Migration{},
	); err != nil {
		t.Fatalf("create authorization migration schema: %v", err)
	}
	return db
}

func prepareSupplierAuthorizationTestSchema(t *testing.T, db *gorm.DB) {
	t.Helper()
	if err := db.AutoMigrate(
		&models.Role{},
		&models.Menu{},
		&models.CasbinRule{},
		&models.ConfigRevision{},
	); err != nil {
		t.Fatalf("create authorization schema: %v", err)
	}
}
