// Code generated by mss module template 1.2.0-backend.4 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/mss-boot-io/mss-boot-admin/admin/models"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/security"
)

const supplierTestPrincipalKey = "supplier.test.principal"

func TestSupplierAdminAuthorizerPermissionMatrix(t *testing.T) {
	gin.SetMode(gin.TestMode)
	db := openSupplierAuthorizationTestDatabase(t)
	if err := applySupplierAuthorizationMigration(
		db,
		SupplierAuthorizationMigrationID.String(),
		nil,
	); err != nil {
		t.Fatalf("apply authorization migration: %v", err)
	}

	principals := make(map[string]security.Verifier, 3+1)
	for _, roleName := range []string{"admin", "finance", "procurement"} {
		var role models.Role
		if err := db.Where("name = ?", roleName).Take(&role).Error; err != nil {
			t.Fatalf("load role %s: %v", roleName, err)
		}
		roleCopy := role
		principals[roleName] = &models.User{UserLogin: models.UserLogin{
			RoleID: role.ID,
			Role:   &roleCopy,
		}}
	}
	principals["root"] = &models.User{UserLogin: models.UserLogin{
		RoleID: "root-without-persisted-policy",
		Role:   &models.Role{Root: true},
	}}

	resolver := func(ctx *gin.Context) security.Verifier {
		value, exists := ctx.Get(supplierTestPrincipalKey)
		if !exists {
			return nil
		}
		principal, _ := value.(security.Verifier)
		return principal
	}
	authorizer, err := NewAdminAuthorizer(db, resolver)
	if err != nil {
		t.Fatalf("NewAdminAuthorizer() error = %v", err)
	}
	router := gin.New()
	router.Use(func(ctx *gin.Context) {
		switch roleName := ctx.GetHeader("X-Test-Role"); roleName {
		case "unauthenticated":
			ctx.Set(supplierTestPrincipalKey, "not-a-principal")
		case "":
		default:
			ctx.Set(supplierTestPrincipalKey, principals[roleName])
		}
		ctx.Next()
	})
	router.Handle("POST", "/admin/api/suppliers", func(ctx *gin.Context) {
		err := authorizer.Authorize(ctx, PermissionCreate)
		switch {
		case err == nil:
			ctx.Status(http.StatusNoContent)
		case errors.Is(err, ErrSupplierAuthenticationRequired):
			ctx.Status(http.StatusUnauthorized)
		default:
			ctx.Status(http.StatusForbidden)
		}
	})
	router.Handle("DELETE", "/admin/api/suppliers/:id", func(ctx *gin.Context) {
		err := authorizer.Authorize(ctx, PermissionDelete)
		switch {
		case err == nil:
			ctx.Status(http.StatusNoContent)
		case errors.Is(err, ErrSupplierAuthenticationRequired):
			ctx.Status(http.StatusUnauthorized)
		default:
			ctx.Status(http.StatusForbidden)
		}
	})
	router.Handle("GET", "/admin/api/suppliers/export", func(ctx *gin.Context) {
		err := authorizer.Authorize(ctx, PermissionExport)
		switch {
		case err == nil:
			ctx.Status(http.StatusNoContent)
		case errors.Is(err, ErrSupplierAuthenticationRequired):
			ctx.Status(http.StatusUnauthorized)
		default:
			ctx.Status(http.StatusForbidden)
		}
	})
	router.Handle("GET", "/admin/api/suppliers/:id", func(ctx *gin.Context) {
		err := authorizer.Authorize(ctx, PermissionRead)
		switch {
		case err == nil:
			ctx.Status(http.StatusNoContent)
		case errors.Is(err, ErrSupplierAuthenticationRequired):
			ctx.Status(http.StatusUnauthorized)
		default:
			ctx.Status(http.StatusForbidden)
		}
	})
	router.Handle("GET", "/admin/api/suppliers", func(ctx *gin.Context) {
		err := authorizer.Authorize(ctx, PermissionList)
		switch {
		case err == nil:
			ctx.Status(http.StatusNoContent)
		case errors.Is(err, ErrSupplierAuthenticationRequired):
			ctx.Status(http.StatusUnauthorized)
		default:
			ctx.Status(http.StatusForbidden)
		}
	})
	router.Handle("PUT", "/admin/api/suppliers/:id", func(ctx *gin.Context) {
		err := authorizer.Authorize(ctx, PermissionUpdate)
		switch {
		case err == nil:
			ctx.Status(http.StatusNoContent)
		case errors.Is(err, ErrSupplierAuthenticationRequired):
			ctx.Status(http.StatusUnauthorized)
		default:
			ctx.Status(http.StatusForbidden)
		}
	})

	matrix := []struct {
		role      string
		operation string
		method    string
		path      string
		allowed   bool
	}{
		{role: "admin", operation: "create", method: "POST", path: "/admin/api/suppliers", allowed: true},
		{role: "admin", operation: "delete", method: "DELETE", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "admin", operation: "export", method: "GET", path: "/admin/api/suppliers/export", allowed: true},
		{role: "admin", operation: "get", method: "GET", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "admin", operation: "list", method: "GET", path: "/admin/api/suppliers", allowed: true},
		{role: "admin", operation: "update", method: "PUT", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "finance", operation: "create", method: "POST", path: "/admin/api/suppliers", allowed: false},
		{role: "finance", operation: "delete", method: "DELETE", path: "/admin/api/suppliers/:id", allowed: false},
		{role: "finance", operation: "export", method: "GET", path: "/admin/api/suppliers/export", allowed: true},
		{role: "finance", operation: "get", method: "GET", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "finance", operation: "list", method: "GET", path: "/admin/api/suppliers", allowed: true},
		{role: "finance", operation: "update", method: "PUT", path: "/admin/api/suppliers/:id", allowed: false},
		{role: "procurement", operation: "create", method: "POST", path: "/admin/api/suppliers", allowed: true},
		{role: "procurement", operation: "delete", method: "DELETE", path: "/admin/api/suppliers/:id", allowed: false},
		{role: "procurement", operation: "export", method: "GET", path: "/admin/api/suppliers/export", allowed: true},
		{role: "procurement", operation: "get", method: "GET", path: "/admin/api/suppliers/:id", allowed: true},
		{role: "procurement", operation: "list", method: "GET", path: "/admin/api/suppliers", allowed: true},
		{role: "procurement", operation: "update", method: "PUT", path: "/admin/api/suppliers/:id", allowed: true},
	}
	for _, test := range matrix {
		t.Run(test.role+"/"+test.operation, func(t *testing.T) {
			requestPath := strings.ReplaceAll(test.path, ":id", "record-id")
			request := httptest.NewRequest(test.method, requestPath, nil)
			request.Header.Set("X-Test-Role", test.role)
			response := httptest.NewRecorder()
			router.ServeHTTP(response, request)
			want := http.StatusForbidden
			if test.allowed {
				want = http.StatusNoContent
			}
			if response.Code != want {
				t.Fatalf("%s %s for %s = %d, want %d", test.method, requestPath, test.role, response.Code, want)
			}
		})
	}

	for _, roleHeader := range []string{"", "unauthenticated"} {
		name := "missing-context"
		if roleHeader != "" {
			name = roleHeader
		}
		t.Run(name, func(t *testing.T) {
			request := httptest.NewRequest("POST", strings.ReplaceAll("/admin/api/suppliers", ":id", "record-id"), nil)
			if roleHeader != "" {
				request.Header.Set("X-Test-Role", roleHeader)
			}
			response := httptest.NewRecorder()
			router.ServeHTTP(response, request)
			if response.Code != http.StatusUnauthorized {
				t.Fatalf("unauthenticated response = %d, want %d", response.Code, http.StatusUnauthorized)
			}
		})
	}

	t.Run("root-bypass-follows-spec", func(t *testing.T) {
		request := httptest.NewRequest("POST", strings.ReplaceAll("/admin/api/suppliers", ":id", "record-id"), nil)
		request.Header.Set("X-Test-Role", "root")
		response := httptest.NewRecorder()
		router.ServeHTTP(response, request)
		want := http.StatusForbidden
		want = http.StatusNoContent
		if response.Code != want {
			t.Fatalf("root-bypass response = %d, want %d", response.Code, want)
		}
	})
}

func TestSupplierAdminAuthorizerRequiresExplicitComposition(t *testing.T) {
	if _, err := NewAdminAuthorizer(nil, func(*gin.Context) security.Verifier { return nil }); err == nil {
		t.Fatal("NewAdminAuthorizer(nil database) unexpectedly succeeded")
	}
	db := openSupplierAuthorizationTestDatabase(t)
	if _, err := NewAdminAuthorizer(db, nil); err == nil {
		t.Fatal("NewAdminAuthorizer(nil resolver) unexpectedly succeeded")
	}
}
