// Code generated by mss module template 1.3.0-backend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"errors"
	"fmt"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/mss-boot-io/mss-boot-admin/admin/models"
	adminpkg "github.com/mss-boot-io/mss-boot-admin/admin/pkg"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/security"
	"gorm.io/gorm"
)

var (
	ErrSupplierAuthenticationRequired   = errors.New("supplier authentication required")
	ErrSupplierAuthorizationDenied      = errors.New("supplier authorization denied")
	ErrSupplierAuthorizationUnavailable = errors.New("supplier authorization unavailable")
)

// AdminPrincipalResolver reads the canonical identity installed by the Admin
// authentication middleware. Composition roots normally pass middleware.GetVerify.
type AdminPrincipalResolver func(*gin.Context) security.Verifier

// AdminAuthorizer adapts the generated permission contract to the Admin
// database-backed Casbin policy. It does not mount routes or infer middleware.
type AdminAuthorizer struct {
	db        *gorm.DB
	principal AdminPrincipalResolver
}

// NewAdminAuthorizer requires both the authoritative Admin database and an
// explicit request-principal resolver.
func NewAdminAuthorizer(db *gorm.DB, principal AdminPrincipalResolver) (*AdminAuthorizer, error) {
	if db == nil {
		return nil, errors.New("supplier authorization database is required")
	}
	if principal == nil {
		return nil, errors.New("supplier principal resolver is required")
	}
	return &AdminAuthorizer{db: db, principal: principal}, nil
}

type supplierAuthorizationRoute struct {
	method string
	path   string
}

var supplierAuthorizationRoutes = map[string]supplierAuthorizationRoute{
	PermissionCreate: {method: "POST", path: "/admin/api/suppliers"},
	PermissionDelete: {method: "DELETE", path: "/admin/api/suppliers/:id"},
	PermissionExport: {method: "GET", path: "/admin/api/suppliers/export"},
	PermissionRead:   {method: "GET", path: "/admin/api/suppliers/:id"},
	PermissionList:   {method: "GET", path: "/admin/api/suppliers"},
	PermissionUpdate: {method: "PUT", path: "/admin/api/suppliers/:id"},
}

// Authorize validates the generated permission-to-route binding, requires an
// authenticated Admin principal, and then reads the canonical Casbin table.
// The ownership contract is none, so authorization never falls back to a row
// owner or request-supplied scope.
func (authorizer *AdminAuthorizer) Authorize(ctx *gin.Context, permission string) error {
	if authorizer == nil || authorizer.db == nil || authorizer.principal == nil {
		return ErrSupplierAuthorizationUnavailable
	}
	route, declared := supplierAuthorizationRoutes[permission]
	if !declared || ctx == nil || ctx.Request == nil {
		return ErrSupplierAuthorizationDenied
	}
	if ctx.Request.Method != route.method || ctx.FullPath() != route.path {
		return ErrSupplierAuthorizationDenied
	}
	principal := authorizer.principal(ctx)
	if nilInterface(principal) || strings.TrimSpace(principal.GetRoleID()) == "" {
		return ErrSupplierAuthenticationRequired
	}
	if principal.Root() {
		return nil
	}

	var count int64
	if err := authorizer.db.WithContext(ctx.Request.Context()).Model(&models.CasbinRule{}).Where(
		"ptype = ? AND v0 = ? AND v1 = ? AND v2 = ? AND v3 = ?",
		"p",
		principal.GetRoleID(),
		adminpkg.APIAccessType.String(),
		route.path,
		route.method,
	).Count(&count).Error; err != nil {
		return fmt.Errorf("%w: read Admin policy", ErrSupplierAuthorizationUnavailable)
	}
	if count == 0 {
		return ErrSupplierAuthorizationDenied
	}
	return nil
}
