// Code generated by mss module template 1.1.0-backend.2 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	moduleruntime "github.com/mss-boot-io/mss-boot-admin/admin/modules/runtime"
)

func init() {
	moduleruntime.MustRegister(moduleruntime.Descriptor{
		Name:        "supplier",
		DisplayName: "供应商管理",
		Description: "管理供应商基础信息、信用等级、联系人和启用状态。",
		Version:     "v1alpha1",
		Model:       new(Supplier),
	})
}
