// Code generated by mss module template 1.1.0-backend.3 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	moduleruntime "github.com/mss-boot-io/mss-boot-admin/admin/modules/runtime"
)

func init() {
	moduleruntime.MustRegister(moduleruntime.Descriptor{
		Name:        "supplier",
		DisplayName: "供应商管理",
		Description: "管理供应商基础信息、信用等级、联系人和启用状态。",
		Version:     "v1alpha1",
		Model:       new(Supplier),
		Permissions: []moduleruntime.Permission{
			{
				Code:         "supplier:create",
				DisplayName:  "创建供应商",
				Description:  "",
				DefaultRoles: []string{"admin", "procurement"},
			},
			{
				Code:         "supplier:delete",
				DisplayName:  "删除供应商",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "supplier:export",
				DisplayName:  "导出供应商",
				Description:  "",
				DefaultRoles: []string{"admin", "finance", "procurement"},
			},
			{
				Code:         "supplier:list",
				DisplayName:  "查看供应商列表",
				Description:  "",
				DefaultRoles: []string{"admin", "finance", "procurement"},
			},
			{
				Code:         "supplier:read",
				DisplayName:  "查看供应商详情",
				Description:  "",
				DefaultRoles: []string{"admin", "finance", "procurement"},
			},
			{
				Code:         "supplier:update",
				DisplayName:  "编辑供应商",
				Description:  "",
				DefaultRoles: []string{"admin", "procurement"},
			},
		},
		Menu: moduleruntime.Menu{
			Path:          "/suppliers",
			DisplayName:   "供应商管理",
			DisplayNameEn: "Suppliers",
			Icon:          "shop",
			Parent:        "/procurement",
			Order:         20,
			Hidden:        false,
		},
	})
}
