// Code generated by mss module template 1.3.0-backend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"fmt"
	"net/mail"
	"regexp"
	"strings"
	"unicode/utf8"
)

// ValidationError is a value-redacted, field-specific input failure.
type ValidationError struct {
	Field string `json:"field"`
	Rule  string `json:"rule"`
}

func (e *ValidationError) Error() string {
	return fmt.Sprintf("invalid %s: %s", e.Field, e.Rule)
}

// CreateSupplierInput is the authoritative create contract.
type CreateSupplierInput struct {
	Code         string `json:"code"`
	Name         string `json:"name"`
	Country      string `json:"country"`
	ContactName  string `json:"contactName"`
	ContactEmail string `json:"contactEmail"`
	CreditLevel  string `json:"creditLevel"`
	Enabled      *bool  `json:"enabled"`
}

// UpdateSupplierInput is a presence-aware partial update contract.
type UpdateSupplierInput struct {
	Code         *string `json:"code"`
	Name         *string `json:"name"`
	Country      *string `json:"country"`
	ContactName  *string `json:"contactName"`
	ContactEmail *string `json:"contactEmail"`
	CreditLevel  *string `json:"creditLevel"`
	Enabled      *bool   `json:"enabled"`
}

// ListSupplierQuery defines bounded filtering, searching, sorting, and paging.
type ListSupplierQuery struct {
	Q           string `form:"q" query:"q"`
	Current     int    `form:"current" query:"current"`
	PageSize    int    `form:"pageSize" query:"pageSize"`
	SortBy      string `form:"sortBy" query:"sortBy"`
	SortOrder   string `form:"sortOrder" query:"sortOrder"`
	Country     string `form:"country" query:"country"`
	CreditLevel string `form:"creditLevel" query:"creditLevel"`
	Enabled     *bool  `form:"enabled" query:"enabled"`
}

// SupplierPage is the stable list response contract.
type SupplierPage struct {
	Data     []Supplier `json:"data"`
	Total    int64      `json:"total"`
	Current  int        `json:"current"`
	PageSize int        `json:"pageSize"`
}

func (input *CreateSupplierInput) normalizeAndValidate() error {
	if input == nil {
		return &ValidationError{Field: "body", Rule: "required"}
	}
	input.Code = strings.TrimSpace(input.Code)
	if err := validateCode(input.Code, true); err != nil {
		return err
	}
	input.Name = strings.TrimSpace(input.Name)
	if err := validateName(input.Name, true); err != nil {
		return err
	}
	input.Country = strings.TrimSpace(input.Country)
	if err := validateCountry(input.Country, false); err != nil {
		return err
	}
	input.ContactName = strings.TrimSpace(input.ContactName)
	if err := validateContactName(input.ContactName, true); err != nil {
		return err
	}
	input.ContactEmail = strings.TrimSpace(input.ContactEmail)
	if err := validateContactEmail(input.ContactEmail, false); err != nil {
		return err
	}
	input.CreditLevel = strings.TrimSpace(input.CreditLevel)
	if input.CreditLevel == "" {
		input.CreditLevel = "normal"
	}
	if err := validateCreditLevel(input.CreditLevel, true); err != nil {
		return err
	}
	if input.Enabled == nil {
		value := true
		input.Enabled = &value
	}
	if input.Enabled == nil {
		return &ValidationError{Field: "enabled", Rule: "required"}
	}
	return nil
}

func (input *UpdateSupplierInput) normalizeAndValidate() error {
	if input == nil {
		return &ValidationError{Field: "body", Rule: "required"}
	}
	changed := false
	if input.Code != nil {
		changed = true
		normalized := strings.TrimSpace(*input.Code)
		input.Code = &normalized
		if err := validateCode(normalized, true); err != nil {
			return err
		}
	}
	if input.Name != nil {
		changed = true
		normalized := strings.TrimSpace(*input.Name)
		input.Name = &normalized
		if err := validateName(normalized, true); err != nil {
			return err
		}
	}
	if input.Country != nil {
		changed = true
		normalized := strings.TrimSpace(*input.Country)
		input.Country = &normalized
		if err := validateCountry(normalized, false); err != nil {
			return err
		}
	}
	if input.ContactName != nil {
		changed = true
		normalized := strings.TrimSpace(*input.ContactName)
		input.ContactName = &normalized
		if err := validateContactName(normalized, true); err != nil {
			return err
		}
	}
	if input.ContactEmail != nil {
		changed = true
		normalized := strings.TrimSpace(*input.ContactEmail)
		input.ContactEmail = &normalized
		if err := validateContactEmail(normalized, false); err != nil {
			return err
		}
	}
	if input.CreditLevel != nil {
		changed = true
		normalized := strings.TrimSpace(*input.CreditLevel)
		input.CreditLevel = &normalized
		if err := validateCreditLevel(normalized, true); err != nil {
			return err
		}
	}
	if input.Enabled != nil {
		changed = true
	}
	if !changed {
		return &ValidationError{Field: "body", Rule: "at-least-one-field"}
	}
	return nil
}

func (query *ListSupplierQuery) normalizeAndValidate() error {
	if query == nil {
		return &ValidationError{Field: "query", Rule: "required"}
	}
	query.Q = strings.TrimSpace(query.Q)
	if query.Current <= 0 {
		query.Current = 1
	}
	if query.PageSize <= 0 {
		query.PageSize = 20
	}
	if query.PageSize > 100 {
		return &ValidationError{Field: "pageSize", Rule: "maximum-100"}
	}
	if query.SortOrder == "" {
		query.SortOrder = "asc"
	}
	if query.SortOrder != "asc" && query.SortOrder != "desc" {
		return &ValidationError{Field: "sortOrder", Rule: "asc-or-desc"}
	}
	if query.SortBy != "" {
		switch query.SortBy {
		case "code":
		case "name":
		default:
			return &ValidationError{Field: "sortBy", Rule: "unsupported"}
		}
	}
	query.Country = strings.TrimSpace(query.Country)
	query.CreditLevel = strings.TrimSpace(query.CreditLevel)
	if query.CreditLevel != "" {
		if err := validateCreditLevel(query.CreditLevel, false); err != nil {
			return err
		}
	}
	return nil
}

var codePattern = regexp.MustCompile("^[A-Z0-9_-]+$")

func validateCode(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "code", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) < 2 {
		return &ValidationError{Field: "code", Rule: "minimum-length-2"}
	}
	if utf8.RuneCountInString(value) > 64 {
		return &ValidationError{Field: "code", Rule: "maximum-length-64"}
	}
	if !codePattern.MatchString(value) {
		return &ValidationError{Field: "code", Rule: "pattern"}
	}
	return nil
}

func validateName(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "name", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) < 2 {
		return &ValidationError{Field: "name", Rule: "minimum-length-2"}
	}
	if utf8.RuneCountInString(value) > 200 {
		return &ValidationError{Field: "name", Rule: "maximum-length-200"}
	}
	return nil
}

func validateCountry(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "country", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) > 100 {
		return &ValidationError{Field: "country", Rule: "maximum-length-100"}
	}
	return nil
}

func validateContactName(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "contactName", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) > 100 {
		return &ValidationError{Field: "contactName", Rule: "maximum-length-100"}
	}
	return nil
}

func validateContactEmail(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "contactEmail", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) > 254 {
		return &ValidationError{Field: "contactEmail", Rule: "maximum-length-254"}
	}
	parsed, err := mail.ParseAddress(value)
	if err != nil || parsed.Address != value {
		return &ValidationError{Field: "contactEmail", Rule: "email"}
	}
	return nil
}

func validateCreditLevel(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "creditLevel", Rule: "required"}
		}
		return nil
	}
	switch value {
	case "preferred":
	case "normal":
	case "restricted":
	case "blocked":
	default:
		return &ValidationError{Field: "creditLevel", Rule: "enum"}
	}
	return nil
}
