// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"context"
	"time"
)

// DomainEvent is the narrow typed event boundary for this module checkpoint.
// It is intentionally not coupled to the v1.1 EventBus work.
type DomainEvent interface {
	EventName() string
}

// EventCollector receives typed events after the database transaction commits.
type EventCollector interface {
	Collect(context.Context, DomainEvent)
}

type discardEventCollector struct{}

func (discardEventCollector) Collect(context.Context, DomainEvent) {}

// SupplierCreatedEvent is emitted for procurement.supplier.created.
type SupplierCreatedEvent struct {
	ResourceID string    `json:"resourceID"`
	OccurredAt time.Time `json:"occurredAt"`
}

func (SupplierCreatedEvent) EventName() string { return "procurement.supplier.created" }

// SupplierUpdatedEvent is emitted for procurement.supplier.updated.
type SupplierUpdatedEvent struct {
	ResourceID    string    `json:"resourceID"`
	ChangedFields []string  `json:"changedFields"`
	OccurredAt    time.Time `json:"occurredAt"`
}

func (SupplierUpdatedEvent) EventName() string { return "procurement.supplier.updated" }
