// Code generated by mss module template 1.2.0-backend.4 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"github.com/glebarez/sqlite"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func TestSupplierForwardMigrationFreshRepeatAndConstraints(t *testing.T) {
	db := openUnmigratedSupplierDatabase(t)
	runner := configuredSupplierMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("fresh migration error = %v", err)
	}
	assertSupplierSchemaReady(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("repeat migration error = %v", err)
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", SupplierMigrationID.String()).Count(&versions).Error; err != nil {
		t.Fatalf("count migration versions: %v", err)
	}
	if versions != 1 {
		t.Fatalf("migration version rows = %d, want 1", versions)
	}
	invalidCreditLevel := &Supplier{
		Code:         "VALUE_01",
		Name:         "VALUE_01",
		Country:      "VALUE_01",
		ContactName:  "VALUE_01",
		ContactEmail: "supplier@example.test",
		CreditLevel:  "outside-contract",
		Enabled:      true,
	}
	if err := db.Create(invalidCreditLevel).Error; err == nil {
		t.Fatal("database enum constraint accepted an undeclared value")
	}
}

func TestSupplierForwardMigrationPreservesUpgradeData(t *testing.T) {
	db := openUnmigratedSupplierDatabase(t)
	if err := db.Exec("CREATE TABLE legacy_records (id TEXT PRIMARY KEY, value TEXT NOT NULL)").Error; err != nil {
		t.Fatalf("create legacy table: %v", err)
	}
	if err := db.Exec("INSERT INTO legacy_records (id, value) VALUES (?, ?)", "legacy-1", "preserve-me").Error; err != nil {
		t.Fatalf("insert legacy row: %v", err)
	}
	runner := configuredSupplierMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("upgrade migration error = %v", err)
	}
	var value string
	if err := db.Raw("SELECT value FROM legacy_records WHERE id = ?", "legacy-1").Scan(&value).Error; err != nil {
		t.Fatalf("read legacy row: %v", err)
	}
	if value != "preserve-me" {
		t.Fatalf("legacy value = %q", value)
	}
	assertSupplierSchemaReady(t, db)
}

func TestSupplierForwardMigrationRecoversAfterInterruptionWithoutPartialTruth(t *testing.T) {
	db := openUnmigratedSupplierDatabase(t)
	injected := errors.New("injected interruption")
	err := applySupplierMigration(db, SupplierMigrationID.String(), func() error { return injected })
	if !errors.Is(err, injected) {
		t.Fatalf("interrupted migration error = %v", err)
	}
	if !db.Migrator().HasTable(new(Supplier)) {
		t.Fatal("interrupted migration did not reach the table checkpoint")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", SupplierMigrationID.String()).Count(&versions).Error; err != nil {
		t.Fatalf("count interrupted version rows: %v", err)
	}
	if versions != 0 {
		t.Fatalf("interrupted migration recorded completion: %d", versions)
	}
	runner := configuredSupplierMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("recovery migration error = %v", err)
	}
	assertSupplierSchemaReady(t, db)
}

func TestSupplierForwardMigrationRejectsExistingColumnShapeDriftWithoutVersionTruth(t *testing.T) {
	db := openUnmigratedSupplierDatabase(t)
	driftedDDL, ok := driftSupplierSQLiteColumnType(createSupplierTableDDL["sqlite"])
	if !ok {
		t.Fatal("test contract could not select a business column to corrupt")
	}
	if err := db.Exec(driftedDDL).Error; err != nil {
		t.Fatalf("create drifted table: %v", err)
	}
	runner := configuredSupplierMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err == nil {
		t.Fatal("migration accepted an incompatible existing column shape")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", SupplierMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("drifted migration version count = %d, err=%v", versions, err)
	}
}

func TestSupplierForwardMigrationRejectsNullableRequiredColumnsWithoutVersionTruth(t *testing.T) {
	t.Run("code", func(t *testing.T) {
		db := openUnmigratedSupplierDatabase(t)
		driftedDDL, ok := driftSupplierSQLiteRequiredColumnNullable(createSupplierTableDDL["sqlite"], "code")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertSupplierMigrationVersionAbsent(t, db)
	})
	t.Run("name", func(t *testing.T) {
		db := openUnmigratedSupplierDatabase(t)
		driftedDDL, ok := driftSupplierSQLiteRequiredColumnNullable(createSupplierTableDDL["sqlite"], "name")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertSupplierMigrationVersionAbsent(t, db)
	})
	t.Run("contact_name", func(t *testing.T) {
		db := openUnmigratedSupplierDatabase(t)
		driftedDDL, ok := driftSupplierSQLiteRequiredColumnNullable(createSupplierTableDDL["sqlite"], "contact_name")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertSupplierMigrationVersionAbsent(t, db)
	})
	t.Run("credit_level", func(t *testing.T) {
		db := openUnmigratedSupplierDatabase(t)
		driftedDDL, ok := driftSupplierSQLiteRequiredColumnNullable(createSupplierTableDDL["sqlite"], "credit_level")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertSupplierMigrationVersionAbsent(t, db)
	})
	t.Run("enabled", func(t *testing.T) {
		db := openUnmigratedSupplierDatabase(t)
		driftedDDL, ok := driftSupplierSQLiteRequiredColumnNullable(createSupplierTableDDL["sqlite"], "enabled")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertSupplierMigrationVersionAbsent(t, db)
	})
}

func TestSupplierForwardMigrationRejectsIndexShapeDriftWithoutVersionTruth(t *testing.T) {
	for _, test := range []struct {
		name       string
		wrongIndex func(supplierMigrationIndex) string
	}{
		{
			name: "columns",
			wrongIndex: func(index supplierMigrationIndex) string {
				keyword := ""
				if index.unique {
					keyword = "UNIQUE "
				}
				return "CREATE " + keyword + "INDEX \"" + index.name + "\" ON \"biz_suppliers\" (\"id\")"
			},
		},
		{
			name: "uniqueness",
			wrongIndex: func(index supplierMigrationIndex) string {
				keyword := "UNIQUE "
				if index.unique {
					keyword = ""
				}
				columns := "\"" + strings.Join(index.columns, "\", \"") + "\""
				return "CREATE " + keyword + "INDEX \"" + index.name + "\" ON \"biz_suppliers\" (" + columns + ")"
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			db := openUnmigratedSupplierDatabase(t)
			if err := db.Exec(createSupplierTableDDL["sqlite"]).Error; err != nil {
				t.Fatalf("create table: %v", err)
			}
			if len(supplierMigrationIndexes) == 0 {
				t.Fatal("test contract requires an index")
			}
			if err := db.Exec(test.wrongIndex(supplierMigrationIndexes[0])).Error; err != nil {
				t.Fatalf("create wrong-shape index: %v", err)
			}
			runner := configuredSupplierMigrationRunner(t, db)
			if err := runner.MigrateContext(context.Background()); err == nil {
				t.Fatal("migration accepted an incompatible same-name index")
			}
			assertSupplierMigrationVersionAbsent(t, db)
		})
	}
}

func TestSupplierGeneratedMigrationDuplicateRegistrationFailsPreflightWithoutDatabase(t *testing.T) {
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("first RegisterMigration() error = %v", err)
	}
	if err := RegisterMigration(runner); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("duplicate RegisterMigration() error = %v", err)
	}
	if err := runner.ValidateRegistrations(); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("ValidateRegistrations() error = %v, want duplicate ID", err)
	}
	if runner.GetDb() != nil {
		t.Fatal("registration preflight unexpectedly required a database")
	}
}

func TestSupplierForwardMigrationRejectsExistingCheckBodyDriftWithoutVersionTruth(t *testing.T) {
	db := openUnmigratedSupplierDatabase(t)
	originalValue := "'" + "preferred" + "'"
	driftedDDL := strings.Replace(createSupplierTableDDL["sqlite"], originalValue, "'contract-drift'", 1)
	if driftedDDL == createSupplierTableDDL["sqlite"] {
		t.Fatal("test contract could not corrupt the check body")
	}
	if err := db.Exec(driftedDDL).Error; err != nil {
		t.Fatalf("create check-drifted table: %v", err)
	}
	runner := configuredSupplierMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err == nil {
		t.Fatal("migration accepted an incompatible existing check body")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", SupplierMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("check-drifted migration version count = %d, err=%v", versions, err)
	}
}

func driftSupplierSQLiteColumnType(ddl string) (string, bool) {
	for _, column := range supplierMigrationColumns[4:] {
		var declaredType string
		if column.length > 0 {
			declaredType = fmt.Sprintf("VARCHAR(%d)", column.length)
		} else {
			declaredType = "BOOLEAN"
		}
		original := fmt.Sprintf("%q %s", column.name, declaredType)
		replacement := fmt.Sprintf("%q BLOB", column.name)
		if drifted := strings.Replace(ddl, original, replacement, 1); drifted != ddl {
			return drifted, true
		}
	}
	return ddl, false
}

func driftSupplierSQLiteRequiredColumnNullable(ddl, column string) (string, bool) {
	token := fmt.Sprintf("%q", column)
	for _, line := range strings.SplitAfter(ddl, "\n") {
		if !strings.Contains(line, token) || !strings.Contains(line, " NOT NULL") {
			continue
		}
		driftedLine := strings.Replace(line, " NOT NULL", "", 1)
		return strings.Replace(ddl, line, driftedLine, 1), true
	}
	return ddl, false
}

func assertSupplierMigrationVersionAbsent(t *testing.T, db *gorm.DB) {
	t.Helper()
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", SupplierMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("drifted migration version count = %d, err=%v", versions, err)
	}
}

func openUnmigratedSupplierDatabase(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(filepath.Join(t.TempDir(), "migration.db")), &gorm.Config{
		TranslateError: false,
		Logger:         logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("database handle: %v", err)
	}
	t.Cleanup(func() { _ = sqlDB.Close() })
	if err := db.Exec("CREATE TABLE mss_boot_migration (version TEXT PRIMARY KEY, apply_time DATETIME NOT NULL)").Error; err != nil {
		t.Fatalf("create migration table: %v", err)
	}
	prepareSupplierAuthorizationTestSchema(t, db)
	return db
}

func configuredSupplierMigrationRunner(t *testing.T, db *gorm.DB) *migration.Migration {
	t.Helper()
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("RegisterMigration() error = %v", err)
	}
	if err := runner.ValidateRegistrations(); err != nil {
		t.Fatalf("ValidateRegistrations() error = %v", err)
	}
	runner.SetDb(db)
	runner.SetModel(new(migrationmodels.Migration))
	return runner
}

func assertSupplierSchemaReady(t *testing.T, db *gorm.DB) {
	t.Helper()
	if err := verifySupplierSchema(db); err != nil {
		t.Fatalf("schema readiness error = %v", err)
	}
	if !db.Migrator().HasIndex(new(Supplier), "idx_biz_suppliers_country_enabled") {
		t.Fatal("missing index idx_biz_suppliers_country_enabled")
	}
	if !db.Migrator().HasIndex(new(Supplier), "idx_biz_suppliers_deleted_at") {
		t.Fatal("missing index idx_biz_suppliers_deleted_at")
	}
	if !db.Migrator().HasIndex(new(Supplier), "idx_biz_suppliers_name") {
		t.Fatal("missing index idx_biz_suppliers_name")
	}
	if !db.Migrator().HasIndex(new(Supplier), "ux_biz_suppliers_code") {
		t.Fatal("missing index ux_biz_suppliers_code")
	}
}
