// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const SupplierMigrationID migration.MigrationID = "20260810160000"

var createSupplierTableDDL = map[string]string{
	"sqlite":   "CREATE TABLE IF NOT EXISTS \"biz_suppliers\" (\n  \"id\" VARCHAR(64) NOT NULL PRIMARY KEY,\n  \"created_at\" DATETIME NOT NULL,\n  \"updated_at\" DATETIME NOT NULL,\n  \"deleted_at\" DATETIME NULL,\n  \"code\" VARCHAR(64) NOT NULL,\n  \"name\" VARCHAR(200) NOT NULL,\n  \"country\" VARCHAR(100),\n  \"contact_name\" VARCHAR(100) NOT NULL,\n  \"contact_email\" VARCHAR(254),\n  \"credit_level\" VARCHAR(255) NOT NULL DEFAULT 'normal',\n  \"enabled\" BOOLEAN NOT NULL DEFAULT 1,\n  CONSTRAINT \"ck_biz_suppliers_credit_level\" CHECK (\"credit_level\" IN ('preferred', 'normal', 'restricted', 'blocked'))\n)",
	"postgres": "CREATE TABLE IF NOT EXISTS \"biz_suppliers\" (\n  \"id\" VARCHAR(64) NOT NULL PRIMARY KEY,\n  \"created_at\" TIMESTAMPTZ NOT NULL,\n  \"updated_at\" TIMESTAMPTZ NOT NULL,\n  \"deleted_at\" TIMESTAMPTZ NULL,\n  \"code\" VARCHAR(64) NOT NULL,\n  \"name\" VARCHAR(200) NOT NULL,\n  \"country\" VARCHAR(100),\n  \"contact_name\" VARCHAR(100) NOT NULL,\n  \"contact_email\" VARCHAR(254),\n  \"credit_level\" VARCHAR(255) NOT NULL DEFAULT 'normal',\n  \"enabled\" BOOLEAN NOT NULL DEFAULT TRUE,\n  CONSTRAINT \"ck_biz_suppliers_credit_level\" CHECK (\"credit_level\" IN ('preferred', 'normal', 'restricted', 'blocked'))\n)",
	"mysql":    "CREATE TABLE IF NOT EXISTS `biz_suppliers` (\n  `id` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,\n  `created_at` DATETIME(3) NOT NULL,\n  `updated_at` DATETIME(3) NOT NULL,\n  `deleted_at` DATETIME(3) NULL,\n  `code` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,\n  `name` VARCHAR(200) COLLATE utf8mb4_bin NOT NULL,\n  `country` VARCHAR(100) COLLATE utf8mb4_bin,\n  `contact_name` VARCHAR(100) COLLATE utf8mb4_bin NOT NULL,\n  `contact_email` VARCHAR(254) COLLATE utf8mb4_bin,\n  `credit_level` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL DEFAULT 'normal',\n  `enabled` BOOLEAN NOT NULL DEFAULT TRUE,\n  CONSTRAINT `ck_biz_suppliers_credit_level` CHECK (`credit_level` IN ('preferred', 'normal', 'restricted', 'blocked'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin",
}

type supplierMigrationColumn struct {
	name          string
	databaseTypes map[string]string
	nullable      bool
	primaryKey    bool
	length        int64
	hasDefault    bool
	defaultValue  string
}

var supplierMigrationColumns = []supplierMigrationColumn{
	{
		name: "id",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   true,
		length:       64,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "created_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "updated_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "deleted_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     true,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "code",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       64,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "name",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       200,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "country",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     true,
		primaryKey:   false,
		length:       100,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "contact_name",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       100,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "contact_email",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     true,
		primaryKey:   false,
		length:       254,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "credit_level",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       255,
		hasDefault:   true,
		defaultValue: "normal",
	},
	{
		name: "enabled",
		databaseTypes: map[string]string{
			"sqlite":   "boolean|bool",
			"postgres": "bool|boolean",
			"mysql":    "tinyint|boolean|bool",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   true,
		defaultValue: "true",
	},
}

type supplierMigrationIndex struct {
	name    string
	columns []string
	unique  bool
	ddl     map[string]string
}

var supplierMigrationIndexes = []supplierMigrationIndex{
	{
		name:    "idx_biz_suppliers_country_enabled",
		columns: []string{"country", "enabled"},
		unique:  false,
		ddl: map[string]string{
			"sqlite":   "CREATE INDEX IF NOT EXISTS \"idx_biz_suppliers_country_enabled\" ON \"biz_suppliers\" (\"country\", \"enabled\")",
			"postgres": "CREATE INDEX IF NOT EXISTS \"idx_biz_suppliers_country_enabled\" ON \"biz_suppliers\" (\"country\", \"enabled\")",
			"mysql":    "CREATE INDEX `idx_biz_suppliers_country_enabled` ON `biz_suppliers` (`country`, `enabled`)",
		},
	},
	{
		name:    "idx_biz_suppliers_deleted_at",
		columns: []string{"deleted_at"},
		unique:  false,
		ddl: map[string]string{
			"sqlite":   "CREATE INDEX IF NOT EXISTS \"idx_biz_suppliers_deleted_at\" ON \"biz_suppliers\" (\"deleted_at\")",
			"postgres": "CREATE INDEX IF NOT EXISTS \"idx_biz_suppliers_deleted_at\" ON \"biz_suppliers\" (\"deleted_at\")",
			"mysql":    "CREATE INDEX `idx_biz_suppliers_deleted_at` ON `biz_suppliers` (`deleted_at`)",
		},
	},
	{
		name:    "idx_biz_suppliers_name",
		columns: []string{"name"},
		unique:  false,
		ddl: map[string]string{
			"sqlite":   "CREATE INDEX IF NOT EXISTS \"idx_biz_suppliers_name\" ON \"biz_suppliers\" (\"name\")",
			"postgres": "CREATE INDEX IF NOT EXISTS \"idx_biz_suppliers_name\" ON \"biz_suppliers\" (\"name\")",
			"mysql":    "CREATE INDEX `idx_biz_suppliers_name` ON `biz_suppliers` (`name`)",
		},
	},
	{
		name:    "ux_biz_suppliers_code",
		columns: []string{"code"},
		unique:  true,
		ddl: map[string]string{
			"sqlite":   "CREATE UNIQUE INDEX IF NOT EXISTS \"ux_biz_suppliers_code\" ON \"biz_suppliers\" (\"code\")",
			"postgres": "CREATE UNIQUE INDEX IF NOT EXISTS \"ux_biz_suppliers_code\" ON \"biz_suppliers\" (\"code\")",
			"mysql":    "CREATE UNIQUE INDEX `ux_biz_suppliers_code` ON `biz_suppliers` (`code`)",
		},
	},
}

// RegisterMigration registers the complete lossless ID on an explicit runner.
func RegisterMigration(runner *migration.Migration) error {
	if runner == nil {
		return errors.New("supplier migration runner is required")
	}
	if err := runner.Register(SupplierMigrationID, migrateSupplier); err != nil {
		return err
	}
	return runner.Register(SupplierAuthorizationMigrationID, migrateSupplierAuthorization)
}

func migrateSupplier(db *gorm.DB, version string) error {
	return applySupplierMigration(db, version, nil)
}

// applySupplierMigration is an additive, forward-only migration. The
// hook exists solely for deterministic interruption recovery tests.
func applySupplierMigration(db *gorm.DB, version string, afterTable func() error) error {
	if db == nil {
		return errors.New("supplier migration database is required")
	}
	if version != SupplierMigrationID.String() {
		return errors.New("supplier migration version mismatch")
	}
	dialect := db.Dialector.Name()
	createDDL, supported := createSupplierTableDDL[dialect]
	if !supported {
		return fmt.Errorf("supplier migration: unsupported database dialect %q", dialect)
	}
	if !db.Migrator().HasTable(new(Supplier)) {
		if err := db.Exec(createDDL).Error; err != nil {
			return errors.New("supplier migration: create table failed")
		}
	}
	if afterTable != nil {
		if err := afterTable(); err != nil {
			return fmt.Errorf("supplier migration interrupted after table creation: %w", err)
		}
	}
	for _, databaseIndex := range supplierMigrationIndexes {
		if db.Migrator().HasIndex(new(Supplier), databaseIndex.name) {
			continue
		}
		if err := db.Exec(databaseIndex.ddl[dialect]).Error; err != nil {
			return errors.New("supplier migration: create index failed")
		}
	}
	if err := verifySupplierSchema(db); err != nil {
		return err
	}
	versionRow := &migrationmodels.Migration{}
	versionRow.SetVersion(version)
	if err := db.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "version"}},
		DoNothing: true,
	}).Create(versionRow).Error; err != nil {
		return errors.New("supplier migration: record version failed")
	}
	return nil
}

func verifySupplierSchema(db *gorm.DB) error {
	if !db.Migrator().HasTable(new(Supplier)) {
		return errors.New("supplier migration: table readiness failed")
	}
	columnTypes, err := db.Migrator().ColumnTypes(new(Supplier))
	if err != nil {
		return errors.New("supplier migration: column shape readiness failed")
	}
	columnsByName := make(map[string]gorm.ColumnType, len(columnTypes))
	for _, columnType := range columnTypes {
		columnsByName[columnType.Name()] = columnType
	}
	dialect := db.Dialector.Name()
	for _, expected := range supplierMigrationColumns {
		actual, ok := columnsByName[expected.name]
		if !ok || !migrationDatabaseTypeAllowed(expected.databaseTypes[dialect], actual.DatabaseTypeName()) {
			return errors.New("supplier migration: column shape readiness failed")
		}
		nullable, nullableKnown := actual.Nullable()
		if !nullableKnown || nullable != expected.nullable {
			return errors.New("supplier migration: column shape readiness failed")
		}
		primaryKey, primaryKeyKnown := actual.PrimaryKey()
		if !primaryKeyKnown || primaryKey != expected.primaryKey {
			return errors.New("supplier migration: column shape readiness failed")
		}
		if expected.length > 0 {
			length, lengthKnown := actual.Length()
			if !lengthKnown || length != expected.length {
				return errors.New("supplier migration: column shape readiness failed")
			}
		}
		defaultValue, hasDefault := actual.DefaultValue()
		if hasDefault != expected.hasDefault || (hasDefault && normalizeMigrationDefault(defaultValue) != normalizeMigrationDefault(expected.defaultValue)) {
			return errors.New("supplier migration: column shape readiness failed")
		}
	}
	for _, expected := range supplierMigrationIndexes {
		columns, unique, err := loadSupplierMigrationIndexShape(db, dialect, expected.name)
		if err != nil || !migrationStringSlicesEqual(columns, expected.columns) || unique != expected.unique {
			return errors.New("supplier migration: index readiness failed")
		}
	}
	return verifySupplierChecks(db)
}

func loadSupplierMigrationIndexShape(db *gorm.DB, dialect, name string) ([]string, bool, error) {
	rows := make([]struct {
		ColumnName string `gorm:"column:column_name"`
		IsUnique   bool   `gorm:"column:is_unique"`
	}, 0)
	var query string
	switch dialect {
	case "sqlite":
		query = "SELECT info.name AS column_name, list.\"unique\" <> 0 AS is_unique FROM pragma_index_list(?) AS list, pragma_index_info(list.name) AS info WHERE list.name = ? ORDER BY info.seqno"
	case "mysql":
		query = "SELECT column_name, non_unique = 0 AS is_unique FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = ? AND index_name = ? ORDER BY seq_in_index"
	case "postgres":
		query = "SELECT attribute.attname AS column_name, catalog.indisunique AS is_unique FROM pg_index AS catalog JOIN pg_class AS table_class ON table_class.oid = catalog.indrelid JOIN pg_namespace AS namespace ON namespace.oid = table_class.relnamespace JOIN pg_class AS index_class ON index_class.oid = catalog.indexrelid JOIN LATERAL unnest(catalog.indkey) WITH ORDINALITY AS key(attnum, position) ON true JOIN pg_attribute AS attribute ON attribute.attrelid = table_class.oid AND attribute.attnum = key.attnum WHERE namespace.nspname = current_schema() AND table_class.relname = ? AND index_class.relname = ? ORDER BY key.position"
	default:
		return nil, false, errors.New("supplier migration: unsupported index dialect")
	}
	if err := db.Raw(query, "biz_suppliers", name).Scan(&rows).Error; err != nil {
		return nil, false, err
	}
	if len(rows) == 0 {
		return nil, false, errors.New("supplier migration: index not found")
	}
	columns := make([]string, 0, len(rows))
	unique := rows[0].IsUnique
	for _, row := range rows {
		if row.IsUnique != unique {
			return nil, false, errors.New("supplier migration: inconsistent index metadata")
		}
		columns = append(columns, row.ColumnName)
	}
	return columns, unique, nil
}

func migrationStringSlicesEqual(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func migrationDatabaseTypeAllowed(allowed, actual string) bool {
	actual = strings.ToLower(strings.TrimSpace(actual))
	for _, candidate := range strings.Split(allowed, "|") {
		candidate = strings.ToLower(strings.TrimSpace(candidate))
		if actual == candidate || strings.HasPrefix(actual, candidate+"(") {
			return true
		}
	}
	return false
}

func normalizeMigrationDefault(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	for strings.HasPrefix(value, "(") && strings.HasSuffix(value, ")") {
		value = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(value, "("), ")"))
	}
	if cast := strings.Index(value, "::"); cast >= 0 {
		value = value[:cast]
	}
	value = strings.Trim(strings.TrimSpace(value), "'\"")
	switch value {
	case "1", "b'1", "true":
		return "true"
	case "0", "b'0", "false":
		return "false"
	default:
		return value
	}
}

func verifySupplierChecks(db *gorm.DB) error {
	dialect := db.Dialector.Name()
	var definition string
	switch dialect {
	case "sqlite":
		if err := db.Raw("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", "biz_suppliers").Scan(&definition).Error; err != nil {
			return errors.New("supplier migration: check readiness failed")
		}
		if !strings.Contains(definition, "ck_biz_suppliers_credit_level") || !strings.Contains(normalizeMigrationCheckDefinition(definition), normalizeMigrationCheckDefinition("CHECK (\"credit_level\" IN ('preferred', 'normal', 'restricted', 'blocked'))")) {
			return errors.New("supplier migration: check readiness failed")
		}
	case "postgres":
		if err := db.Raw("SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname = ? AND conrelid = ?::regclass", "ck_biz_suppliers_credit_level", "biz_suppliers").Scan(&definition).Error; err != nil || definition == "" {
			return errors.New("supplier migration: check readiness failed")
		}
		if normalizeMigrationCheckDefinition(definition) != normalizeMigrationCheckDefinition("CHECK (((\"credit_level\")::text = ANY ((ARRAY['preferred'::character varying, 'normal'::character varying, 'restricted'::character varying, 'blocked'::character varying])::text[])))") {
			return errors.New("supplier migration: check shape readiness failed")
		}
	case "mysql":
		if err := db.Raw("SELECT cc.check_clause FROM information_schema.check_constraints AS cc JOIN information_schema.table_constraints AS tc ON tc.constraint_schema = cc.constraint_schema AND tc.constraint_name = cc.constraint_name WHERE tc.constraint_schema = DATABASE() AND tc.table_name = ? AND tc.constraint_name = ? AND tc.constraint_type = 'CHECK'", "biz_suppliers", "ck_biz_suppliers_credit_level").Scan(&definition).Error; err != nil || definition == "" {
			return errors.New("supplier migration: check readiness failed")
		}
		if normalizeMigrationCheckDefinition(definition) != normalizeMigrationCheckDefinition("(`credit_level` IN ('preferred', 'normal', 'restricted', 'blocked'))") {
			return errors.New("supplier migration: check shape readiness failed")
		}
	default:
		return errors.New("supplier migration: unsupported check dialect")
	}
	return nil
}

func normalizeMigrationSQL(value string) string {
	return strings.Join(strings.Fields(strings.ToLower(value)), " ")
}

var migrationCharsetIntroducer = regexp.MustCompile(`_[a-z0-9]+(')`)

func normalizeMigrationCheckDefinition(value string) string {
	value = strings.ToLower(value)
	value = strings.ReplaceAll(value, "\\'", "'")
	value = migrationCharsetIntroducer.ReplaceAllString(value, "$1")
	return strings.NewReplacer(
		" ", "",
		"\t", "",
		"\r", "",
		"\n", "",
		"`", "",
		"\"", "",
	).Replace(value)
}
