// Code generated by mss module template 1.3.0-backend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"
	"time"

	configgormdb "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/config/gormdb"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

const (
	supplierMySQLDSNEnv          = "MSS_SUPPLIER_TEST_MYSQL_DSN"
	supplierPostgresDSNEnv       = "MSS_SUPPLIER_TEST_POSTGRES_DSN"
	supplierProviderTestDatabase = "mss_supplier_test"
)

func TestSupplierMigrationMySQLIntegration(t *testing.T) {
	runSupplierMigrationProviderIntegration(t, "mysql", supplierMySQLDSNEnv)
}

func TestSupplierMigrationPostgresIntegration(t *testing.T) {
	runSupplierMigrationProviderIntegration(t, "postgres", supplierPostgresDSNEnv)
}

func TestSupplierMigrationMySQLRejectsCheckAndIndexDrift(t *testing.T) {
	runSupplierMigrationProviderDrift(t, "mysql", supplierMySQLDSNEnv)
}

func TestSupplierMigrationPostgresRejectsCheckAndIndexDrift(t *testing.T) {
	runSupplierMigrationProviderDrift(t, "postgres", supplierPostgresDSNEnv)
}

func runSupplierMigrationProviderIntegration(t *testing.T, dialect, environment string) {
	t.Helper()
	dsn := strings.TrimSpace(os.Getenv(environment))
	if dsn == "" {
		t.Skip(environment + " is not set")
	}
	db := openSupplierProviderDatabase(t, dialect, dsn)

	t.Run("fresh repeat constraints", func(t *testing.T) {
		resetSupplierProviderTables(t, db)
		createSupplierProviderMigrationTable(t, db, dialect)
		runner := configuredSupplierMigrationRunner(t, db)
		for attempt := 1; attempt <= 2; attempt++ {
			if err := runner.MigrateContext(context.Background()); err != nil {
				t.Fatalf("%s migration attempt %d: %v", dialect, attempt, err)
			}
		}
		assertSupplierSchemaReady(t, db)
		valid := &Supplier{
			Code:         "VALUE_01",
			Name:         "VALUE_01",
			Country:      "VALUE_01",
			ContactName:  "VALUE_01",
			ContactEmail: "supplier@example.test",
			CreditLevel:  "preferred",
			Enabled:      true,
		}
		if err := db.Create(valid).Error; err != nil {
			t.Fatalf("%s create valid row: %v", dialect, err)
		}
		duplicate := &Supplier{
			Code:         "VALUE_01",
			Name:         "VALUE_01",
			Country:      "VALUE_01",
			ContactName:  "VALUE_01",
			ContactEmail: "supplier@example.test",
			CreditLevel:  "preferred",
			Enabled:      true,
		}
		if err := db.Create(duplicate).Error; err == nil {
			t.Fatalf("%s unique constraint accepted a duplicate", dialect)
		}
		invalidCreditLevel := &Supplier{
			Code:         "VALUE_02",
			Name:         "VALUE_02",
			Country:      "VALUE_02",
			ContactName:  "VALUE_02",
			ContactEmail: "alternate@example.test",
			CreditLevel:  "outside-contract",
			Enabled:      false,
		}
		if err := db.Create(invalidCreditLevel).Error; err == nil {
			t.Fatalf("%s enum constraint accepted an undeclared value", dialect)
		}
		var versions int64
		if err := db.Table("mss_boot_migration").Where("version = ?", SupplierMigrationID.String()).Count(&versions).Error; err != nil || versions != 1 {
			t.Fatalf("%s migration version count = %d, err=%v", dialect, versions, err)
		}
	})

	t.Run("interrupted recovery", func(t *testing.T) {
		resetSupplierProviderTables(t, db)
		createSupplierProviderMigrationTable(t, db, dialect)
		injected := errors.New("provider interruption")
		if err := applySupplierMigration(db, SupplierMigrationID.String(), func() error { return injected }); !errors.Is(err, injected) {
			t.Fatalf("%s interrupted migration error = %v", dialect, err)
		}
		var versions int64
		if err := db.Table("mss_boot_migration").Where("version = ?", SupplierMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
			t.Fatalf("%s interrupted version count = %d, err=%v", dialect, versions, err)
		}
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err != nil {
			t.Fatalf("%s recovery migration: %v", dialect, err)
		}
		assertSupplierSchemaReady(t, db)
	})

	t.Run("runtime conflicts and escaped search without TranslateError", func(t *testing.T) {
		resetSupplierProviderTables(t, db)
		createSupplierProviderMigrationTable(t, db, dialect)
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err != nil {
			t.Fatalf("%s runtime migration: %v", dialect, err)
		}
		collector := &collectingSupplierEvents{db: db}
		service, err := NewService(db, collector)
		if err != nil {
			t.Fatalf("%s NewService(): %v", dialect, err)
		}
		first, err := service.Create(context.Background(), validSupplierInput())
		if err != nil {
			t.Fatalf("%s Create(first): %v", dialect, err)
		}
		if _, err := service.Create(context.Background(), validSupplierInput()); !errors.Is(err, ErrSupplierConflict) {
			t.Fatalf("%s Create(duplicate without TranslateError) error = %v", dialect, err)
		}
		secondInput := validSupplierInput()
		secondInput.Code = "VALUE_02"
		secondInput.Name = "VALUE_02"
		secondInput.Country = "VALUE_02"
		secondInput.ContactName = "VALUE_02"
		secondInput.ContactEmail = "alternate@example.test"
		second, err := service.Create(context.Background(), secondInput)
		if err != nil {
			t.Fatalf("%s Create(second): %v", dialect, err)
		}
		page, err := service.List(context.Background(), ListSupplierQuery{Q: "%", Current: 1, PageSize: 10})
		if err != nil {
			t.Fatalf("%s escaped wildcard List(): %v", dialect, err)
		}
		if page.Total != 0 {
			t.Fatalf("%s escaped wildcard search matched %d rows", dialect, page.Total)
		}
		if err := db.Exec("CREATE UNIQUE INDEX ux_supplier_provider_update_conflict ON biz_suppliers (name)").Error; err != nil {
			t.Fatalf("%s create update conflict index: %v", dialect, err)
		}
		conflictingValue := second.Name
		if _, err := service.Update(context.Background(), first.ID, &UpdateSupplierInput{Name: &conflictingValue}); !errors.Is(err, ErrSupplierConflict) {
			t.Fatalf("%s Update(duplicate without TranslateError) error = %v", dialect, err)
		}
		declaredConflict := second.Code
		if _, err := service.Update(context.Background(), first.ID, &UpdateSupplierInput{Code: &declaredConflict}); !errors.Is(err, ErrSupplierConflict) {
			t.Fatalf("%s Update(declared duplicate without TranslateError) error = %v", dialect, err)
		}
	})
}

func runSupplierMigrationProviderDrift(t *testing.T, dialect, environment string) {
	t.Helper()
	dsn := strings.TrimSpace(os.Getenv(environment))
	if dsn == "" {
		t.Skip(environment + " is not set")
	}
	db := openSupplierProviderDatabase(t, dialect, dsn)

	t.Run("same-name index shape", func(t *testing.T) {
		resetSupplierProviderTables(t, db)
		createSupplierProviderMigrationTable(t, db, dialect)
		if err := db.Exec(createSupplierTableDDL[dialect]).Error; err != nil {
			t.Fatalf("%s create table: %v", dialect, err)
		}
		if len(supplierMigrationIndexes) == 0 {
			t.Fatal("test contract requires an index")
		}
		index := supplierMigrationIndexes[0]
		wrongColumn := "id"
		if len(index.columns) == 1 && index.columns[0] == wrongColumn {
			wrongColumn = "created_at"
		}
		keyword := ""
		if index.unique {
			keyword = "UNIQUE "
		}
		ddl := "CREATE " + keyword + "INDEX " + quoteSupplierProviderIdentifier(dialect, index.name) + " ON " + quoteSupplierProviderIdentifier(dialect, "biz_suppliers") + " (" + quoteSupplierProviderIdentifier(dialect, wrongColumn) + ")"
		if err := db.Exec(ddl).Error; err != nil {
			t.Fatalf("%s create wrong-shape index: %v", dialect, err)
		}
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatalf("%s migration accepted a same-name wrong-column index", dialect)
		}
		assertSupplierProviderVersionAbsent(t, db, dialect)
	})

	t.Run("permissive check body", func(t *testing.T) {
		resetSupplierProviderTables(t, db)
		createSupplierProviderMigrationTable(t, db, dialect)
		driftedDDL, ok := driftSupplierProviderCheck(createSupplierTableDDL[dialect], dialect, "ck_biz_suppliers_credit_level")
		if !ok {
			t.Fatal("test contract could not make the check permissive")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("%s create check-drifted table: %v", dialect, err)
		}
		runner := configuredSupplierMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatalf("%s migration accepted a permissive check body", dialect)
		}
		assertSupplierProviderVersionAbsent(t, db, dialect)
	})
}

func quoteSupplierProviderIdentifier(dialect, value string) string {
	if dialect == "mysql" {
		return "`" + value + "`"
	}
	return "\"" + value + "\""
}

func driftSupplierProviderCheck(ddl, dialect, name string) (string, bool) {
	marker := "CONSTRAINT " + quoteSupplierProviderIdentifier(dialect, name) + " CHECK ("
	start := strings.Index(ddl, marker)
	if start < 0 {
		return ddl, false
	}
	end := strings.Index(ddl[start:], "\n")
	if end < 0 {
		end = len(ddl) - start
	}
	line := ddl[start : start+end]
	closing := strings.LastIndex(line, ")")
	if closing < 0 {
		return ddl, false
	}
	driftedLine := line[:closing] + " OR 1 = 1" + line[closing:]
	return strings.Replace(ddl, line, driftedLine, 1), true
}

func assertSupplierProviderVersionAbsent(t *testing.T, db *gorm.DB, dialect string) {
	t.Helper()
	var versions int64
	if err := db.Table("mss_boot_migration").Where("version = ?", SupplierMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("%s drifted migration version count = %d, err=%v", dialect, versions, err)
	}
}

func openSupplierProviderDatabase(t *testing.T, dialect, dsn string) *gorm.DB {
	t.Helper()
	dialector, ok := configgormdb.Opens[dialect]
	if !ok {
		t.Fatalf("provider dialect %q is unavailable", dialect)
	}
	db, err := gorm.Open(dialector(dsn), &gorm.Config{
		DisableForeignKeyConstraintWhenMigrating: true,
		TranslateError:                           false,
		Logger:                                   logger.Discard,
	})
	if err != nil {
		t.Fatalf("open %s provider database: %v", dialect, err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("obtain %s provider handle: %v", dialect, err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	if err := sqlDB.PingContext(ctx); err != nil {
		cancel()
		_ = sqlDB.Close()
		t.Fatalf("ping %s provider database: %v", dialect, err)
	}
	var databaseName string
	query := "SELECT current_database()"
	if dialect == "mysql" {
		query = "SELECT DATABASE()"
	}
	if err := db.WithContext(ctx).Raw(query).Scan(&databaseName).Error; err != nil {
		cancel()
		_ = sqlDB.Close()
		t.Fatalf("read %s provider database name: %v", dialect, err)
	}
	if databaseName != supplierProviderTestDatabase {
		cancel()
		_ = sqlDB.Close()
		t.Fatalf("refusing destructive %s test outside allowlisted database %q", dialect, supplierProviderTestDatabase)
	}
	t.Cleanup(func() {
		resetSupplierProviderTables(t, db)
		cancel()
		if err := sqlDB.Close(); err != nil {
			t.Errorf("close %s provider database: %v", dialect, err)
		}
	})
	return db.WithContext(ctx)
}

func resetSupplierProviderTables(t *testing.T, db *gorm.DB) {
	t.Helper()
	for _, table := range []string{
		"biz_suppliers",
		"mss_boot_casbin_rule",
		"mss_boot_config_revisions",
		"mss_boot_menus",
		"mss_boot_roles",
		"mss_boot_migration",
	} {
		if err := db.Exec("DROP TABLE IF EXISTS " + table).Error; err != nil {
			t.Fatalf("drop %s: %v", table, err)
		}
	}
}

func createSupplierProviderMigrationTable(t *testing.T, db *gorm.DB, dialect string) {
	t.Helper()
	ddl := "CREATE TABLE mss_boot_migration (version TEXT PRIMARY KEY, apply_time TIMESTAMPTZ NOT NULL)"
	if dialect == "mysql" {
		ddl = "CREATE TABLE mss_boot_migration (version VARCHAR(255) PRIMARY KEY, apply_time DATETIME(3) NOT NULL) ENGINE=InnoDB"
	}
	if err := db.Exec(ddl).Error; err != nil {
		t.Fatalf("create %s migration table: %v", dialect, err)
	}
	prepareSupplierAuthorizationTestSchema(t, db)
}
