// Code generated by mss module template 1.2.0-backend.4 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/response/actions"

// Supplier is the persistent entity generated for 供应商管理.
type Supplier struct {
	actions.ModelGorm
	Code         string `json:"code" gorm:"column:code;type:varchar(64);not null;uniqueIndex:ux_biz_suppliers_code;comment:供应商编码"`
	Name         string `json:"name" gorm:"column:name;type:varchar(200);not null;index:idx_biz_suppliers_name,priority:1;comment:供应商名称"`
	Country      string `json:"country" gorm:"column:country;type:varchar(100);index:idx_biz_suppliers_country_enabled,priority:1;comment:国家或地区"`
	ContactName  string `json:"contactName" gorm:"column:contact_name;type:varchar(100);not null;comment:联系人"`
	ContactEmail string `json:"contactEmail" gorm:"column:contact_email;type:varchar(254);comment:联系邮箱"`
	CreditLevel  string `json:"creditLevel" gorm:"column:credit_level;type:varchar(255);not null;default:normal;comment:信用等级"`
	Enabled      bool   `json:"enabled" gorm:"column:enabled;type:boolean;not null;index:idx_biz_suppliers_country_enabled,priority:2;default:true;comment:启用状态"`
}

// TableName returns the stable database table name.
func (*Supplier) TableName() string {
	return "biz_suppliers"
}
