// Code generated by mss module template 1.2.0-backend.4 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"errors"
	"testing"

	"github.com/mss-boot-io/mss-boot-admin/admin/business"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	"gorm.io/gorm"
)

func TestSupplierTableName(t *testing.T) {
	if got, want := new(Supplier).TableName(), "biz_suppliers"; got != want {
		t.Fatalf("TableName() = %q, want %q", got, want)
	}
}

func TestSupplierMigrationIdentityIsComplete(t *testing.T) {
	if got, want := SupplierMigrationID.String(), "20260810160000"; got != want {
		t.Fatalf("migration ID = %q, want %q", got, want)
	}
}

func TestSupplierAuthorizationMigrationIdentityIsComplete(t *testing.T) {
	if got, want := SupplierAuthorizationMigrationID.String(), "20260811120000"; got != want {
		t.Fatalf("authorization migration ID = %q, want %q", got, want)
	}
}

func TestSupplierPermissionCodesAreUnique(t *testing.T) {
	codes := []string{
		"supplier:create",
		"supplier:delete",
		"supplier:export",
		"supplier:list",
		"supplier:read",
		"supplier:update",
	}
	seen := make(map[string]struct{}, len(codes))
	for _, code := range codes {
		if _, exists := seen[code]; exists {
			t.Fatalf("duplicate permission code %q", code)
		}
		seen[code] = struct{}{}
	}
}

func TestSupplierOperationContractMatchesSpecification(t *testing.T) {
	contracts := OperationContracts()
	if got, want := len(contracts), 6; got != want {
		t.Fatalf("operation contracts = %d, want %d", got, want)
	}
	want := map[string]string{
		"POST /admin/api/suppliers":        PermissionCreate,
		"DELETE /admin/api/suppliers/{id}": PermissionDelete,
		"GET /admin/api/suppliers/export":  PermissionExport,
		"GET /admin/api/suppliers/{id}":    PermissionRead,
		"GET /admin/api/suppliers":         PermissionList,
		"PUT /admin/api/suppliers/{id}":    PermissionUpdate,
	}
	for _, contract := range contracts {
		key := contract.Method + " " + contract.Path
		if permission, exists := want[key]; !exists || permission != contract.Permission {
			t.Fatalf("unexpected operation contract %#v", contract)
		}
		delete(want, key)
	}
	if len(want) != 0 {
		t.Fatalf("missing operation contracts: %#v", want)
	}
}

func TestSupplierDescriptorProjectsAuthorizationMetadataWithoutInferringComposition(t *testing.T) {
	module := Module()
	if got, want := module.Name(), "supplier"; got != want {
		t.Fatalf("Module().Name() = %q, want %q", got, want)
	}
	registry, err := business.Compose(migration.New(), module)
	if err != nil {
		t.Fatalf("compose generated module: %v", err)
	}
	descriptors := registry.Descriptors()
	if len(descriptors) != 1 {
		t.Fatalf("generated descriptors = %#v", descriptors)
	}
	descriptor := descriptors[0]
	if descriptor.Migrate != nil {
		t.Fatal("generated descriptor must not expose AutoMigrate or another inferred migration hook")
	}
	if got, want := len(descriptor.Permissions), 6; got != want {
		t.Fatalf("descriptor permissions = %d, want %d", got, want)
	}
	if got, want := descriptor.Menu.Path, "/suppliers"; got != want {
		t.Fatalf("descriptor menu path = %q, want %q", got, want)
	}
	runner, err := registry.MigrationRunner()
	if err != nil {
		t.Fatalf("clone generated migration runner: %v", err)
	}
	if err := runner.Register(SupplierMigrationID, func(*gorm.DB, string) error { return nil }); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("generated schema migration was not registered: %v", err)
	}
	if err := runner.Register(SupplierAuthorizationMigrationID, func(*gorm.DB, string) error { return nil }); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("generated authorization migration was not registered: %v", err)
	}
}
