// Code generated by mss module template 1.3.0-backend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"context"
	"errors"
	"fmt"
	"io"

	"github.com/gin-gonic/gin"
	"github.com/mss-boot-io/mss-boot-admin/admin/business"
	"github.com/mss-boot-io/mss-boot-admin/admin/models"
	"gorm.io/gorm"
)

type businessModule struct{}

// Module returns this generated module's explicit Admin composition contract.
func Module() business.Module { return businessModule{} }

func (businessModule) Name() string { return "supplier" }

func (businessModule) Register(registry *business.Registry) error {
	if registry == nil {
		return errors.New("supplier business registry is required")
	}
	return registry.Register(business.Registration{
		Descriptor: Descriptor(),
		Migrations: RegisterMigration,
		Readiness:  verifyRuntimeReadiness,
		Routes:     registerBusinessRoutes,
	})
}

func verifyRuntimeReadiness(ctx context.Context, db *gorm.DB) error {
	if ctx == nil {
		return errors.New("supplier schema readiness context is required")
	}
	if db == nil {
		return errors.New("supplier schema readiness database is required")
	}
	if err := business.RequireAppliedMigrations(
		ctx,
		db,
		SupplierMigrationID,
		SupplierAuthorizationMigrationID,
	); err != nil {
		return fmt.Errorf("supplier migration readiness failed: %w", err)
	}
	readyDB := db.WithContext(ctx)
	if !readyDB.Migrator().HasTable(new(Supplier)) {
		return errors.New("supplier migration readiness failed: business table is unavailable")
	}
	if !readyDB.Migrator().HasTable(new(models.CasbinRule)) {
		return errors.New("supplier authorization readiness failed: Admin policy table is unavailable")
	}
	return nil
}

func registerBusinessRoutes(group *gin.RouterGroup, runtime business.Runtime) error {
	if group == nil {
		return errors.New("supplier protected route group is required")
	}
	application := &requestApplication{
		database: runtime.RequestDatabase,
		events:   businessEventCollector{collector: runtime.Events},
	}
	authorizer := &requestAuthorizer{
		database:  runtime.RequestDatabase,
		principal: runtime.Principal,
	}
	if err := RegisterRoutes(group, application, authorizer); err != nil {
		return fmt.Errorf("register supplier routes: %w", err)
	}
	return nil
}

type businessEventCollector struct {
	collector business.EventCollector
}

func (collector businessEventCollector) Collect(ctx context.Context, event DomainEvent) {
	collector.collector.Collect(ctx, event)
}

type requestApplication struct {
	database business.RequestDatabase
	events   EventCollector
}

func (application *requestApplication) service(ctx context.Context) (*Service, error) {
	if application == nil || application.database == nil {
		return nil, ErrSupplierPersistence
	}
	db, ok := application.database(ctx)
	if !ok || db == nil {
		return nil, ErrSupplierPersistence
	}
	service, err := NewService(db, application.events)
	if err != nil {
		return nil, fmt.Errorf("%w: compose request service", ErrSupplierPersistence)
	}
	return service, nil
}

func (application *requestApplication) List(
	ctx context.Context,
	query ListSupplierQuery,
) (SupplierPage, error) {
	service, err := application.service(ctx)
	if err != nil {
		return SupplierPage{}, err
	}
	return service.List(ctx, query)
}

func (application *requestApplication) Get(
	ctx context.Context,
	id string,
) (*Supplier, error) {
	service, err := application.service(ctx)
	if err != nil {
		return nil, err
	}
	return service.Get(ctx, id)
}

func (application *requestApplication) Create(
	ctx context.Context,
	input *CreateSupplierInput,
) (*Supplier, error) {
	service, err := application.service(ctx)
	if err != nil {
		return nil, err
	}
	return service.Create(ctx, input)
}

func (application *requestApplication) Update(
	ctx context.Context,
	id string,
	input *UpdateSupplierInput,
) (*Supplier, error) {
	service, err := application.service(ctx)
	if err != nil {
		return nil, err
	}
	return service.Update(ctx, id, input)
}

func (application *requestApplication) Delete(ctx context.Context, id string) error {
	service, err := application.service(ctx)
	if err != nil {
		return err
	}
	return service.Delete(ctx, id)
}

func (application *requestApplication) Export(
	ctx context.Context,
	query ListSupplierQuery,
	destination io.Writer,
) error {
	service, err := application.service(ctx)
	if err != nil {
		return err
	}
	return service.Export(ctx, query, destination)
}

type requestAuthorizer struct {
	database  business.RequestDatabase
	principal business.PrincipalResolver
}

func (authorizer *requestAuthorizer) Authorize(
	ctx *gin.Context,
	permission string,
) error {
	if authorizer == nil || authorizer.database == nil || authorizer.principal == nil ||
		ctx == nil || ctx.Request == nil {
		return ErrSupplierAuthorizationUnavailable
	}
	db, ok := authorizer.database(ctx.Request.Context())
	if !ok || db == nil {
		return ErrSupplierAuthorizationUnavailable
	}
	requestAuthorizer, err := NewAdminAuthorizer(db, AdminPrincipalResolver(authorizer.principal))
	if err != nil {
		return fmt.Errorf("%w: compose request authorizer", ErrSupplierAuthorizationUnavailable)
	}
	return requestAuthorizer.Authorize(ctx, permission)
}
