// Code generated by mss module presentation template 1.3.7-presentation-v2.2 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"encoding/json"
	"reflect"
	"testing"

	"github.com/mss-boot-io/mss-boot-admin/admin/presentation"
)

func TestGeneratedPresentationDefinitionContract(t *testing.T) {
	definition := PresentationDefinition()
	if definition.DefinitionVersion != presentation.DefinitionVersionV2 {
		t.Fatalf("generated presentation definition version = %q, want %q", definition.DefinitionVersion, presentation.DefinitionVersionV2)
	}
	if definition.PageKey == "" {
		t.Fatal("generated presentation page key is empty")
	}
	if issues := presentation.ValidateCapability(&definition); len(issues) != 0 {
		t.Fatalf("generated presentation capability is invalid: %#v", issues)
	}
	computedHash, err := presentation.ComputeDefinitionHash(&definition)
	if err != nil {
		t.Fatalf("compute generated presentation definition hash: %v", err)
	}
	if definition.DefinitionHash != computedHash {
		t.Fatalf("generated presentation definition hash = %q, computed %q", definition.DefinitionHash, computedHash)
	}

	wire, err := json.Marshal(definition)
	if err != nil {
		t.Fatalf("marshal generated presentation definition: %v", err)
	}
	var actual any
	if err := json.Unmarshal(wire, &actual); err != nil {
		t.Fatalf("decode generated presentation definition: %v", err)
	}
	var expected any
	if err := json.Unmarshal([]byte(presentationDefinitionJSON), &expected); err != nil {
		t.Fatalf("decode embedded generated presentation definition: %v", err)
	}
	if !reflect.DeepEqual(actual, expected) {
		t.Fatalf("generated presentation definition wire payload differs from embedded source\nactual:   %s\nexpected: %s", wire, presentationDefinitionJSON)
	}
}
