// Code generated by mss module template 1.1.0-backend.2 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"context"
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"reflect"
	"sort"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const maxSupplierExportRows = 10000

var (
	ErrSupplierNotFound    = errors.New("supplier not found")
	ErrSupplierConflict    = errors.New("supplier conflict")
	ErrSupplierPersistence = errors.New("supplier persistence unavailable")
	ErrSupplierExportLimit = errors.New("supplier export limit exceeded")
)

// Application is the generated backend use-case boundary consumed by HTTP.
type Application interface {
	List(context.Context, ListSupplierQuery) (SupplierPage, error)
	Get(context.Context, string) (*Supplier, error)
	Create(context.Context, *CreateSupplierInput) (*Supplier, error)
	Update(context.Context, string, *UpdateSupplierInput) (*Supplier, error)
	Delete(context.Context, string) error
	Export(context.Context, ListSupplierQuery, io.Writer) error
}

// Service owns authoritative supplier transactions.
type Service struct {
	db     *gorm.DB
	events EventCollector
}

func NewService(db *gorm.DB, events EventCollector) (*Service, error) {
	if db == nil {
		return nil, errors.New("supplier database is required")
	}
	if isNilEventCollector(events) {
		return nil, errors.New("supplier event collector is required")
	}
	return &Service{db: db, events: events}, nil
}

func isNilEventCollector(events EventCollector) bool {
	if events == nil {
		return true
	}
	value := reflect.ValueOf(events)
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return value.IsNil()
	default:
		return false
	}
}

func (service *Service) List(ctx context.Context, query ListSupplierQuery) (SupplierPage, error) {
	if service == nil || service.db == nil {
		return SupplierPage{}, ErrSupplierPersistence
	}
	if ctx == nil {
		return SupplierPage{}, &ValidationError{Field: "context", Rule: "required"}
	}
	if err := query.normalizeAndValidate(); err != nil {
		return SupplierPage{}, err
	}
	db := applySupplierQuery(service.db.WithContext(ctx).Model(new(Supplier)), query)
	var total int64
	if err := db.Count(&total).Error; err != nil {
		return SupplierPage{}, normalizeSupplierDBError(err)
	}
	var records []Supplier
	db = orderSupplierQuery(db, query)
	if err := db.Offset((query.Current - 1) * query.PageSize).Limit(query.PageSize).Find(&records).Error; err != nil {
		return SupplierPage{}, normalizeSupplierDBError(err)
	}
	return SupplierPage{Data: records, Total: total, Current: query.Current, PageSize: query.PageSize}, nil
}

func (service *Service) Get(ctx context.Context, id string) (*Supplier, error) {
	if service == nil || service.db == nil {
		return nil, ErrSupplierPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, &ValidationError{Field: "id", Rule: "required"}
	}
	var record Supplier
	if err := service.db.WithContext(ctx).First(&record, "id = ?", id).Error; err != nil {
		return nil, normalizeSupplierDBError(err)
	}
	return &record, nil
}

func (service *Service) Create(ctx context.Context, input *CreateSupplierInput) (*Supplier, error) {
	if service == nil || service.db == nil {
		return nil, ErrSupplierPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	if err := input.normalizeAndValidate(); err != nil {
		return nil, err
	}
	record := &Supplier{
		Code:         input.Code,
		Name:         input.Name,
		Country:      input.Country,
		ContactName:  input.ContactName,
		ContactEmail: input.ContactEmail,
		CreditLevel:  input.CreditLevel,
		Enabled:      boolValue(input.Enabled),
	}
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		return tx.Create(record).Error
	}); err != nil {
		return nil, service.normalizeSupplierWriteError(ctx, "", record, err)
	}
	service.events.Collect(ctx, SupplierCreatedEvent{ResourceID: record.ID, OccurredAt: record.CreatedAt})
	return record, nil
}

func (service *Service) Update(ctx context.Context, id string, input *UpdateSupplierInput) (*Supplier, error) {
	if service == nil || service.db == nil {
		return nil, ErrSupplierPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, &ValidationError{Field: "id", Rule: "required"}
	}
	if err := input.normalizeAndValidate(); err != nil {
		return nil, err
	}
	changedFields := make([]string, 0, 7)
	updates := make(map[string]any, 7)
	if input.Code != nil {
		updates["code"] = *input.Code
		changedFields = append(changedFields, "code")
	}
	if input.Name != nil {
		updates["name"] = *input.Name
		changedFields = append(changedFields, "name")
	}
	if input.Country != nil {
		updates["country"] = *input.Country
		changedFields = append(changedFields, "country")
	}
	if input.ContactName != nil {
		updates["contact_name"] = *input.ContactName
		changedFields = append(changedFields, "contactName")
	}
	if input.ContactEmail != nil {
		updates["contact_email"] = *input.ContactEmail
		changedFields = append(changedFields, "contactEmail")
	}
	if input.CreditLevel != nil {
		updates["credit_level"] = *input.CreditLevel
		changedFields = append(changedFields, "creditLevel")
	}
	if input.Enabled != nil {
		updates["enabled"] = *input.Enabled
		changedFields = append(changedFields, "enabled")
	}
	sort.Strings(changedFields)
	var record Supplier
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&record, "id = ?", id).Error; err != nil {
			return err
		}
		if input.Code != nil {
			record.Code = *input.Code
		}
		if input.Name != nil {
			record.Name = *input.Name
		}
		if input.Country != nil {
			record.Country = *input.Country
		}
		if input.ContactName != nil {
			record.ContactName = *input.ContactName
		}
		if input.ContactEmail != nil {
			record.ContactEmail = *input.ContactEmail
		}
		if input.CreditLevel != nil {
			record.CreditLevel = *input.CreditLevel
		}
		if input.Enabled != nil {
			record.Enabled = *input.Enabled
		}
		if err := tx.Model(&record).Updates(updates).Error; err != nil {
			return err
		}
		return tx.First(&record, "id = ?", id).Error
	}); err != nil {
		return nil, service.normalizeSupplierWriteError(ctx, id, &record, err)
	}
	service.events.Collect(ctx, SupplierUpdatedEvent{ResourceID: record.ID, ChangedFields: changedFields, OccurredAt: record.UpdatedAt})
	return &record, nil
}

func (service *Service) Delete(ctx context.Context, id string) error {
	if service == nil || service.db == nil {
		return ErrSupplierPersistence
	}
	if ctx == nil {
		return &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return &ValidationError{Field: "id", Rule: "required"}
	}
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var record Supplier
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&record, "id = ?", id).Error; err != nil {
			return err
		}
		return tx.Delete(&record).Error
	}); err != nil {
		return normalizeSupplierDBError(err)
	}
	return nil
}

func (service *Service) Export(ctx context.Context, query ListSupplierQuery, destination io.Writer) error {
	if service == nil || service.db == nil {
		return ErrSupplierPersistence
	}
	if ctx == nil {
		return &ValidationError{Field: "context", Rule: "required"}
	}
	if destination == nil {
		return &ValidationError{Field: "destination", Rule: "required"}
	}
	query.Current = 1
	query.PageSize = 100
	if err := query.normalizeAndValidate(); err != nil {
		return err
	}
	var records []Supplier
	db := applySupplierQuery(service.db.WithContext(ctx).Model(new(Supplier)), query)
	db = orderSupplierQuery(db, query).Limit(maxSupplierExportRows + 1)
	if err := db.Find(&records).Error; err != nil {
		return normalizeSupplierDBError(err)
	}
	if len(records) > maxSupplierExportRows {
		return ErrSupplierExportLimit
	}
	writer := csv.NewWriter(destination)
	if err := writer.Write([]string{"id", "code", "name", "country", "contactName", "contactEmail", "creditLevel", "enabled"}); err != nil {
		return ErrSupplierPersistence
	}
	for _, record := range records {
		row := []string{csvSafe(record.ID), csvSafe(fmt.Sprint(record.Code)), csvSafe(fmt.Sprint(record.Name)), csvSafe(fmt.Sprint(record.Country)), csvSafe(fmt.Sprint(record.ContactName)), csvSafe(fmt.Sprint(record.ContactEmail)), csvSafe(fmt.Sprint(record.CreditLevel)), csvSafe(fmt.Sprint(record.Enabled))}
		if err := writer.Write(row); err != nil {
			return ErrSupplierPersistence
		}
	}
	writer.Flush()
	if writer.Error() != nil {
		return ErrSupplierPersistence
	}
	return nil
}

func applySupplierQuery(db *gorm.DB, query ListSupplierQuery) *gorm.DB {
	if query.Q != "" {
		pattern := "%" + escapeLike(strings.ToLower(query.Q)) + "%"
		db = db.Where(
			strings.Join([]string{
				"LOWER(code) LIKE ? ESCAPE '!'",
				"LOWER(name) LIKE ? ESCAPE '!'",
				"LOWER(contact_name) LIKE ? ESCAPE '!'",
			}, " OR "),
			pattern,
			pattern,
			pattern,
		)
	}
	if query.Country != "" {
		db = db.Where("country = ?", query.Country)
	}
	if query.CreditLevel != "" {
		db = db.Where("credit_level = ?", query.CreditLevel)
	}
	if query.Enabled != nil {
		db = db.Where("enabled = ?", *query.Enabled)
	}
	return db
}

func orderSupplierQuery(db *gorm.DB, query ListSupplierQuery) *gorm.DB {
	columns := map[string]string{
		"code": "code",
		"name": "name",
	}
	if column := columns[query.SortBy]; column != "" {
		db = db.Order(clause.OrderByColumn{Column: clause.Column{Name: column}, Desc: query.SortOrder == "desc"})
	} else {
		db = db.Order(clause.OrderByColumn{Column: clause.Column{Name: "created_at"}, Desc: true})
	}
	return db.Order(clause.OrderByColumn{Column: clause.Column{Name: "id"}})
}

func normalizeSupplierDBError(err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, gorm.ErrRecordNotFound):
		return ErrSupplierNotFound
	case errors.Is(err, gorm.ErrDuplicatedKey), isUniqueConstraintError(err):
		return ErrSupplierConflict
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return err
	default:
		return ErrSupplierPersistence
	}
}

func isUniqueConstraintError(err error) bool {
	type sqlStateError interface {
		SQLState() string
	}
	var sqlState sqlStateError
	if errors.As(err, &sqlState) && sqlState.SQLState() == "23505" {
		return true
	}
	type sqliteCodeError interface {
		Code() int
	}
	var sqliteCode sqliteCodeError
	if errors.As(err, &sqliteCode) && (sqliteCode.Code() == 1555 || sqliteCode.Code() == 2067) {
		return true
	}
	for current := err; current != nil; current = errors.Unwrap(current) {
		value := reflect.ValueOf(current)
		if value.Kind() == reflect.Pointer && !value.IsNil() {
			value = value.Elem()
		}
		if value.Kind() != reflect.Struct {
			continue
		}
		number := value.FieldByName("Number")
		if number.IsValid() && number.CanUint() && number.Kind() >= reflect.Uint && number.Kind() <= reflect.Uint64 && number.Uint() == 1062 {
			return true
		}
	}
	return false
}
func (service *Service) normalizeSupplierWriteError(ctx context.Context, excludeID string, record *Supplier, err error) error {
	normalized := normalizeSupplierDBError(err)
	if !errors.Is(normalized, ErrSupplierPersistence) {
		return normalized
	}
	conflict, probeErr := service.hasSupplierUniqueConflict(ctx, excludeID, record)
	if probeErr != nil {
		return ErrSupplierPersistence
	}
	if conflict {
		return ErrSupplierConflict
	}
	return normalized
}

func (service *Service) hasSupplierUniqueConflict(ctx context.Context, excludeID string, record *Supplier) (bool, error) {
	if record == nil {
		return false, nil
	}
	query0 := service.db.WithContext(ctx).Unscoped().Model(new(Supplier))
	query0 = query0.Where("code = ?", record.Code)
	if excludeID != "" {
		query0 = query0.Where("id <> ?", excludeID)
	}
	var count0 int64
	if err := query0.Count(&count0).Error; err != nil {
		return false, err
	}
	if count0 > 0 {
		return true, nil
	}
	return false, nil
}

func boolValue(value *bool) bool {
	return value != nil && *value
}

func escapeLike(value string) string {
	value = strings.ReplaceAll(value, `!`, `!!`)
	value = strings.ReplaceAll(value, `%`, `!%`)
	return strings.ReplaceAll(value, `_`, `!_`)
}

func csvSafe(value string) string {
	if value == "" {
		return value
	}
	switch value[0] {
	case '=', '+', '-', '@':
		return "'" + value
	default:
		return value
	}
}
