// Code generated by mss module template 1.3.0-backend.1 from .mss/modules/example-supplier.yaml. DO NOT EDIT.

package supplier

import (
	"context"
	"errors"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/glebarez/sqlite"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

type collectingSupplierEvents struct {
	mu        sync.Mutex
	db        *gorm.DB
	events    []DomainEvent
	committed []bool
}

func (collector *collectingSupplierEvents) Collect(_ context.Context, event DomainEvent) {
	var count int64
	resourceID := ""
	switch typed := event.(type) {
	case SupplierCreatedEvent:
		resourceID = typed.ResourceID
	case SupplierUpdatedEvent:
		resourceID = typed.ResourceID
	}
	committed := collector.db.Model(new(Supplier)).Where("id = ?", resourceID).Count(&count).Error == nil && count == 1
	collector.mu.Lock()
	defer collector.mu.Unlock()
	collector.events = append(collector.events, event)
	collector.committed = append(collector.committed, committed)
}

func (collector *collectingSupplierEvents) snapshot() ([]DomainEvent, []bool) {
	collector.mu.Lock()
	defer collector.mu.Unlock()
	return append([]DomainEvent(nil), collector.events...), append([]bool(nil), collector.committed...)
}

func TestSupplierServiceCRUDQueryExportAndPostCommitEvents(t *testing.T) {
	db := openSupplierTestDatabase(t)
	if _, err := NewService(db, nil); err == nil {
		t.Fatal("NewService(nil event collector) unexpectedly succeeded")
	}
	var typedNilCollector *collectingSupplierEvents
	if _, err := NewService(db, typedNilCollector); err == nil {
		t.Fatal("NewService(typed nil event collector) unexpectedly succeeded")
	}
	collector := &collectingSupplierEvents{db: db}
	service, err := NewService(db, collector)
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}

	invalid := validSupplierInput()
	invalid.Code = "invalid value"
	if _, err := service.Create(context.Background(), invalid); err == nil {
		t.Fatal("Create(invalid pattern) unexpectedly succeeded")
	}

	input := validSupplierInput()
	created, err := service.Create(context.Background(), input)
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if created.ID == "" {
		t.Fatal("Create() did not assign an ID")
	}
	if created.CreditLevel != "normal" {
		t.Fatalf("default creditLevel = %q", created.CreditLevel)
	}
	if created.Enabled != true {
		t.Fatalf("default enabled = %v", created.Enabled)
	}
	events, committed := collector.snapshot()
	if len(events) != 1 || events[0].EventName() != "procurement.supplier.created" || !committed[0] {
		t.Fatalf("created events = %#v, committed = %#v", events, committed)
	}
	if _, err := service.Create(context.Background(), validSupplierInput()); !errors.Is(err, ErrSupplierConflict) {
		t.Fatalf("Create(duplicate) error = %v, want conflict", err)
	}

	secondInput := validSupplierInput()
	secondInput.Code = "VALUE_02"
	secondInput.Name = "VALUE_02"
	secondInput.Country = "VALUE_02"
	secondInput.ContactName = "VALUE_02"
	secondInput.ContactEmail = "alternate@example.test"
	second, err := service.Create(context.Background(), secondInput)
	if err != nil {
		t.Fatalf("Create(second) error = %v", err)
	}
	if err := db.Exec("CREATE UNIQUE INDEX ux_supplier_generated_update_conflict ON biz_suppliers (name)").Error; err != nil {
		t.Fatalf("create update conflict index: %v", err)
	}
	conflictingValue := second.Name
	if _, err := service.Update(context.Background(), created.ID, &UpdateSupplierInput{Name: &conflictingValue}); !errors.Is(err, ErrSupplierConflict) {
		t.Fatalf("Update(duplicate without TranslateError) error = %v, want conflict", err)
	}
	if err := db.Exec("DROP INDEX ux_supplier_generated_update_conflict").Error; err != nil {
		t.Fatalf("drop update conflict index: %v", err)
	}
	conflictingUniqueValue := second.Code
	if _, err := service.Update(context.Background(), created.ID, &UpdateSupplierInput{Code: &conflictingUniqueValue}); !errors.Is(err, ErrSupplierConflict) {
		t.Fatalf("Update(declared duplicate without TranslateError) error = %v, want conflict", err)
	}

	query := ListSupplierQuery{
		Current:     1,
		PageSize:    1,
		SortBy:      "code",
		SortOrder:   "asc",
		Q:           input.Code,
		Country:     input.Country,
		CreditLevel: input.CreditLevel,
		Enabled:     input.Enabled,
	}
	page, err := service.List(context.Background(), query)
	if err != nil {
		t.Fatalf("List() error = %v", err)
	}
	if page.Total != 1 || len(page.Data) != 1 || page.Data[0].ID != created.ID {
		t.Fatalf("List() = %#v", page)
	}
	updatedValue := "VALUE_02"
	updated, err := service.Update(context.Background(), created.ID, &UpdateSupplierInput{Name: &updatedValue})
	if err != nil {
		t.Fatalf("Update() error = %v", err)
	}
	if updated.Name != updatedValue {
		t.Fatalf("updated name = %q", updated.Name)
	}
	events, committed = collector.snapshot()
	if events[len(events)-1].EventName() != "procurement.supplier.updated" || !committed[len(committed)-1] {
		t.Fatalf("updated events = %#v, committed = %#v", events, committed)
	}

	var exported strings.Builder
	if err := service.Export(context.Background(), ListSupplierQuery{}, &exported); err != nil {
		t.Fatalf("Export() error = %v", err)
	}
	if !strings.Contains(exported.String(), "id,") || !strings.Contains(exported.String(), created.ID) {
		t.Fatalf("Export() = %q", exported.String())
	}
	if got := csvSafe("=SUM(A1:A2)"); got != "'=SUM(A1:A2)" {
		t.Fatalf("csvSafe() = %q", got)
	}

	if err := service.Delete(context.Background(), second.ID); err != nil {
		t.Fatalf("Delete() error = %v", err)
	}
	if _, err := service.Get(context.Background(), second.ID); !errors.Is(err, ErrSupplierNotFound) {
		t.Fatalf("Get(deleted) error = %v, want not found", err)
	}
}

func validSupplierInput() *CreateSupplierInput {
	return &CreateSupplierInput{
		Code:         "VALUE_01",
		Name:         "VALUE_01",
		Country:      "VALUE_01",
		ContactName:  "VALUE_01",
		ContactEmail: "supplier@example.test",
	}
}

func testBool(value bool) *bool { return &value }

func openSupplierTestDatabase(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(filepath.Join(t.TempDir(), "supplier.db")), &gorm.Config{
		TranslateError: false,
		Logger:         logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("database handle: %v", err)
	}
	t.Cleanup(func() { _ = sqlDB.Close() })
	if err := db.Exec("CREATE TABLE mss_boot_migration (version TEXT PRIMARY KEY, apply_time DATETIME NOT NULL)").Error; err != nil {
		t.Fatalf("create migration table: %v", err)
	}
	prepareSupplierAuthorizationTestSchema(t, db)
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("RegisterMigration() error = %v", err)
	}
	runner.SetDb(db)
	runner.SetModel(new(migrationmodels.Migration))
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("MigrateContext() error = %v", err)
	}
	return db
}
