apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-ops-admin-db
  namespace: litellm
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local
  resources:
    requests:
      storage: 1Gi
