// Code generated by mss application template __MSS_GENERATOR_VERSION__. DO NOT EDIT.

import coreMessages from '__MSS_DISTRIBUTION_FRONTEND_PACKAGE__/runtime/locales/en-US';
import customMessages from '../business/locales/en-US';
import generatedMessages from '../generated/locales/en-US';

export default {
  ...coreMessages,
  ...generatedMessages,
  ...customMessages,
};
