// Code generated by mss application template __MSS_GENERATOR_VERSION__. DO NOT EDIT.

import coreMessages from '__MSS_DISTRIBUTION_FRONTEND_PACKAGE__/runtime/locales/zh-CN';
import customMessages from '../business/locales/zh-CN';
import generatedMessages from '../generated/locales/zh-CN';

export default {
  ...coreMessages,
  ...generatedMessages,
  ...customMessages,
};
