// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/api/github/callback": {
            "get": {
                "description": "github回调",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "generator"
                ],
                "summary": "github回调",
                "parameters": [
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GithubToken"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/admin/api/github/control": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建或更新github配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "generator"
                ],
                "summary": "创建或更新github配置",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GithubControlReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admin/api/github/get": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取github配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "generator"
                ],
                "summary": "获取github配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GithubGetResp"
                        }
                    }
                }
            }
        },
        "/admin/api/github/get-login-url": {
            "get": {
                "description": "获取github登录地址",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "generator"
                ],
                "summary": "获取github登录地址",
                "parameters": [
                    {
                        "type": "string",
                        "description": "state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/admin/api/language-defines": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建/更新",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "language_define"
                ],
                "summary": "创建/更新",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LanguageDefine"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/admin/api/language-defines/{id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "language_define"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin/api/language/all": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取所有语言",
                "tags": [
                    "language"
                ],
                "summary": "获取所有语言",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Language"
                            }
                        }
                    }
                }
            }
        },
        "/admin/api/languages": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Language列表数据",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "language"
                ],
                "summary": "Language列表数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Page"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Language"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建Language",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "language"
                ],
                "summary": "创建Language",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Language"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/admin/api/languages/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取Language",
                "tags": [
                    "language"
                ],
                "summary": "获取Language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Language"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新Language",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "language"
                ],
                "summary": "更新Language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Language"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除Language",
                "tags": [
                    "language"
                ],
                "summary": "删除Language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin/api/menu/authorize": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取菜单权限",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "获取菜单权限",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/models.Menu"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "children": {
                                                "type": "array",
                                                "items": {
                                                    "$ref": "#/definitions/models.Menu"
                                                }
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/admin/api/menu/authorize/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新菜单权限",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "更新菜单权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateAuthorizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admin/api/menu/tree": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取菜单树",
                "tags": [
                    "menu"
                ],
                "summary": "获取菜单树",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "allOf": [
                                    {
                                        "$ref": "#/definitions/models.Menu"
                                    },
                                    {
                                        "type": "object",
                                        "properties": {
                                            "children": {
                                                "type": "array",
                                                "items": {
                                                    "$ref": "#/definitions/models.Menu"
                                                }
                                            }
                                        }
                                    }
                                ]
                            }
                        }
                    }
                }
            }
        },
        "/admin/api/menus": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "菜单列表数据",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "菜单列表数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "parentID",
                        "name": "parentID",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Page"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Menu"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建菜单",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "创建菜单",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Menu"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/admin/api/menus/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取菜单",
                "tags": [
                    "menu"
                ],
                "summary": "获取菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "preloads",
                        "name": "preloads",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Menu"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新菜单",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "更新菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Menu"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除菜单",
                "tags": [
                    "menu"
                ],
                "summary": "删除菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin/api/model/migrate/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "迁移虚拟模型",
                "tags": [
                    "model"
                ],
                "summary": "迁移虚拟模型",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admin/api/role/authorize/{roleID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取角色授权",
                "tags": [
                    "role"
                ],
                "summary": "获取角色授权",
                "parameters": [
                    {
                        "type": "string",
                        "description": "roleID",
                        "name": "roleID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.GetAuthorizeResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "给角色授权",
                "tags": [
                    "role"
                ],
                "summary": "角色授权",
                "parameters": [
                    {
                        "type": "string",
                        "description": "roleID",
                        "name": "roleID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SetAuthorizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admin/api/roles": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "角色列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "角色列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "remark",
                        "name": "remark",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Page"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Role"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建角色",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "创建角色",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/admin/api/roles/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取角色",
                "tags": [
                    "role"
                ],
                "summary": "获取角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新角色",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除角色",
                "tags": [
                    "role"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin/api/task/{operate}/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "操作任务",
                "tags": [
                    "task"
                ],
                "summary": "操作任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "操作类型",
                        "name": "operate",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admin/api/tasks": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "任务列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "任务列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "remark",
                        "name": "remark",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Page"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.Task"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建任务",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "创建任务",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/admin/api/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取任务",
                "tags": [
                    "task"
                ],
                "summary": "获取任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新任务",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "task"
                ],
                "summary": "更新任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Task"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除任务",
                "tags": [
                    "task"
                ],
                "summary": "删除任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/admin/api/template/generate": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "从模版生成代码",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "generator"
                ],
                "summary": "从模版生成代码",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TemplateGenerateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TemplateGenerateResp"
                        }
                    }
                }
            }
        },
        "/admin/api/template/get-branches": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取template分支",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "generator"
                ],
                "summary": "获取template分支",
                "parameters": [
                    {
                        "type": "string",
                        "description": "template source",
                        "name": "source",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "access token",
                        "name": "accessToken",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TemplateGetBranchesResp"
                        }
                    }
                }
            }
        },
        "/admin/api/template/get-params": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取template参数配置",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "generator"
                ],
                "summary": "获取template参数配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "template source",
                        "name": "source",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "branch default:HEAD",
                        "name": "branch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "path default:.",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "access token",
                        "name": "accessToken",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TemplateGetParamsResp"
                        }
                    }
                }
            }
        },
        "/admin/api/template/get-path": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取template文件路径list",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "generator"
                ],
                "summary": "获取template文件路径list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "template source",
                        "name": "source",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "branch default:HEAD",
                        "name": "branch",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "access token",
                        "name": "accessToken",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TemplateGetPathResp"
                        }
                    }
                }
            }
        },
        "/admin/api/user/fakeCaptcha": {
            "post": {
                "description": "获取验证码",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取验证码",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FakeCaptchaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.FakeCaptchaResponse"
                        }
                    }
                }
            }
        },
        "/admin/api/user/login/account": {
            "post": {
                "description": "登录",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, \"expire\": \"2023-12-10T12:31:30+08:00\", \"token\": \"xxx\"}",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    }
                }
            }
        },
        "/admin/api/user/userInfo": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取登录用户信息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取登录用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新用户信息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admin/api/user/{userID}/password-reset": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "重置密码",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "userID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PasswordResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/admin/api/users": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "用户列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Page"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "创建用户",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "创建用户",
                "parameters": [
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        },
        "/admin/api/users/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取用户",
                "tags": [
                    "user"
                ],
                "summary": "获取用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新用户",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除用户",
                "tags": [
                    "user"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.FakeCaptchaRequest": {
            "type": "object",
            "required": [
                "phone"
            ],
            "properties": {
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.FakeCaptchaResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.GenerateParams": {
            "type": "object",
            "required": [
                "repo"
            ],
            "properties": {
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "repo": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                }
            }
        },
        "dto.GetAuthorizeResponse": {
            "type": "object",
            "properties": {
                "apiIDS": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "menuIDS": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roleID": {
                    "type": "string"
                }
            }
        },
        "dto.GithubControlReq": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "description": "github密码或者token",
                    "type": "string"
                }
            }
        },
        "dto.GithubGetResp": {
            "type": "object",
            "properties": {
                "configured": {
                    "description": "已配置",
                    "type": "boolean"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "email": {
                    "description": "github邮箱",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "dto.GithubToken": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "description": "AccessToken is the token that authorizes and authenticates\nthe requests.",
                    "type": "string"
                },
                "expiry": {
                    "description": "Expiry is the optional expiration time of the access token.\n\nIf zero, TokenSource implementations will reuse the same\ntoken forever and RefreshToken or equivalent\nmechanisms for that TokenSource will not be used.",
                    "type": "string"
                },
                "refreshToken": {
                    "description": "RefreshToken is a token that's used by the application\n(as opposed to the user) to refresh the access token\nif it expires.",
                    "type": "string"
                },
                "tokenType": {
                    "description": "TokenType is the type of token.\nThe Type method returns either this or \"Bearer\", the default.",
                    "type": "string"
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "expire": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.PasswordResetRequest": {
            "type": "object",
            "required": [
                "password",
                "userID"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "dto.SetAuthorizeRequest": {
            "type": "object",
            "properties": {
                "apiIDS": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "menuIDS": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.TemplateGenerateReq": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "generate": {
                    "$ref": "#/definitions/dto.GenerateParams"
                },
                "template": {
                    "$ref": "#/definitions/dto.TemplateParams"
                }
            }
        },
        "dto.TemplateGenerateResp": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                }
            }
        },
        "dto.TemplateGetBranchesResp": {
            "type": "object",
            "properties": {
                "branches": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.TemplateGetParamsResp": {
            "type": "object",
            "properties": {
                "params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TemplateParam"
                    }
                }
            }
        },
        "dto.TemplateGetPathResp": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.TemplateParam": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "tip": {
                    "type": "string"
                }
            }
        },
        "dto.TemplateParams": {
            "type": "object",
            "required": [
                "source"
            ],
            "properties": {
                "branch": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateAuthorizeRequest": {
            "type": "object",
            "required": [
                "keys",
                "roleID"
            ],
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roleID": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserInfoRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "Address 地址",
                    "type": "string"
                },
                "avatar": {
                    "description": "Avatar 头像",
                    "type": "string"
                },
                "city": {
                    "description": "City 城市",
                    "type": "string"
                },
                "country": {
                    "description": "Country 国家",
                    "type": "string"
                },
                "email": {
                    "description": "Email 邮箱",
                    "type": "string"
                },
                "group": {
                    "description": "Group 组别",
                    "type": "string"
                },
                "name": {
                    "description": "Name 昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "Phone 手机号",
                    "type": "string"
                },
                "profile": {
                    "description": "Profile 个人简介",
                    "type": "string"
                },
                "province": {
                    "description": "Province 省份",
                    "type": "string"
                },
                "signature": {
                    "description": "Signature 个性签名",
                    "type": "string"
                },
                "tags": {
                    "description": "Tags 标签",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "description": "Title 职位",
                    "type": "string"
                }
            }
        },
        "models.Language": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt create time",
                    "type": "string"
                },
                "defines": {
                    "description": "Defines",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LanguageDefine"
                    }
                },
                "id": {
                    "description": "ID primary key",
                    "type": "string"
                },
                "name": {
                    "description": "Name 名称",
                    "type": "string"
                },
                "status": {
                    "description": "Statue 状态",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "UpdatedAt update time",
                    "type": "string"
                }
            }
        },
        "models.LanguageDefine": {
            "type": "object",
            "required": [
                "group",
                "key",
                "languageID",
                "value"
            ],
            "properties": {
                "createdAt": {
                    "description": "CreatedAt create time",
                    "type": "string"
                },
                "group": {
                    "description": "Group 分组",
                    "type": "string"
                },
                "id": {
                    "description": "ID primary key",
                    "type": "string"
                },
                "key": {
                    "description": "Key 键",
                    "type": "string"
                },
                "languageID": {
                    "description": "LanguageID 语言ID",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "UpdatedAt update time",
                    "type": "string"
                },
                "value": {
                    "description": "Value 值",
                    "type": "string"
                }
            }
        },
        "models.Menu": {
            "type": "object",
            "properties": {
                "access": {
                    "description": "Access 权限配置，需要与 plugin-access 插件配合使用",
                    "type": "string"
                },
                "component": {
                    "description": "Component 组件",
                    "type": "string"
                },
                "createdAt": {
                    "description": "CreatedAt create time",
                    "type": "string"
                },
                "fixSiderbar": {
                    "description": "FixedSideBar 固定菜单",
                    "type": "boolean"
                },
                "fixedHeader": {
                    "description": "FixedHeader 固定顶栏",
                    "type": "boolean"
                },
                "flatMenu": {
                    "description": "FlatMenu 子项往上提，仍旧展示",
                    "type": "boolean"
                },
                "footerRender": {
                    "description": "FooterRender 不展示页脚",
                    "type": "boolean"
                },
                "headerRender": {
                    "description": "HeaderRender 不展示顶栏",
                    "type": "boolean"
                },
                "headerTheme": {
                    "description": "HeaderTheme 顶部导航的主题，mix 模式生效",
                    "type": "string"
                },
                "hideChildrenInMenu": {
                    "description": "HideChildrenInMenu 隐藏子菜单",
                    "type": "boolean"
                },
                "hideInBreadcrumb": {
                    "description": "HideInBreadcrumb 在面包屑中隐藏",
                    "type": "boolean"
                },
                "hideInMenu": {
                    "description": "HideInMenu 隐藏自己和子菜单",
                    "type": "boolean"
                },
                "icon": {
                    "description": "Icon 图标",
                    "type": "string"
                },
                "id": {
                    "description": "ID primary key",
                    "type": "string"
                },
                "layout": {
                    "description": "Layout 导航菜单的位置, side 为正常模式，top菜单显示在顶部，mix 两种兼有",
                    "type": "string"
                },
                "menuHeaderRender": {
                    "description": "MenuHeaderRender 不展示菜单头部",
                    "type": "boolean"
                },
                "menuRender": {
                    "description": "MenuRender 不展示菜单",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name 菜单名称",
                    "type": "string"
                },
                "navTheme": {
                    "description": "NavTheme 导航菜单的主题",
                    "type": "string"
                },
                "parentID": {
                    "description": "ParentID 父级id",
                    "type": "string"
                },
                "path": {
                    "description": "// Title 菜单标题\nTitle string ` + "`" + `json:\"title\" gorm:\"column:title;comment:菜单标题;type:varchar(255);not null\"` + "`" + `\nPath 路由",
                    "type": "string"
                },
                "permission": {
                    "description": "Permission 菜单权限",
                    "type": "string"
                },
                "sort": {
                    "description": "Sort 排序",
                    "type": "integer"
                },
                "status": {
                    "description": "Status 状态",
                    "type": "integer"
                },
                "target": {
                    "description": "Target 新页面打开",
                    "type": "string"
                },
                "type": {
                    "description": "Type 菜单类型",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "UpdatedAt update time",
                    "type": "string"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt create time",
                    "type": "string"
                },
                "id": {
                    "description": "ID primary key",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "root": {
                    "type": "boolean"
                },
                "status": {
                    "description": "Status 状态",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "UpdatedAt update time",
                    "type": "string"
                }
            }
        },
        "models.Task": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "body": {
                    "type": "string"
                },
                "checkedAt": {
                    "type": "string"
                },
                "command": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "CreatedAt create time",
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "entryID": {
                    "type": "integer"
                },
                "id": {
                    "description": "ID primary key",
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "python": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "spec": {
                    "type": "string"
                },
                "status": {
                    "description": "Status 状态",
                    "type": "integer"
                },
                "timeout": {
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "UpdatedAt update time",
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avatar": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "CreatedAt create time",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "description": "ID primary key",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "permissions": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "phone": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                },
                "province": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "description": "Status 状态",
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "UpdatedAt update time",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserLogin": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "status": {
                    "description": "Status 状态",
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.Page": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "errorCode": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "showType": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "traceId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "admin API",
	Description:      "admin接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
