// Code generated by mss application template __MSS_GENERATOR_VERSION__. DO NOT EDIT.

import type { AdminBusinessRoute } from '__MSS_DISTRIBUTION_FRONTEND_PACKAGE__/business';
import customBusinessRoutes from '../src/business/routes.config';
import generatedBusinessRoutes from './business-routes.generated';

const businessRoutes: AdminBusinessRoute[] = [...generatedBusinessRoutes, ...customBusinessRoutes];

export default businessRoutes;
