name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Install dependencies
        run: make deps
      - name: Unit Test
        run: make test
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o admin-${{ matrix.os }}-${{ matrix.arch }}
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-${{ matrix.os }}-${{ matrix.arch }}
          path: admin-${{ matrix.os }}-${{ matrix.arch }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Add exe
        run: |
          mv admin-windows-amd64 admin-windows-amd64.exe
          mv admin-windows-arm64 admin-windows-arm64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/admin-linux-amd64
            ${{ github.workspace }}/admin-linux-arm64
            ${{ github.workspace }}/admin-darwin-amd64
            ${{ github.workspace }}/admin-darwin-arm64
            ${{ github.workspace }}/admin-windows-amd64.exe
            ${{ github.workspace }}/admin-windows-arm64.exe
          prerelease: false
          append_body: |
            ## Pull Image
            ```shell
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref }}
            ```